/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import static Screen_laborales.PInsertTMP.ventanaAbierta;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.org.querys.V1querys;
import mx.org.querys.V2querysNE;
import mx.org.querys.V3Querys;
import mx.org.querys.federal.FedV1Querys;


/**
 *
 * @author ANTONIO.CORIA
 */
public class Errores_InsertTMP extends javax.swing.JFrame {

    public static String entidad = "", claveorgano = "", periodo = "", TRegistros = "",TRegistrosInse;
    public static int AllTRegistrosInse=0;
    ArrayList<String[]> ArrayClave_organo, ArrayClave_entidad;
    V1querys query = new V1querys();//Intanciar clase V1querys con nombre query
    V2querysNE queryNE = new V2querysNE();//Intanciar clase V2querysNE con nombre queryNE
    V3Querys V3queryNE = new V3Querys();//Intanciar clase V3querys con nombre V3queryNE
    FedV1Querys V1FedQuerys = new FedV1Querys();
    ArrayList<String[]> ArrayErroresIns,ArrayTablas;
    PInsertTMP PTMP = new PInsertTMP();
    String[] errorarray;
    String part0 = "", part1 = "", part2 = "", part3 = "", part4 = "", part5 = "", part6 = "", part7 = "", part8 = "";

    public Errores_InsertTMP() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(25);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(700);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(25);
         jTable1.getColumnModel().getColumn(6).setPreferredWidth(25);
        jLabel5.setVisible(false);
        jProgressBar1.setVisible(false);
        Tperiodo.setText(PTMP.Periodo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        RBentidad = new javax.swing.JRadioButton();
        RBclaveorgano = new javax.swing.JRadioButton();
        Cclaveorgano = new javax.swing.JComboBox();
        Centidad = new javax.swing.JComboBox();
        Tperiodo = new javax.swing.JTextField();
        Bperiodo = new javax.swing.JButton();
        Bmostrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Bborrar = new javax.swing.JButton();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jRadioButton1 = new javax.swing.JRadioButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Errores Insert TMP");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Errores Insert");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 634, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(RBentidad);
        RBentidad.setText("Entidad");
        RBentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBentidadActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBclaveorgano);
        RBclaveorgano.setText("Clave Organo");
        RBclaveorgano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBclaveorganoActionPerformed(evt);
            }
        });

        Cclaveorgano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CclaveorganoActionPerformed(evt);
            }
        });

        Centidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CentidadActionPerformed(evt);
            }
        });

        Bperiodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/consultar.png"))); // NOI18N
        Bperiodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BperiodoActionPerformed(evt);
            }
        });

        Bmostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/actualizar.png"))); // NOI18N
        Bmostrar.setText("Actualizar");
        Bmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmostrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Periodo");

        Bborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Borrar.png"))); // NOI18N
        Bborrar.setText("Actualizar");
        Bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BborrarActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setName(""); // NOI18N

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setName(""); // NOI18N

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setName(""); // NOI18N

        jRadioButton1.setText("All_TABLES");

        jLabel5.setText("Cargando.....");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(174, 174, 174)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(Tperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 671, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RBentidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(RBclaveorgano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cclaveorgano, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(165, 165, 165))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Bmostrar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addComponent(Bborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(Bperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 657, Short.MAX_VALUE)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bperiodo)
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Bmostrar)
                                    .addComponent(Bborrar)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RBentidad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RBclaveorgano)
                                    .addComponent(Cclaveorgano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TABLA", "CLAVE_ORGANO", "CLAVE_EXPEDIENTE", "ID", "EXCEPCION", "USUARIO", "FECHA_HORA"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setColumnSelectionAllowed(false);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
      entidad = "";
      claveorgano="";
      ventanaAbierta=false;
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Centidad.setVisible(false);
        Cclaveorgano.setVisible(false);
        Tperiodo.setVisible(false);
        Bperiodo.setVisible(false);
        jLabel4.setVisible(false);
        Bborrar.setVisible(false);
        label2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void RBentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBentidadActionPerformed
        // TODO add your handling code here:
        if (RBentidad.isSelected() == true) {
            llenaComboEntidad();
            Centidad.setVisible(true);
            Cclaveorgano.setVisible(false);
            Tperiodo.setVisible(true);
            Bperiodo.setVisible(true);
            jLabel4.setVisible(true);
            entidad ="";
            entidad = Centidad.getSelectedItem().toString();
            claveorgano = "";

        } else {
            Centidad.setVisible(false);
        }

    }//GEN-LAST:event_RBentidadActionPerformed

    private void RBclaveorganoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBclaveorganoActionPerformed
        // TODO add your handling code here:
        if (RBclaveorgano.isSelected() == true) {
            llenaComboClaveorgano();
            Cclaveorgano.setVisible(true);
            Centidad.setVisible(false);
            Tperiodo.setVisible(true);
            Bperiodo.setVisible(true);
            jLabel4.setVisible(true);
            claveorgano="";
            claveorgano = Cclaveorgano.getSelectedItem().toString();
            entidad = "";
        } else {
            Cclaveorgano.setVisible(false);
        }
    }//GEN-LAST:event_RBclaveorganoActionPerformed

    private void BperiodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BperiodoActionPerformed
        // TODO add your handling code here:
        PConPer periodo = new PConPer();
        periodo.setVisible(true);
    }//GEN-LAST:event_BperiodoActionPerformed

    private void CentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CentidadActionPerformed
        // TODO add your handling code here:
        if (Centidad.getSelectedIndex() == -1) {
        } else {
            entidad ="";
            entidad = Centidad.getSelectedItem().toString();
        }

    }//GEN-LAST:event_CentidadActionPerformed

    private void CclaveorganoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CclaveorganoActionPerformed
        // TODO add your handling code here:
        if (Cclaveorgano.getSelectedIndex() == -1) {
        } else {
            claveorgano ="";
            claveorgano = Cclaveorgano.getSelectedItem().toString();
        }
    }//GEN-LAST:event_CclaveorganoActionPerformed

    private void BmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmostrarActionPerformed
        // TODO add your handling code here:
      
        
        periodo = Tperiodo.getText();
        limpiarTabla();
         new Thread(() -> {
        if (jRadioButton1.isSelected()){
          jProgressBar1.setVisible(true);
          jLabel5.setVisible(true); 
          jLabel3.setText("ALL_TABLES");
          ArrayErroresIns = V3queryNE.TAllErroresInser(PTMP.tabla, claveorgano, entidad, periodo); 
        }else{
          jLabel3.setText("''" + PTMP.tabla + "''");  
          ArrayErroresIns = V3queryNE.TErroresInser(PTMP.tabla, claveorgano, entidad, periodo);   
        }
        TRegistrosInse="";
        if (jRadioButton1.isSelected()){
    String[] ArrayTablas = new String[21];
    ArrayTablas[0]="V3_TMP_CONTROL_EXPEDIENTEJL";
    ArrayTablas[1]="V3_TMP_AUDIENCIASJL";
    ArrayTablas[2]="V3_TMP_ORDINARIOJL";
    ArrayTablas[3]="V3_TMP_PART_ACT_ORDINARIOJL";
    ArrayTablas[4]="V3_TMP_PART_DEM_ORDINARIOJL";
    ArrayTablas[5]="V3_TMP_INDIVIDUALJL";
    ArrayTablas[6]="V3_TMP_PART_ACT_INDIVIDUALJL";
    ArrayTablas[7]="V3_TMP_PART_DEM_INDIVIDUALJL";
    ArrayTablas[8]="V3_TMP_COLECTIVOJL";
    ArrayTablas[9]="V3_TMP_PART_ACT_COLECTIVOJL";
    ArrayTablas[10]="V3_TMP_PART_DEM_COLECTIVOJL";
    ArrayTablas[11]="V3_TMP_HUELGAJL";
    ArrayTablas[12]="V3_TMP_PART_ACT_HUELGAJL";
    ArrayTablas[13]="V3_TMP_PART_DEM_HUELGAJL";
    ArrayTablas[14]="V3_TMP_COLECT_ECONOMJL";
    ArrayTablas[15]="V3_TMP_PART_ACT_COLECT_ECONOMJL";
    ArrayTablas[16]="V3_TMP_PART_DEM_COLECT_ECONOMJL";
    ArrayTablas[17]="V3_TMP_PARAPROCESALJL";
    ArrayTablas[18]="V3_TMP_PREF_CREDITOJL";
    ArrayTablas[19]="V3_TMP_TERCERIASJL";
    ArrayTablas[20]="V3_TMP_EJECUCIONJL";
    int contador=5;
    for (int i=0;i<=20;i++)
     {    
     TRegistrosInse=V3queryNE.Total_Reg_insertados(ArrayTablas[i], entidad, claveorgano, periodo);
     jProgressBar1.setValue(contador);
     contador=contador+5;
     AllTRegistrosInse=AllTRegistrosInse+Integer.parseInt(TRegistrosInse);
         System.out.println("totalregistros"+AllTRegistrosInse);
     }  
     TRegistros = V3queryNE.AllTotal_Reg_NI(PTMP.tabla, entidad, claveorgano, periodo); 
     jProgressBar1.setVisible(false);
     label3.setText("Total Insertados:"+AllTRegistrosInse); 
     }else
     {
         TRegistros = V3queryNE.Total_Reg_NI(PTMP.tabla, entidad, claveorgano, periodo);
          TRegistrosInse=V3queryNE.Total_Reg_insertados(PTMP.tabla, entidad, claveorgano, periodo);  
           label3.setText("Total Insertados:"+TRegistrosInse);   
     }
         
        //label4.setText("Total Reg en .CSV:"+TotalRegistros);
        
        if (ArrayErroresIns.size() > 0) {
            Bborrar.setVisible(true);
            label2.setText("Total No Insertados: "+TRegistros);
            label2.setVisible(true);
            DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
            Object[] fila = new Object[8];
            for (int j = 0; j < ArrayErroresIns.size(); j++) {
                String Periodo = Arrays.toString(ArrayErroresIns.get(j)).replace("[", "").replace("]", "");
                errorarray = Periodo.split(",");
                part0 = errorarray[0].trim();
                part1 = errorarray[1].trim();
                part2 = errorarray[2].trim();
                part3 = errorarray[3].trim();
                part4 = errorarray[4].trim();
                part5 = errorarray[5].trim();
                part6 = errorarray[6].trim();
                 part6 = errorarray[7].trim();
                fila[0] = part0;
                fila[1] = part1;
                fila[2] = part2;
                fila[3] = part3;
                fila[4] = part4;
                fila[5] = part5;
                fila[6] = part6;
                TablaError.addRow(fila);
                Class<?> col_class = jTable1.getColumnClass(0);
                jTable1.setDefaultEditor(col_class, null);

            }
        jProgressBar1.setVisible(false);
        jLabel5.setVisible(false);  
        } else {
            Bborrar.setVisible(false);
            label2.setVisible(false);
            limpiarTabla();
            JOptionPane.showMessageDialog(null, "No se encontraron registros con Error de insert", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        
         }).start();

    }//GEN-LAST:event_BmostrarActionPerformed

    public void limpiarTabla() {
        DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
        while (TablaError.getRowCount() > 0) {
            TablaError.removeRow(0);
        }
    }

    private void BborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BborrarActionPerformed
        // TODO add your handling code here:
    
        if(jRadioButton1.isSelected()){
           ArrayTablas=V3queryNE.TablaErroresInsert(entidad, claveorgano, periodo);
           int resp = JOptionPane.showConfirmDialog(null, "¿Desea Eliminar los registros de las tablas con errores de insert?", "Alerta!", JOptionPane.YES_NO_OPTION);    
           String Tabla="";
           if (resp == JOptionPane.YES_OPTION) {
                for (int i=0;i<ArrayTablas.size();i++)
                {
                    System.out.println("tablas"+Arrays.toString(ArrayTablas.get(i)).replace("[", "").replace("]", ""));
                    Tabla=Arrays.toString(ArrayTablas.get(i)).replace("[", "").replace("]", "");
                    V3queryNE.EliminaRegERRORES_INSERT_RALAB(Tabla, entidad, claveorgano, periodo);
                     V3queryNE.EliminaRegTMPRalab(Tabla, entidad, claveorgano, periodo);
                      JOptionPane.showMessageDialog(null, "Se han eliminado los registros de la tabla:" + Arrays.toString(ArrayTablas.get(i)) + "   ,v3_errores_insert_ralabTMP", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            Bborrar.setVisible(false);
            label2.setVisible(false);
            label3.setText("");
            label4.setText("");
                
            }
        }
        else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Desea Eliminar los registros de la tabla:" + PTMP.tabla + "? para volver a insertar", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            V3queryNE.EliminaRegERRORES_INSERT_RALAB(PTMP.tabla, entidad, claveorgano, periodo);
            V3queryNE.EliminaRegTMPRalab(PTMP.tabla, entidad, claveorgano, periodo);
            JOptionPane.showMessageDialog(null, "Se han eliminado los registros de la tabla:" + PTMP.tabla + "   ,v3_errores_insert_ralabTMP", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            //limpiarTabla();
            Bborrar.setVisible(false);
            label2.setVisible(false);
            label3.setText("");
            label4.setText("");
        }
        }
    }//GEN-LAST:event_BborrarActionPerformed

    public void llenaComboEntidad() {

        if (PInsertTMP.Versiones.equals("V1")) {
            ArrayClave_entidad = query.Entidad();
        }
        if (PInsertTMP.Versiones.equals("V2")) {
            ArrayClave_entidad = queryNE.EntidadNE();
        }
        if (PInsertTMP.Versiones.equals("V3")) {
            ArrayClave_entidad = V3queryNE.EntidadNE();
        }
        if (PInsertTMP.Versiones.equals("V1")) {
            ArrayClave_entidad = V1FedQuerys.EntidadNE();
        }

        Centidad.removeAllItems();
        for (int i = 0; i < ArrayClave_entidad.size(); i++) {
            String Organo = (Arrays.toString(ArrayClave_entidad.get(i)));
            Centidad.addItem(Organo.replace("[", "").replace("]", ""));
        }
    }

    public void llenaComboClaveorgano() {

        if (PInsertTMP.Versiones.equals("V1")) {
            ArrayClave_organo = query.Clave_organo();
        }
        if (PInsertTMP.Versiones.equals("V2")) {
            ArrayClave_organo = queryNE.Clave_organoNE();
        }
        if (PInsertTMP.Versiones.equals("V3")) {
            ArrayClave_organo = V3queryNE.Clave_organoNE();
        }
        if (PInsertTMP.Versiones.equals("V1")) {
            ArrayClave_organo = V1FedQuerys.Clave_organoNE();
        }
        Cclaveorgano.removeAllItems();
        for (int i = 0; i < ArrayClave_organo.size(); i++) {
            String Organo = (Arrays.toString(ArrayClave_organo.get(i)));
            Cclaveorgano.addItem(Organo.replace("[", "").replace("]", ""));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Errores_InsertTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Errores_InsertTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Errores_InsertTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Errores_InsertTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bborrar;
    private javax.swing.JButton Bmostrar;
    private javax.swing.JButton Bperiodo;
    private javax.swing.JComboBox Cclaveorgano;
    private javax.swing.JComboBox Centidad;
    private javax.swing.JRadioButton RBclaveorgano;
    private javax.swing.JRadioButton RBentidad;
    private javax.swing.JTextField Tperiodo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
