/*  To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import static Screen_laborales.PInsertTR.ventanaAbierta;
import java.awt.Color;
import java.util.ArrayList;
import mx.org.querys.V3Querys;
import Screen_laborales.PInsertTR;
import java.awt.BorderLayout;
import java.awt.Container;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Errores_InsertTR extends javax.swing.JFrame {


     ArrayList<String[]> ArrayErroresIns,ArrayErroresInsInicio;
     V3Querys V3queryNE = new V3Querys();//Intanciar clase V3querys con nombre V3queryNE
     String[] errorarray;
     String part0 = "", part1 = "", part2 = "", part3 = "", part4 = "", part5 = "", part6 = "", part7 = "", part8 = "",T_reg="",T_regNI="",T_regTMP="",texto="";
     int TTRegNI=0;
    public static String Ttabla="",Tclave_organo="",Tclave_expediente="",Tid="";
    // JFrame f = new JFrame("Progreso Conteo Registristros TR");
     
    
    public Errores_InsertTR() {
        initComponents();
        jTextArea1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        LProgress.setVisible(false);
        jProgressBar1.setVisible(false);
       jTable1.getColumnModel().getColumn(0).setPreferredWidth(75); 
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(600);
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Bmostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        LProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Errores Insert TR");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Errores Insert");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TABLA", "CLAVE_ORGANO", "CLAVE_EXPEDIENTE", "ID", "EXCEPCION"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.setCellSelectionEnabled(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        Bmostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/actualizar.png"))); // NOI18N
        Bmostrar.setText("Actualizar");
        Bmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmostrarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        LProgress.setText("Procesando...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bmostrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LProgress)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bmostrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ventanaAbierta=false;
    }//GEN-LAST:event_formWindowClosed

    private void BmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmostrarActionPerformed


         new Thread(() -> { 
           if (!PInsertTR.tabla.equals("INICIO()")){
             DespliegaErrores();
         }else{
             despliegaErroresInicio();
         }
        }).start();      
        
        
         
         
    }//GEN-LAST:event_BmostrarActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        int selectedRowIndex = jTable1.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        if ((evt.getClickCount()==2)  && (evt.getButton()==1)){
          Ttabla="";
          Tclave_organo="";
          Tclave_expediente="";
          Tid="";      
          Ttabla=model.getValueAt(selectedRowIndex, 0).toString();
          Tclave_organo=model.getValueAt(selectedRowIndex, 1).toString();
          Tclave_expediente=model.getValueAt(selectedRowIndex, 2).toString();
          Tid=model.getValueAt(selectedRowIndex, 3).toString();
          Reg_NI Reg= new Reg_NI();
          Reg.setVisible(true);
         }
    }//GEN-LAST:event_jTable1MousePressed

    public void DespliegaErrores(){
        jTextArea1.setText("");
        LProgress.setVisible(false);
        jProgressBar1.setVisible(false);
        jTextArea1.setVisible(true);
        jLabel3.setText(PInsertTR.tabla);
        limpiarTabla();
        ArrayErroresIns=V3queryNE.TErroresInserTR(PInsertTR.tabla, PInsertTR.clave_organo, PInsertTR.clave_entidad, PInsertTR.periodo);       
        TextArea();     
         if ((ArrayErroresIns.size() > 0)){ 
             System.out.println("entro a no inicio");
            DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
            Object[] fila = new Object[8];
            for (int j = 0; j < ArrayErroresIns.size(); j++) {
                String Periodo = Arrays.toString(ArrayErroresIns.get(j)).replace("[", "").replace("]", "");
                errorarray = Periodo.split(",");
                part0 = errorarray[0].trim();
                part1 = errorarray[1].trim();
                part2 = errorarray[2].trim();
                part3 = errorarray[3].trim();
                part4 = errorarray[4].trim();
                part5 = errorarray[5].trim();
                part6 = errorarray[6].trim();
                fila[0] = part0;
                fila[1] = part1;
                fila[2] = part2;
                fila[3] = part3;
                fila[4] = part4;
                TablaError.addRow(fila);
                Class<?> col_class = jTable1.getColumnClass(0);
                jTable1.setDefaultEditor(col_class, null);

            }
        } else {
            limpiarTabla();
            JOptionPane.showMessageDialog(null, "No se encontraron registros con Error de insert", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void despliegaErroresInicio(){
        // TODO add your handling code here:
        jTextArea1.setText("");
        jTextArea1.setVisible(true);
        LProgress.setVisible(true);
        jProgressBar1.setVisible(true);
        jLabel3.setText(PInsertTR.tabla);
        limpiarTabla();    
        TextAreaInicio();   
       ArrayErroresInsInicio=V3queryNE.TErroresInserTRInicio(PInsertTR.clave_organo, PInsertTR.clave_entidad, PInsertTR.periodo);

         if (TTRegNI>0){ 
             System.out.println("entro a inicio");
            DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
            Object[] fila = new Object[8];
            for (int j = 0; j < ArrayErroresInsInicio.size(); j++) {
                String Periodo = Arrays.toString(ArrayErroresInsInicio.get(j)).replace("[", "").replace("]", "");
                errorarray = Periodo.split(",");
                part0 = errorarray[0].trim();
                part1 = errorarray[1].trim();
                part2 = errorarray[2].trim();
                part3 = errorarray[3].trim();
                part4 = errorarray[4].trim();
                part5 = errorarray[5].trim();
                part6 = errorarray[6].trim();
                fila[0] = part0;
                fila[1] = part1;
                fila[2] = part2;
                fila[3] = part3;
                fila[4] = part4;
                TablaError.addRow(fila);
                Class<?> col_class = jTable1.getColumnClass(0);
                jTable1.setDefaultEditor(col_class, null);

            }
        } else {
            limpiarTabla();
            JOptionPane.showMessageDialog(null, "No se encontraron registros con Error de insert", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void TextArea(){
        T_reg=V3queryNE.Total_Reg_insertadosTR(PInsertTR.tabla, PInsertTR.clave_entidad, PInsertTR.clave_organo, PInsertTR.periodo);
        T_regNI=V3queryNE.Total_Reg_NITR(PInsertTR.tabla, PInsertTR.clave_entidad, PInsertTR.clave_organo, PInsertTR.periodo);
        T_regTMP=V3queryNE.Total_Reg_TMP(PInsertTR.tabla, PInsertTR.clave_entidad, PInsertTR.clave_organo, PInsertTR.periodo);
        jTextArea1.setText(PInsertTR.tabla+": \n \n"
                + "Reg_TMP:"+T_regTMP +"   Reg_TR:"+T_reg+"   "+"Reg_NoIn:"+T_regNI);   
    }
    
    public void TextAreaInicio(){
    
    int progres=5;
    String[] ArrayTablas = new String[21];
    ArrayTablas[0]="V3_TR_CONTROL_EXPEDIENTEJL";
    ArrayTablas[1]="V3_TR_AUDIENCIASJL";
    ArrayTablas[2]="V3_TR_ORDINARIOJL";
    ArrayTablas[3]="V3_TR_PART_ACT_ORDINARIOJL";
    ArrayTablas[4]="V3_TR_PART_DEM_ORDINARIOJL";
    ArrayTablas[5]="V3_TR_INDIVIDUALJL";
    ArrayTablas[6]="V3_TR_PART_ACT_INDIVIDUALJL";
    ArrayTablas[7]="V3_TR_PART_DEM_INDIVIDUALJL";
    ArrayTablas[8]="V3_TR_COLECTIVOJL";
    ArrayTablas[9]="V3_TR_PART_ACT_COLECTIVOJL";
    ArrayTablas[10]="V3_TR_PART_DEM_COLECTIVOJL";
    ArrayTablas[11]="V3_TR_HUELGAJL";
    ArrayTablas[12]="V3_TR_PART_ACT_HUELGAJL";
    ArrayTablas[13]="V3_TR_PART_DEM_HUELGAJL";
    ArrayTablas[14]="V3_TR_COLECT_ECONOMJL";
    ArrayTablas[15]="V3_TR_PART_ACT_COLECT_ECONOMJL";
    ArrayTablas[16]="V3_TR_PART_DEM_COLECT_ECONOMJL";
    ArrayTablas[17]="V3_TR_PARAPROCESALJL";
    ArrayTablas[18]="V3_TR_PREF_CREDITOJL";
    ArrayTablas[19]="V3_TR_TERCERIASJL";
    ArrayTablas[20]="V3_TR_EJECUCIONJL";
        
     for (int i=0;i<=20;i++)
     {  
        T_reg=V3queryNE.Total_Reg_insertadosTR(ArrayTablas[i], PInsertTR.clave_entidad, PInsertTR.clave_organo, PInsertTR.periodo);
        T_regNI=V3queryNE.Total_Reg_NITR(ArrayTablas[i], PInsertTR.clave_entidad, PInsertTR.clave_organo, PInsertTR.periodo);
        T_regTMP=V3queryNE.Total_Reg_TMP(ArrayTablas[i], PInsertTR.clave_entidad, PInsertTR.clave_organo, PInsertTR.periodo);
        TTRegNI=TTRegNI+Integer.parseInt(T_regNI);
        texto=texto+ArrayTablas[i]+": \n \n"
                +"Reg_TMP:"+T_regTMP+"   Reg_TR:"+T_reg+"   "+"Reg_NoIn:"+T_regNI+ "\n"
                +"-----------------------------------------------------------------\n";
         progres=progres+5;
         jProgressBar1.setValue(progres);
     }
        jProgressBar1.setValue(0);
         LProgress.setVisible(false);
        jProgressBar1.setVisible(false);
        jTextArea1.setText(texto);  
    }
    
    
     public void limpiarTabla() {
       T_reg="";
       T_regNI="";
       T_regTMP="";
       TTRegNI=0;  
       texto="";
         System.out.println("limpio variables yea yea");
        DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
        while (TablaError.getRowCount() > 0) {
            TablaError.removeRow(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Errores_InsertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Errores_InsertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Errores_InsertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Errores_InsertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Errores_InsertTR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bmostrar;
    private javax.swing.JLabel LProgress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
