/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import static Screen_laborales.PInsertTR.BD;
import static Screen_laborales.PInsertTR.Versiones;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.BD.AcumulaTR;
import mx.org.querys.V1querys;
import mx.org.querys.V2querysNE;
import mx.org.querys.V3Querys;
import mx.org.querys.federal.FedV1Querys;

/**
 *
 * @author ANTONIO.CORIA
 */
public class PAcumula extends javax.swing.JFrame {

    /**
     * Creates new form PAcumula
     */
    public static String pru="",tabla = "", rutaT = "", Versiones = "", Nombre_archivo = "", Directorio = "", procedimiento, clave_entidad = "", clave_organo = "", periodo = "",periodo2="", NMunicipio = "", NENTIDAD = "", BD = "";
    List<String> testList = new ArrayList<String>();
    ArrayList<String[]> ArrayClave_organo, ArrayClave_entidad;
    V1querys query = new V1querys();//Intanciar clase V1querys con nombre query
    V2querysNE queryNE = new V2querysNE();//Intanciar clase V2querysNE con nombre queryNE
    V3Querys V3queryNE = new V3Querys();//Intanciar clase V3querys con nombre V3queryNE
    FedV1Querys V1FedQuerys = new FedV1Querys();

    public PAcumula() {
        initComponents();
        this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        jPanel1.setVisible(false);
        R1.setVisible(false);
        R2.setVisible(false);
        R3.setVisible(false);
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        JOEstatal = new javax.swing.JRadioButton();
        JOFederal = new javax.swing.JRadioButton();
        R1 = new javax.swing.JRadioButton();
        R2 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        LEntidad = new javax.swing.JLabel();
        Jorgano = new javax.swing.JLabel();
        CorganoJur = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Textoperiodo1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Textoperiodo2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RPrueba = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione BD"));

        JOEstatal.setBackground(new java.awt.Color(255, 255, 255));
        JOEstatal.setText("Estatal");
        JOEstatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOEstatalActionPerformed(evt);
            }
        });

        JOFederal.setBackground(new java.awt.Color(255, 255, 255));
        JOFederal.setText("Federal");
        JOFederal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOFederalActionPerformed(evt);
            }
        });

        R1.setText("VERSION 1.0");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });

        R2.setText("VERSION 2.0");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });

        R3.setText("VERSION 3.0");
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JOEstatal)
                    .addComponent(JOFederal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(R1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(R2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(R3)
                .addGap(136, 136, 136))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(JOEstatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JOFederal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1)
                    .addComponent(R2)
                    .addComponent(R3))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setToolTipText("");

        LEntidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        Jorgano.setText("Organo Jurisdiccional:");

        CorganoJur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CorganoJurItemStateChanged(evt);
            }
        });
        CorganoJur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorganoJurActionPerformed(evt);
            }
        });

        jLabel4.setText("Periodo:");

        Textoperiodo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Textoperiodo1KeyReleased(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/consultar.png"))); // NOI18N
        jButton2.setToolTipText("Seleccione para despliegue de periodos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Periodo Anterior:");

        Textoperiodo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Textoperiodo2KeyReleased(evt);
            }
        });

        jButton1.setText("Acumular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Entidad:");

        RPrueba.setText("PRUEBA");
        RPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPruebaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(Jorgano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Textoperiodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RPrueba)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(RPrueba)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jorgano)
                    .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Textoperiodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JOEstatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOEstatalActionPerformed
        // TODO add your handling code here:
        if (JOEstatal.isSelected()) {
            R1.setVisible(true);
            R2.setVisible(true);
            R3.setVisible(true);
            BD = "Estatal";
            CorganoJur.removeAllItems();
        }
    }//GEN-LAST:event_JOEstatalActionPerformed

    private void JOFederalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOFederalActionPerformed
        // TODO add your handling code here:
        if (JOFederal.isSelected()) {
            BD = "Federal";
            CorganoJur.removeAllItems();
        }
    }//GEN-LAST:event_JOFederalActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
        if (R1.isSelected()) {
            Versiones = "";
            Versiones = "1.0";

        }
    }//GEN-LAST:event_R1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        if (R2.isSelected()) {
            Versiones = "";
            Versiones = "2.0";

        }
    }//GEN-LAST:event_R2ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        if (R3.isSelected()) {
            Versiones = "";
            Versiones = "3.0";
            jPanel1.setVisible(true);
            llenaCombo();
        }
    }//GEN-LAST:event_R3ActionPerformed

  

    public void llenaCombo() {

        if (Versiones.equals("1.0") && (BD.equals("Estatal"))) {
            ArrayClave_organo = query.Clave_organo();
        }
        if (Versiones.equals("2.0") && (BD.equals("Estatal"))) {
            ArrayClave_organo = queryNE.Clave_organoNE();
        }
        if (Versiones.equals("3.0") && (BD.equals("Estatal"))) {
            ArrayClave_organo = V3queryNE.Clave_organoAcumula();
        }
        if (Versiones.equals("1.0") && (BD.equals("Federal"))) {
            ArrayClave_organo = V1FedQuerys.Clave_organoNE();
        }
        CorganoJur.removeAllItems();
        for (int i = 0; i < ArrayClave_organo.size(); i++) {
            String Organo = (Arrays.toString(ArrayClave_organo.get(i)));
            CorganoJur.addItem(Organo.replace("[", "").replace("]", ""));
        }
    }

    private void CorganoJurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CorganoJurItemStateChanged
        // TODO add your handling code here:
        NEntidad_COrgano();
    }//GEN-LAST:event_CorganoJurItemStateChanged

    private void CorganoJurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorganoJurActionPerformed
        // TODO add your handling code here:

        /* if (CorganoJur.getSelectedItem().toString().substring(0, 2).equals("04"))
         {

         }else{

         }*/
        Valores();
    }//GEN-LAST:event_CorganoJurActionPerformed

    private void Textoperiodo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Textoperiodo1KeyReleased
        // TODO add your handling code here:
        Valores();
    }//GEN-LAST:event_Textoperiodo1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Valores();
        PConPer per = new PConPer();
        per.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Textoperiodo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Textoperiodo2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Textoperiodo2KeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
           new Thread(() -> {
                  Valores();
                if (!Textoperiodo1.getText().equals("") && !Textoperiodo2.getText().equals("") ){
         int resp = JOptionPane.showConfirmDialog(null, "¿Desea acumular la información con clave_organo="+clave_organo+" \n"+" Periodo_Actual="+periodo+" \n Periodo_Anterior="+periodo2, "Alerta!", JOptionPane.YES_NO_OPTION);  
        if (resp == JOptionPane.YES_OPTION) { 
           AcumulaTR tr=new AcumulaTR();
           Reg_Acumula Ac=new Reg_Acumula();
               try {
                   tr.Acumula();
                   Ac.setVisible(true);
               } catch (IOException ex) {
                   Logger.getLogger(PAcumula.class.getName()).log(Level.SEVERE, null, ex);
               } catch (SQLException ex) {
                   Logger.getLogger(PAcumula.class.getName()).log(Level.SEVERE, null, ex);
               }
           
        }
         }else{
             JOptionPane.showMessageDialog(null, "Favor de ingresar periodo a acumular", "Acumula", JOptionPane.WARNING_MESSAGE);
                }
        }).start();      
            
            
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
       
    
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         clave_entidad="";
        clave_organo="";
        PMenu menu = new PMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void RPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPruebaActionPerformed
        // TODO add your handling code here:
        if (RPrueba.isSelected()==true)
        {
         pru="1";   
        }else
        {
         pru="0";   
        }
            
        
    }//GEN-LAST:event_RPruebaActionPerformed

    
    
   

    public void NEntidad_COrgano() {

        if (CorganoJur.getItemCount() > 0) {
            System.out.println(CorganoJur.getSelectedItem().toString().substring(0, 2));
            switch (CorganoJur.getSelectedItem().toString().substring(0, 2)) {
                case "01":
                    LEntidad.setText("Aguascalientes");
                    break;
                case "02":
                    LEntidad.setText("Baja California");
                    break;
                case "03":
                    LEntidad.setText("Baja California Sur");
                    break;
                case "04":
                    LEntidad.setText("Campeche");
                    break;
                case "05":
                    LEntidad.setText("Coahuila de Zaragoza");
                    break;
                case "06":
                    LEntidad.setText("Colima");
                    break;
                case "07":
                    LEntidad.setText("Chiapas");
                    break;
                case "08":
                    LEntidad.setText("Chihuahua");
                    break;
                case "09":
                    LEntidad.setText("Ciudad de México");
                    break;
                case "10":
                    LEntidad.setText("Durango");
                    break;
                case "11":
                    LEntidad.setText("Guanajuato");
                    break;
                case "12":
                    LEntidad.setText("Guerrero");
                    break;
                case "13":
                    LEntidad.setText("Hidalgo");
                    break;
                case "14":
                    LEntidad.setText("Jalisco");
                    break;
                case "15":
                    LEntidad.setText("México");
                    break;
                case "16":
                    LEntidad.setText("Michoacán de Ocampo");
                    break;
                case "17":
                    LEntidad.setText("Morelos");
                    break;
                case "18":
                    LEntidad.setText("Nayarit");
                    break;
                case "19":
                    LEntidad.setText("Nuevo León");
                    break;
                case "20":
                    LEntidad.setText("Oaxaca");
                    break;
                case "21":
                    LEntidad.setText("Puebla");
                    break;
                case "22":
                    LEntidad.setText("Querétaro");
                    break;
                case "23":
                    LEntidad.setText("Quintana Roo");
                    break;
                case "24":
                    LEntidad.setText("San Luis Potosí");
                    break;
                case "25":
                    LEntidad.setText("Sinaloa");
                    break;
                case "26":
                    LEntidad.setText("Sonora");
                    break;
                case "27":
                    LEntidad.setText("Tabasco");
                    break;
                case "28":
                    LEntidad.setText("Tamaulipas");
                    break;
                case "29":
                    LEntidad.setText("Tlaxcala");
                    break;
                case "30":
                    LEntidad.setText("Veracruz de Ignacio de la Llave");
                    break;
                case "31":
                    LEntidad.setText("Yucatán");
                    break;
                case "32":
                    LEntidad.setText("Zacatecas");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "No se Encontro Entidad", "Valida", JOptionPane.WARNING_MESSAGE);
                    JOptionPane.showMessageDialog(null, "Favor de contactar al Administrador", "Valida", JOptionPane.WARNING_MESSAGE);
            }
        }

    }

    public void Valores() {
            clave_entidad = "";
        clave_organo = "";
        clave_organo = CorganoJur.getSelectedItem().toString();
        periodo = Textoperiodo1.getText();
        periodo2 = Textoperiodo2.getText();
        NMunicipio = LEntidad.getText();
        NENTIDAD = LEntidad.getText();
        if (RPrueba.isSelected() == true) {
            pru = "1";
        } else {
            pru = "0";
        }
            System.out.println("valoreeeees" + clave_organo + " " + clave_entidad + " " + periodo+" "+pru);

        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAcumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAcumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAcumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAcumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAcumula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CorganoJur;
    private javax.swing.JRadioButton JOEstatal;
    private javax.swing.JRadioButton JOFederal;
    private javax.swing.JLabel Jorgano;
    private javax.swing.JLabel LEntidad;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JRadioButton RPrueba;
    public javax.swing.JTextField Textoperiodo1;
    public javax.swing.JTextField Textoperiodo2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
