/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import static Screen_laborales.PEstatus.Testatus;
import java.awt.Color;
import javax.swing.JOptionPane;
import mx.org.querys.QEstatus;

/**
 *
 * @author ANTONIO.CORIA
 */
public class PCambioEstatus extends javax.swing.JFrame {

    
    public static String periodo="",clave_organo="",estatus="";
    QEstatus est=new QEstatus();
    
    /**
     * Creates new form PCambioEstatus
     */
    public PCambioEstatus() {
        initComponents();
        this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        ValoresEstatus();
    }
    
    public void ValoresEstatus()
    {
        JTid_control.setText(PEstatus.Tid_control);
        JTclave_organo.setText(PEstatus.Tclave_organo);
        JTsede.setText(PEstatus.Tsede);
        JTentidad_clave.setText(PEstatus.Tentidad_clave);
        JTentidad_nombre.setText(PEstatus.Tentidad_nombre);
        JTmunicipio_clave.setText(PEstatus.Tmunicipio_clave);
        JTmunicipio_nombre.setText(PEstatus.Tmunicipio_nombre);
        JTperiodo.setText(PEstatus.Tperiodo);
        Cestatus.setSelectedItem(PEstatus.Testatus);
        
    }
    
    public void ValoresQuery(){
        periodo=JTperiodo.getText();
        clave_organo=JTclave_organo.getText();
        estatus=Cestatus.getSelectedItem().toString();
    }
    
    public void cambioEstatus()
    {
         if (PEstatus.version.equals("1.0") && (PEstatus.BD.equals("Estatal")))
        {
            System.out.println("cambiando v1+estatal");
            est.V1CambioEstatus();
        
        }
        if (PEstatus.version.equals("2.0") && (PEstatus.BD.equals("Estatal")))
        {
            System.out.println("cambiando v2+estatal");
             est.V2CambioEstatus();
       
        }
        if (PEstatus.version.equals("3.0") && (PEstatus.BD.equals("Estatal")))
        {
            System.out.println("cambiando v3+estatal");
             est.V3CambioEstatus();
       
        }
        if (PEstatus.version.equals("Estructura_Definita") && (PEstatus.BD.equals("Estatal")))
        {
            System.out.println("cambiando estructura+definitiva+estatal");
             est.EDCambioEstatus();
       
        }
         if (PEstatus.version.equals("1.0") && (PEstatus.BD.equals("Federal")))
        {
        
             System.out.println("cambiando v1+federal");
              est.V1FedCambioEstatus();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Cestatus = new javax.swing.JComboBox();
        GuardarCamEst = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JTid_control = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTclave_organo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTsede = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTentidad_clave = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTentidad_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JTperiodo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTmunicipio_clave = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JTmunicipio_nombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("ESTATUS");

        Cestatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "C" }));
        Cestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CestatusActionPerformed(evt);
            }
        });

        GuardarCamEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Guardar.png"))); // NOI18N
        GuardarCamEst.setToolTipText("Guardar Cambios");
        GuardarCamEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCamEstActionPerformed(evt);
            }
        });

        jLabel2.setText("ID_CONTROL");

        JTid_control.setEditable(false);

        jLabel3.setText("CLAVE DE ORGANO");

        JTclave_organo.setEditable(false);

        jLabel4.setText("SEDE");

        JTsede.setEditable(false);

        jLabel5.setText("ENTIDAD CLAVE");

        JTentidad_clave.setEditable(false);

        jLabel6.setText("ENTIDAD NOMBRE");

        JTentidad_nombre.setEditable(false);

        jLabel9.setText("PERIODO");

        JTperiodo.setEditable(false);

        jLabel7.setText("MUNICIPIO CLAVE");

        JTmunicipio_clave.setEditable(false);

        jLabel8.setText("MUNICIPIO NOMBRE");

        JTmunicipio_nombre.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTid_control, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTclave_organo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JTmunicipio_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JTsede, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JTentidad_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JTmunicipio_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JTentidad_nombre)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GuardarCamEst, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTid_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTclave_organo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTsede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(JTentidad_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JTentidad_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(JTperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTmunicipio_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(JTmunicipio_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Cestatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(GuardarCamEst, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarCamEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCamEstActionPerformed
        // TODO add your handling code here:
        if ((JTid_control.getText().isEmpty()) || (JTclave_organo.getText().isEmpty()) || (JTsede.getText().isEmpty()) || (JTentidad_clave.getText().isEmpty()) || (JTentidad_nombre.getText().isEmpty()) || (JTmunicipio_clave.getText().isEmpty()) || (JTmunicipio_nombre.getText().isEmpty()) || (JTperiodo.getText().isEmpty()) )
        {
           JOptionPane.showMessageDialog(null, "Error al guardar", "Save", JOptionPane.WARNING_MESSAGE); 
        }
        else
        {
        ValoresQuery();    
        int resp = JOptionPane.showConfirmDialog(null, "¿Desea modificar el estatus con clave_organo="+clave_organo+" y periodo="+periodo+"", "Alerta!", JOptionPane.YES_NO_OPTION);  
        if (resp == JOptionPane.YES_OPTION) {
         cambioEstatus();
         JOptionPane.showMessageDialog(null, "El estatus se actualizo correctamente", "Save", JOptionPane.INFORMATION_MESSAGE); 
         this.setVisible(false);
        }
        
        }
        
        
        
    }//GEN-LAST:event_GuardarCamEstActionPerformed

    private void CestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CestatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PCambioEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PCambioEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PCambioEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PCambioEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PCambioEstatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Cestatus;
    private javax.swing.JButton GuardarCamEst;
    private javax.swing.JTextField JTclave_organo;
    private javax.swing.JTextField JTentidad_clave;
    private javax.swing.JTextField JTentidad_nombre;
    private javax.swing.JTextField JTid_control;
    private javax.swing.JTextField JTmunicipio_clave;
    private javax.swing.JTextField JTmunicipio_nombre;
    private javax.swing.JTextField JTperiodo;
    private javax.swing.JTextField JTsede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
