/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import Conexion.OracleDAOFactory;
import java.awt.Color;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.BD.LimpiaBD;
import mx.org.querys.V1querys;
import mx.org.querys.V2querysNE;
import mx.org.querys.V3Querys;
import mx.org.querys.federal.FedV1Querys;

/**
 *
 * @author ANTONIO.CORIA
 */
public class PCleaner extends javax.swing.JFrame {

    /**
     * Creates new form PCleaner
     */
     public static String tabla="",rutaT="",Versiones="",Nombre_archivo="",Directorio="",procedimiento,clave_entidad="",clave_organo="",periodo="",NMunicipio="",NENTIDAD="",BD="";
      List<String> testList = new ArrayList<String>();
     List<String> testProc = new ArrayList<String>();
     String TexTabla="",TexProc;
     V1querys query=new V1querys();//Intanciar clase V1querys con nombre query
     V2querysNE queryNE=new V2querysNE();//Intanciar clase V2querysNE con nombre queryNE
     V3Querys V3queryNE=new V3Querys();//Intanciar clase V3querys con nombre V3queryNE
     FedV1Querys V1FedQuerys=new FedV1Querys();
      ArrayList<String[]> ArrayClave_organo,ArrayClave_entidad;
      
    public PCleaner() {
        initComponents();
         this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        jPanel1.setVisible(false);
        R1.setVisible(false);
        R2.setVisible(false);
        R3.setVisible(false);
        Jorgano.setVisible(false);
        CorganoJur.setVisible(false);
        Jentidad.setVisible(false);
        Centidad.setVisible(false);
        LEntidad.setVisible(false);
        LProgress.setVisible(false);
        jProgressBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        JOEstatal = new javax.swing.JRadioButton();
        JOFederal = new javax.swing.JRadioButton();
        R1 = new javax.swing.JRadioButton();
        R2 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LEntidad2 = new javax.swing.JLabel();
        Rclave_entidad = new javax.swing.JRadioButton();
        Rclave_organo = new javax.swing.JRadioButton();
        Jentidad = new javax.swing.JLabel();
        Centidad = new javax.swing.JComboBox();
        Jorgano = new javax.swing.JLabel();
        CorganoJur = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Textoperiodo1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        LEntidad = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        LProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Limpiar BD");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione BD"));

        JOEstatal.setBackground(new java.awt.Color(255, 255, 255));
        JOEstatal.setText("Estatal");
        JOEstatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOEstatalActionPerformed(evt);
            }
        });

        JOFederal.setBackground(new java.awt.Color(255, 255, 255));
        JOFederal.setText("Federal");
        JOFederal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOFederalActionPerformed(evt);
            }
        });

        buttonGroup1.add(R1);
        R1.setText("VERSION 1.0");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(R2);
        R2.setText("VERSION 2.0");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(R3);
        R3.setText("VERSION 3.0");
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JOEstatal)
                    .addComponent(JOFederal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(R1)
                .addGap(18, 18, 18)
                .addComponent(R2)
                .addGap(18, 18, 18)
                .addComponent(R3)
                .addGap(104, 104, 104))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(JOEstatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JOFederal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1)
                    .addComponent(R2)
                    .addComponent(R3))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        LEntidad2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LEntidad2.setText("Entidad:");

        Rclave_entidad.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rclave_entidad);
        Rclave_entidad.setText("Clave Entidad");
        Rclave_entidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rclave_entidadActionPerformed(evt);
            }
        });

        Rclave_organo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rclave_organo);
        Rclave_organo.setText("Clave Organo");
        Rclave_organo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rclave_organoActionPerformed(evt);
            }
        });

        Jentidad.setText("Entidad:");

        Centidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CentidadItemStateChanged(evt);
            }
        });
        Centidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CentidadActionPerformed(evt);
            }
        });

        Jorgano.setText("Organo Jurisdiccional:");

        CorganoJur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CorganoJurItemStateChanged(evt);
            }
        });
        CorganoJur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorganoJurActionPerformed(evt);
            }
        });

        jLabel4.setText("Periodo:");

        Textoperiodo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Textoperiodo1KeyReleased(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/consultar.png"))); // NOI18N
        jButton2.setToolTipText("Seleccione para despliegue de periodos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LEntidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jButton1.setText("Limpiar BD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LProgress.setText("Procesando..........");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(210, 210, 210)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Jorgano)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Jentidad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(Rclave_entidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Rclave_organo))
                                    .addGap(105, 105, 105)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LEntidad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LProgress))
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LEntidad2)
                    .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rclave_entidad)
                    .addComponent(Rclave_organo))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jentidad)
                    .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jorgano)
                    .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(LProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JOEstatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOEstatalActionPerformed
        // TODO add your handling code here:
        if(JOEstatal.isSelected()){
            R1.setVisible(true);
            R2.setVisible(true);
            R3.setVisible(true);
            BD="Estatal";
            Centidad.removeAllItems();
            CorganoJur.removeAllItems();
        }
    }//GEN-LAST:event_JOEstatalActionPerformed

    private void JOFederalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOFederalActionPerformed
        // TODO add your handling code here:
        if(JOFederal.isSelected()){
            BD="Federal";
            Centidad.removeAllItems();
            CorganoJur.removeAllItems();
        }
    }//GEN-LAST:event_JOFederalActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
        if(R1.isSelected()){
            Versiones="";
            Versiones="1.0";
          
        }
    }//GEN-LAST:event_R1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        if(R2.isSelected()){
            Versiones="";
            Versiones="2.0";
            
        }
    }//GEN-LAST:event_R2ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        if(R3.isSelected()){
            Versiones="";
            Versiones="3.0";
          jPanel1.setVisible(true);
            llenaCombo();
            llenaComboEntidad();
        }
    }//GEN-LAST:event_R3ActionPerformed

    private void Rclave_entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rclave_entidadActionPerformed
        // TODO add your handling code here:
        //evento valida si el radiobutton  entidad se selecciona muestra LEntidad,LEntidad2,Jentidad,Centidad en jframe PValidacion.
        if (Rclave_entidad.isSelected())
        {
            Valores();
            NEntidad();
            LEntidad.setVisible(true);
            LEntidad2.setVisible(true);
            Jorgano.setVisible(false);
            CorganoJur.setVisible(false);
            Jentidad.setVisible(true);
            Centidad.setVisible(true);
        }
    }//GEN-LAST:event_Rclave_entidadActionPerformed

    private void Rclave_organoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rclave_organoActionPerformed
        // TODO add your handling code here:
        //evento valida si el radiobutton  clave de organo se selecciona muestra LEntidad,LEntidad2,Jorgano,CorganoJur en jframe PValidacion.
        if(Rclave_organo.isSelected())
        {
            Valores();
            NEntidad_COrgano();
            LEntidad.setVisible(true);
            LEntidad2.setVisible(true);
            Jentidad.setVisible(false);
            Centidad.setVisible(false);
            Jorgano.setVisible(true);
            CorganoJur.setVisible(true);
        }
    }//GEN-LAST:event_Rclave_organoActionPerformed

    private void CentidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CentidadItemStateChanged
        // TODO add your handling code here:
        NEntidad();
    }//GEN-LAST:event_CentidadItemStateChanged

    private void CentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CentidadActionPerformed
        // TODO add your handling code here:
        /* if (Centidad.getSelectedItem().toString().equals("04"))
        {

        }else{

        }*/

        Valores();
    }//GEN-LAST:event_CentidadActionPerformed

    private void CorganoJurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CorganoJurItemStateChanged
        // TODO add your handling code here:
        NEntidad_COrgano();
    }//GEN-LAST:event_CorganoJurItemStateChanged

    private void CorganoJurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorganoJurActionPerformed
        // TODO add your handling code here:

        /* if (CorganoJur.getSelectedItem().toString().substring(0, 2).equals("04"))
        {

        }else{

        }*/
        Valores();
    }//GEN-LAST:event_CorganoJurActionPerformed

    private void Textoperiodo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Textoperiodo1KeyReleased
        // TODO add your handling code here:
        Valores();
    }//GEN-LAST:event_Textoperiodo1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Valores();
        PConPer per = new PConPer();
        per.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    
     public void LimpiaBD() throws SQLException{  
     CallableStatement st=null;
    Connection con = null;
    con = OracleDAOFactory.creaConexion();       
     LProgress.setVisible(true);
     jProgressBar1.setVisible(true);    
     String[] ArrayTablas = new String[42];
     V3Querys V3Q=new V3Querys();
     int Progress=3;
    ArrayTablas[0]="V3_TR_AUDIENCIASJL";
    ArrayTablas[1]="V3_TR_ORDINARIOJL";
    ArrayTablas[2]="V3_TR_PART_ACT_ORDINARIOJL";
    ArrayTablas[3]="V3_TR_PART_DEM_ORDINARIOJL";
    ArrayTablas[4]="V3_TR_INDIVIDUALJL";
    ArrayTablas[5]="V3_TR_PART_ACT_INDIVIDUALJL";
    ArrayTablas[6]="V3_TR_PART_DEM_INDIVIDUALJL";
    ArrayTablas[7]="V3_TR_COLECTIVOJL";
    ArrayTablas[8]="V3_TR_PART_ACT_COLECTIVOJL";
    ArrayTablas[9]="V3_TR_PART_DEM_COLECTIVOJL";
    ArrayTablas[10]="V3_TR_HUELGAJL";
    ArrayTablas[11]="V3_TR_PART_ACT_HUELGAJL";
    ArrayTablas[12]="V3_TR_PART_DEM_HUELGAJL";
    ArrayTablas[13]="V3_TR_COLECT_ECONOMJL";
    ArrayTablas[14]="V3_TR_PART_ACT_COLECT_ECONOMJL";
    ArrayTablas[15]="V3_TR_PART_DEM_COLECT_ECONOMJL";
    ArrayTablas[16]="V3_TR_PARAPROCESALJL";
    ArrayTablas[17]="V3_TR_PREF_CREDITOJL";
    ArrayTablas[18]="V3_TR_TERCERIASJL";
    ArrayTablas[19]="V3_TR_EJECUCIONJL";   
    ArrayTablas[20]="V3_TR_CONTROL_EXPEDIENTEJL";   
    ArrayTablas[21]="V3_TMP_AUDIENCIASJL";
    ArrayTablas[22]="V3_TMP_ORDINARIOJL";
    ArrayTablas[23]="V3_TMP_PART_ACT_ORDINARIOJL";
    ArrayTablas[24]="V3_TMP_PART_DEM_ORDINARIOJL";
    ArrayTablas[25]="V3_TMP_INDIVIDUALJL";
    ArrayTablas[26]="V3_TMP_PART_ACT_INDIVIDUALJL";
    ArrayTablas[27]="V3_TMP_PART_DEM_INDIVIDUALJL";
    ArrayTablas[28]="V3_TMP_COLECTIVOJL";
    ArrayTablas[29]="V3_TMP_PART_ACT_COLECTIVOJL";
    ArrayTablas[30]="V3_TMP_PART_DEM_COLECTIVOJL";
    ArrayTablas[31]="V3_TMP_HUELGAJL";
    ArrayTablas[32]="V3_TMP_PART_ACT_HUELGAJL";
    ArrayTablas[33]="V3_TMP_PART_DEM_HUELGAJL";
    ArrayTablas[34]="V3_TMP_COLECT_ECONOMJL";
    ArrayTablas[35]="V3_TMP_PART_ACT_COLECT_ECONOMJL";
    ArrayTablas[36]="V3_TMP_PART_DEM_COLECT_ECONOMJL";
    ArrayTablas[37]="V3_TMP_PARAPROCESALJL";
    ArrayTablas[38]="V3_TMP_PREF_CREDITOJL";
    ArrayTablas[39]="V3_TMP_TERCERIASJL";
    ArrayTablas[40]="V3_TMP_EJECUCIONJL";   
    ArrayTablas[41]="V3_TMP_CONTROL_EXPEDIENTEJL";   
    
    try {
        st = con.prepareCall("{call RESPALDOV3_XENTIDAD(?, ?, ?)}");
        st.setString(1, clave_organo);
        st.setString(2, clave_entidad);
        st.setString(3, periodo);
        st.execute();
     } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e + "Favor de contactar al administrador");
        } finally {
            try {
                if (con != null) {
                    System.out.println("cierraaa");
                    con.close();
                    con = null;
                }
            } catch (SQLException ex) {
                throw new SQLException("[actualiza]: " + ex.getLocalizedMessage());
            }
    }
            
    for (int i=0;i<=41;i++)
    {
        V3Q.CleanerBD(ArrayTablas[i],clave_entidad,clave_organo,periodo);
        Progress=Progress+3;
        jProgressBar1.setValue(Progress);
        
    }
    JOptionPane.showMessageDialog(null, "Los Registros se han Eliminado correctamente");
   jProgressBar1.setValue(0);
   jProgressBar1.setVisible(false);
    LProgress.setVisible(false);
    
     
 }   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        new Thread(() -> {
            Valores();
             int resp=0;
            if(!clave_organo.equals("")){
             resp = JOptionPane.showConfirmDialog(null, "¿Desea Eliminar la información con clave_organo="+clave_organo+" \n"+" Periodo_Actual="+periodo+"", "Alerta!", JOptionPane.YES_NO_OPTION); 
            }  
            if(!clave_entidad.equals("")){
             resp = JOptionPane.showConfirmDialog(null, "¿Desea Eliminar la información con clave_entidad="+clave_entidad+" \n"+" Periodo_Actual="+periodo+"", "Alerta!", JOptionPane.YES_NO_OPTION); 
            }  
             if (resp == JOptionPane.YES_OPTION) {  
                
                try {
                    LimpiaBD();
                } catch (SQLException ex) {
                    Logger.getLogger(PCleaner.class.getName()).log(Level.SEVERE, null, ex);
                }
                
             }
                
         //   try {
            
               
          //  } catch (IOException ex) {
          //      Logger.getLogger(PInsertTMP.class.getName()).log(Level.SEVERE, null, ex);
           // }
        }).start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        PMenu menu= new PMenu();
        menu.setVisible(true);
        clave_organo="";
        clave_entidad="";
        
    }//GEN-LAST:event_formWindowClosing

    
    
   public void llenaComboEntidad(){
         
        if (Versiones.equals("1.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=query.Entidad();    
        }
        if (Versiones.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=queryNE.EntidadNE();    
        }
        if (Versiones.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=V3queryNE.EntidadNE();    
        }
         if (Versiones.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayClave_entidad=V1FedQuerys.EntidadNE();    
        }
        
         Centidad.removeAllItems();
         for (int i=0;i<ArrayClave_entidad.size();i++){
          String Organo=(Arrays.toString(ArrayClave_entidad.get(i)));
          Centidad.addItem(Organo.replace("[","").replace("]",""));
        }
    }
    
    public void llenaCombo(){
         
        if (Versiones.equals("1.0") && (BD.equals("Estatal")) )
        {
        ArrayClave_organo=query.Clave_organo();    
        }
        if (Versiones.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=queryNE.Clave_organoNE();    
        }
         if (Versiones.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=V3queryNE.Clave_organoNE();    
        }
        if (Versiones.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayClave_organo=V1FedQuerys.Clave_organoNE();    
        } 
         CorganoJur.removeAllItems();
         for (int i=0;i<ArrayClave_organo.size();i++){
          String Organo=(Arrays.toString(ArrayClave_organo.get(i)));
          CorganoJur.addItem(Organo.replace("[","").replace("]",""));
        }
    }
    
     
     public void NEntidad(){
      if (Centidad.getItemCount()>0)
    {  
        switch(Centidad.getSelectedItem().toString()){
            case "01":
             LEntidad.setText("Aguascalientes");
                break;
            case "02":
             LEntidad.setText("Baja California");
                break;
            case "03":
                LEntidad.setText("Baja California Sur");
                break;
            case "04":
                LEntidad.setText("Campeche");
                break;
            case "05":
                LEntidad.setText("Coahuila de Zaragoza");
                break;
            case "06":
                LEntidad.setText("Colima");
                break;
            case "07":
                LEntidad.setText("Chiapas");
                break;
            case "08":
                LEntidad.setText("Chihuahua");
                break;
            case "09":
                LEntidad.setText("Ciudad de México");
                break;
            case "10":
                LEntidad.setText("Durango");
                break;
            case "11":
                LEntidad.setText("Guanajuato");
                break;
            case "12":
                LEntidad.setText("Guerrero");
                break;
            case "13":
                LEntidad.setText("Hidalgo");
                break;
            case "14":
                LEntidad.setText("Jalisco");
                break;
            case "15":
                LEntidad.setText("México");
                break;
            case "16":
                LEntidad.setText("Michoacán de Ocampo");
                break;
            case "17":
                LEntidad.setText("Morelos");
                break;
            case "18":
                LEntidad.setText("Nayarit");
                break;
            case "19":
                LEntidad.setText("Nuevo León");
                break;
            case "20":
                LEntidad.setText("Oaxaca");
                break;
            case "21":
                LEntidad.setText("Puebla");
                break;
            case "22":
                LEntidad.setText("Querétaro");
                break;
            case "23":
                LEntidad.setText("Quintana Roo");
                break;
            case "24":
                LEntidad.setText("San Luis Potosí");
                break;
            case "25":
                LEntidad.setText("Sinaloa");
                break;
            case "26":
                LEntidad.setText("Sonora");
                break;
            case "27":
                LEntidad.setText("Tabasco");
                break;
            case "28":
                LEntidad.setText("Tamaulipas");
                break;
            case "29":
                LEntidad.setText("Tlaxcala");
                break;
            case "30":
                LEntidad.setText("Veracruz de Ignacio de la Llave");
                break;
            case "31":
                LEntidad.setText("Yucatán");
                break;
            case "32":
                LEntidad.setText("Zacatecas");
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se Encontro Entidad", "Valida", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "Favor de contactar al Administrador", "Valida", JOptionPane.WARNING_MESSAGE);
        }
        
    }
    }
     
     
     public void NEntidad_COrgano(){  
      
    if (CorganoJur.getItemCount()>0)
    {
        System.out.println(CorganoJur.getSelectedItem().toString().substring(0, 2));
        switch(CorganoJur.getSelectedItem().toString().substring(0, 2)){
            case "01":
             LEntidad.setText("Aguascalientes");
                break;
            case "02":
             LEntidad.setText("Baja California");
                break;
            case "03":
                LEntidad.setText("Baja California Sur");
                break;
            case "04":
                LEntidad.setText("Campeche");
                break;
            case "05":
                LEntidad.setText("Coahuila de Zaragoza");
                break;
            case "06":
                LEntidad.setText("Colima");
                break;
            case "07":
                LEntidad.setText("Chiapas");
                break;
            case "08":
                LEntidad.setText("Chihuahua");
                break;
            case "09":
                LEntidad.setText("Ciudad de México");
                break;
            case "10":
                LEntidad.setText("Durango");
                break;
            case "11":
                LEntidad.setText("Guanajuato");
                break;
            case "12":
                LEntidad.setText("Guerrero");
                break;
            case "13":
                LEntidad.setText("Hidalgo");
                break;
            case "14":
                LEntidad.setText("Jalisco");
                break;
            case "15":
                LEntidad.setText("México");
                break;
            case "16":
                LEntidad.setText("Michoacán de Ocampo");
                break;
            case "17":
                LEntidad.setText("Morelos");
                break;
            case "18":
                LEntidad.setText("Nayarit");
                break;
            case "19":
                LEntidad.setText("Nuevo León");
                break;
            case "20":
                LEntidad.setText("Oaxaca");
                break;
            case "21":
                LEntidad.setText("Puebla");
                break;
            case "22":
                LEntidad.setText("Querétaro");
                break;
            case "23":
                LEntidad.setText("Quintana Roo");
                break;
            case "24":
                LEntidad.setText("San Luis Potosí");
                break;
            case "25":
                LEntidad.setText("Sinaloa");
                break;
            case "26":
                LEntidad.setText("Sonora");
                break;
            case "27":
                LEntidad.setText("Tabasco");
                break;
            case "28":
                LEntidad.setText("Tamaulipas");
                break;
            case "29":
                LEntidad.setText("Tlaxcala");
                break;
            case "30":
                LEntidad.setText("Veracruz de Ignacio de la Llave");
                break;
            case "31":
                LEntidad.setText("Yucatán");
                break;
            case "32":
                LEntidad.setText("Zacatecas");
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se Encontro Entidad", "Valida", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "Favor de contactar al Administrador", "Valida", JOptionPane.WARNING_MESSAGE);
        }
    }
        
    }
     
     
     public  void Valores(){
        if(Rclave_organo.isSelected())
        {
            clave_entidad="";
            clave_organo="";
            clave_organo=CorganoJur.getSelectedItem().toString();
            periodo=Textoperiodo1.getText();
            NMunicipio=LEntidad.getText();
            NENTIDAD=LEntidad.getText();
            System.out.println("valoreeeees"+clave_organo+" "+clave_entidad+" "+periodo+" "+tabla);
          
        }
        else if (Rclave_entidad.isSelected()){
            clave_entidad="";
            clave_organo="";
            clave_entidad=Centidad.getSelectedItem().toString();
            periodo=Textoperiodo1.getText();
            NMunicipio=LEntidad.getText();
            NENTIDAD=LEntidad.getText();
            System.out.println("valoreeeees"+clave_organo+" "+clave_entidad+" "+periodo+" "+tabla);
           
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PCleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PCleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PCleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PCleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PCleaner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Centidad;
    private javax.swing.JComboBox CorganoJur;
    private javax.swing.JRadioButton JOEstatal;
    private javax.swing.JRadioButton JOFederal;
    private javax.swing.JLabel Jentidad;
    private javax.swing.JLabel Jorgano;
    private javax.swing.JLabel LEntidad;
    private javax.swing.JLabel LEntidad2;
    private javax.swing.JLabel LProgress;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JRadioButton Rclave_entidad;
    private javax.swing.JRadioButton Rclave_organo;
    public javax.swing.JTextField Textoperiodo1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
