/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import mx.org.querys.NotNull_Estruc_Definitiva.EDQueryGenerales;
import mx.org.querys.V1querys;
import mx.org.querys.V2querysNE;
import mx.org.querys.V3Querys;
import mx.org.querys.federal.FedV1Querys;

/**
 *
 * @author ANTONIO.CORIA
 */
public class PConPer extends javax.swing.JFrame {

    /**
     * Creates new form ConPeriodo
     */
    
     ArrayList<String[]> ArrayPeriodo;
    V1querys query=new V1querys();
    V2querysNE queryNE=new V2querysNE();
    V3Querys V3queryNE=new V3Querys();
    EDQueryGenerales EDQuerys = new EDQueryGenerales();
    FedV1Querys FedV1Querys= new FedV1Querys();
    PValidacion validacion= new PValidacion ();
    PInsertTMP tmp=new PInsertTMP();
    PInsertTR tr=new PInsertTR();
    PAcumula PAcum= new PAcumula();
    PCleaner clean=new PCleaner(); 
    Errores_InsertTMP errores=new Errores_InsertTMP();
    public static String periodo="";
    String entidad,claveorgano;
     
    
    public PConPer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tperiodo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Tperiodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Periodo"
            }
        ));
        Tperiodo.setColumnSelectionAllowed(true);
        Tperiodo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tperiodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TperiodoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TperiodoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tperiodo);
        Tperiodo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
 //evento para asignar a JTABLE los periodos existentes segun su clave de organo o clave de entidad
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code h89ere:


if((validacion.version.equals("1.0") && (validacion.BD.equals("Estatal"))) || (tmp.Versiones.equals("V1")) || (tr.Versiones.equals("1.0")) )
{
ArrayPeriodo=query.Periodo();
}
if((validacion.version.equals("2.0") && (validacion.BD.equals("Estatal"))) || (tmp.Versiones.equals("V2")) || (tr.Versiones.equals("2.0")))
{
ArrayPeriodo=queryNE.PeriodoNE();
}
if((validacion.version.equals("3.0") && (validacion.BD.equals("Estatal"))) || (tmp.Versiones.equals("V3")) || (tr.Versiones.equals("3.0")) || (PAcum.Versiones.equals("3.0")) || (clean.Versiones.equals("3.0")) )
{    
ArrayPeriodo=V3queryNE.PeriodoNE(errores.claveorgano+validacion.clave_organo+tr.clave_organo+PAcum.clave_organo+clean.clave_organo,errores.entidad+validacion.clave_entidad+tr.clave_entidad+PAcum.clave_entidad+clean.clave_entidad);
}
if((validacion.version.equals("1.0") && (validacion.BD.equals("Federal"))) || (tmp.Versiones.equals("V1")))
{
ArrayPeriodo=FedV1Querys.PeriodoNE();
}
if((validacion.version.equals("Estructura_Definitiva") && (validacion.BD.equals("Estatal"))) )
{    
ArrayPeriodo=EDQuerys.PeriodoNE(validacion.clave_organo,validacion.clave_entidad);
}
/*
if((validacion.version.equals("Estructura_Definitiva") && (validacion.BD.equals("Estatal"))) || (tmp.Versiones.equals("V3")) || (tr.Versiones.equals("3.0")) || (PAcum.Versiones.equals("3.0")) || (clean.Versiones.equals("3.0")) )
{    
ArrayPeriodo=V3queryNE.PeriodoNE(errores.claveorgano+validacion.clave_organo+tr.clave_organo+PAcum.clave_organo+clean.clave_organo,errores.entidad+validacion.clave_entidad+tr.clave_entidad+PAcum.clave_entidad+clean.clave_entidad);
}
*/
DefaultTableModel TablaPeriodo = (DefaultTableModel) Tperiodo.getModel();     
Object[] fila = new Object[ArrayPeriodo.size()];      
for(int j=0; j<ArrayPeriodo.size(); j++){
String Periodo=Arrays.toString(ArrayPeriodo.get(j));
fila[0]=Periodo.replace("[", "").replace("]", "");
TablaPeriodo.addRow(fila);
Class<?> col_class = Tperiodo.getColumnClass(0);
Tperiodo.setDefaultEditor(col_class, null); 
}  

    }//GEN-LAST:event_formWindowOpened

   
    
    private void TperiodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TperiodoMouseClicked
        // TODO add your handling code here 
    }//GEN-LAST:event_TperiodoMouseClicked

    private void TperiodoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TperiodoMousePressed
        // TODO add your handling code here:
        
         int selectedRowIndex = Tperiodo.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel)Tperiodo.getModel();
         
         /* if ((evt.getClickCount()==2)){
              periodo=model.getValueAt(selectedRowIndex, 0).toString();
              System.out.println(periodo);
          }*/
          
    }//GEN-LAST:event_TperiodoMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PConPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PConPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PConPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PConPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PConPer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tperiodo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
