/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screen_laborales;

import LeerQuery.QueryErrorPostgreSQL;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDREA.HERNANDEZL
 */
public class PErroresInsertPostgreSQL extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PErroresInsertPostgreSQL.class.getName());
    String part0 = "", part1 = "", part2 = "", T_reg = "", T_regNI = "", texto = "";
    int TTRegNI = 0;
    String[] errorarray;
    ArrayList<Object[]> ArrayErroresInsInicio;
    QueryErrorPostgreSQL QPPostgreSQL = new QueryErrorPostgreSQL();

    /**
     * Creates new form PErroresInsertPostgreSQL
     */
    public PErroresInsertPostgreSQL() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(75);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID_TABLA", "TABLA", "OBSERVACIONES"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/actualizar.png"))); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(this::BtnActualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(BtnActualizar)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        new Thread(() -> {
            DespliegaErroresInicio();
        }).start();
    }//GEN-LAST:event_BtnActualizarActionPerformed
    public void limpiarTabla() {
        T_reg = "";
        T_regNI = "";
        TTRegNI = 0;
        texto = "";
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    public void TextAreaInicio() {
            System.out.println("Entidad: " + PMapeoProcesarPostgreSQL.clave_entidad);
    System.out.println("Periodo: " + PMapeoProcesarPostgreSQL.Periodo);
        int progres = 5;
        String[] ArrayTablas = {
            "TR_ACTOR",
            "TR_AUDIENCIA",
            "TR_DEMANDADO",
            "TR_ESPECIFIQUE",
            "TR_EXP_ACTOR",
            "TR_EXP_CIRCUNST",
            "TR_EXP_CONCEPTO_RECLAM",
            "TR_EXP_DEMANDADO",
            "TR_EXP_EFECTOS_SENTENCIA",
            "TR_EXP_MOTIVO_CONF",
            "TR_EXP_MOTIVO_HUELGA",
            "TR_EXP_MOTIVO_SOLIC",
            "TR_EXP_PRESTACION",
            "TR_EXP_SUSPENSION",
            "TR_EXP_TERMINACION",
            "TR_EXP_VIOLACION",
            "TR_EXPEDIENTE",
            "TR_GENERAL",
            "TR_ORGANOJ"
        };

        texto = "";
        TTRegNI = 0;

        for (String tabla : ArrayTablas) {
            T_reg = QPPostgreSQL.Total_Reg_insertadosTR(tabla, PMapeoProcesarPostgreSQL.clave_entidad, PMapeoProcesarPostgreSQL.Periodo);
            T_regNI = QPPostgreSQL.Total_Reg_NITR(tabla, PMapeoProcesarPostgreSQL.clave_entidad, PMapeoProcesarPostgreSQL.Periodo);
            TTRegNI += Integer.parseInt(T_regNI);
            texto += tabla + "\n\n"
                    + "   Reg_TR: " + T_reg
                    + "   Reg_NoIn: " + T_regNI
                    + "\n------------------------------------------\n";

            progres += 5;
        }
    }
    
    public void DespliegaErroresInicio() {
        limpiarTabla();
        TextAreaInicio();
        ArrayErroresInsInicio = QPPostgreSQL.TErroresInserTRInicio(PMapeoProcesarPostgreSQL.clave_entidad, PMapeoProcesarPostgreSQL.Periodo);

        if (TTRegNI > 0) {
            DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
            Object[] fila = new Object[3];
            for (int j = 0; j < ArrayErroresInsInicio.size(); j++) {
                String Periodo = Arrays.toString(ArrayErroresInsInicio.get(j)).replace("[", "").replace("]", "");
                errorarray = Periodo.split(",");

                part0 = errorarray[0].trim();
                part1 = errorarray[1].trim();
                part2 = errorarray[2].trim();

                fila[0] = part0;
                fila[1] = part1;
                fila[2] = part2;

                TablaError.addRow(fila);
            }
            Class<?> col_class = jTable1.getColumnClass(0);
            jTable1.setDefaultEditor(col_class, null);

        } else {
            limpiarTabla();
            JOptionPane.showMessageDialog(null, "No se encontraron registros con Error de insert", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PErroresInsertPostgreSQL().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
