/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screen_laborales;

import LeerQuery.QueryProcedureTR_Fed;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDREA.HERNANDEZL
 */
public class PErrores_InsertTR_Fed extends javax.swing.JFrame {

    ArrayList<String[]> ArrayErroresIns;
    QueryProcedureTR_Fed QPrefed = new QueryProcedureTR_Fed();
    String[] errorarray;
    String part0 = "", part1 = "", part2 = "", part3 = "", part4 = "";
    String T_reg = "", T_regTMP = "", texto = "";

    public static String Ttabla = "", Tclave_organo = "", Tclave_expediente = "", Tid = "";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PErrores_InsertTR_Fed.class.getName());

    /**
     * Creates new form Errores_InsertTR_Fed
     */
    public PErrores_InsertTR_Fed() {
        initComponents();
        jTextArea1.setVisible(false);
        this.setLocationRelativeTo(null);
        LProcesando.setVisible(false);
        PBarProcesando.setVisible(false);
        PBarProcesando.setMinimum(0);
        PBarProcesando.setMaximum(100);
        PBarProcesando.setValue(0);
        PBarProcesando.setStringPainted(true);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(75);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnActualizar = new javax.swing.JButton();
        LProcesando = new javax.swing.JLabel();
        PBarProcesando = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Errores de Insert ");
        jLabel1.setToolTipText("");

        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(this::BtnActualizarActionPerformed);

        LProcesando.setText("Procesando...");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TABLA", "CLAVE_ORGANO", "CLAVE_EXPEDIENTE", "ID", "EXCEPCION"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(PBarProcesando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LProcesando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LProcesando)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PBarProcesando, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnActualizar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            if (!PInsertTR.tabla.equals("0.0")) {
                DespliegaErroresFed();
            }
        }).start();
    }//GEN-LAST:event_BtnActualizarActionPerformed
    public void DespliegaErroresFed() {
        jTextArea1.setText("");
        jTextArea1.setVisible(true);

        LProcesando.setVisible(true);
        PBarProcesando.setVisible(true);

        PBarProcesando.setValue(0);
        
        limpiarTabla();
        mostrarResumenPorTabla();

        ArrayErroresIns = QPrefed.TAllErroresInserFed();
        if (ArrayErroresIns.size() > 0) {
            DefaultTableModel TablaError= (DefaultTableModel) jTable1.getModel();
            Object[] fila = new Object[5];
            
            for (int j = 0; j < ArrayErroresIns.size(); j++) {
                String Periodo = Arrays.toString(ArrayErroresIns.get(j)).replace("[", "").replace("]", "");

                errorarray = Periodo.split(",");

                part0 = errorarray[0].trim();
                part1 = errorarray[1].trim();
                part2 = errorarray[2].trim();
                part3 = errorarray[3].trim();
                part4 = errorarray[4].trim();

                fila[0] = part0;
                fila[1] = part1;
                fila[2] = part2;
                fila[3] = part3;
                fila[4] = part4;

                TablaError.addRow(fila);
            }
            jTable1.setDefaultEditor(Object.class, null);
        } else {
            JOptionPane.showMessageDialog(null,
                    "No se encontraron registros con Error de insert en TR",
                    "Mensaje",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
        PBarProcesando.setValue(0);
        LProcesando.setVisible(false);
        PBarProcesando.setVisible(false);
    }

    private void mostrarResumenPorTabla() {
        try {
            LProcesando.setVisible(true);
            PBarProcesando.setVisible(true);

            PBarProcesando.setMinimum(0);
            PBarProcesando.setMaximum(100);
            PBarProcesando.setValue(0);

            ArrayList<Integer> tmp = QPrefed.conteoTMP_Federal(PBarProcesando);
            ArrayList<Integer> tr = QPrefed.conteoTR_Federal(PBarProcesando);

            String[] nombresTMP = {
                "TMP_FED_AUDIENCIAS",
                "TMP_FED_COLECTIVO",
                "TMP_FED_COLECTIVO_ECONOMICO",
                "TMP_FED_CONTROL_EXPEDIENTE",
                "TMP_FED_EJECUCION",
                "TMP_FED_HUELGA",
                "TMP_FED_INDIVIDUAL",
                "TMP_FED_ORDINARIO",
                "TMP_FED_PARAPROCESAL",
                "TMP_FED_SEG_SOCIAL"
            };

            int[] indiceTRparaTMP = {0, 1, 2, 5, 6, 7, 9, 11, 13, 15};

            String[] nombresTR = {
                "TR_FED_AUDIENCIAS",
                "TR_FED_COLECTIVO",
                "TR_FED_COLECTIVO_ECONOMICO",
                "TR_FED_COLECTIVO_ECONOMICO_PREST_RECL",
                "TR_FED_COLECTIVO_PREST_RECL",
                "TR_FED_CONTROL_EXPEDIENTE",
                "TR_FED_EJECUCION",
                "TR_FED_HUELGA",
                "TR_FED_HUELGA_PREST_RECL",
                "TR_FED_INDIVIDUAL",
                "TR_FED_INDIVIDUAL_PREST_RECL",
                "TR_FED_ORDINARIO",
                "TR_FED_ORDINARIO_PREST_RECL",
                "TR_FED_PARAPROCESAL",
                "TR_FED_PARAPROCESAL_PREST_RECL",
                "TR_FED_SEG_SOCIAL",
                "TR_FED_SEG_SOCIAL_PREST_RECL"
            };
            texto = "";

            for (int i = 0; i < nombresTMP.length; i++) {
                int totalTMP = tmp.get(i);
                int totalTR = tr.get(indiceTRparaTMP[i]);
                int noInsertados = totalTMP - totalTR;

                texto += nombresTMP[i]
                        + " -> "
                        + nombresTR[indiceTRparaTMP[i]]
                        + ": \n\n"
                        + "Reg_TMP:" + totalTMP
                        + "   Reg_TR:" + totalTR
                        + "   Reg_NoIn:" + noInsertados
                        + "\n"
                        + "-----------------------------------------------------------------\n";
            }
            int[] indicesPrestRecl = {3, 4, 8, 10, 12, 14, 16};

            for (int idx : indicesPrestRecl) {
                texto += nombresTR[idx]
                        + " (desglose): \n\n"
                        + "Reg_TR:" + tr.get(idx)
                        + "\n"
                        + "-----------------------------------------------------------------\n";
            }

            jTextArea1.setText(texto);
            PBarProcesando.setValue(100);
            LProcesando.setVisible(false);
            PBarProcesando.setVisible(false);

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, null, e);
            e.printStackTrace();

            LProcesando.setVisible(false);
            PBarProcesando.setVisible(false);
        }
    }

    public void limpiarTabla() {
        texto = "";
        DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
        while (TablaError.getRowCount() > 0) {
            TablaError.removeRow(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PErrores_InsertTR_Fed().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JLabel LProcesando;
    private javax.swing.JProgressBar PBarProcesando;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
