/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screen_laborales;

import LeerQuery.QueryProcedureActToV3;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDREA.HERNANDEZL
 */
public class PErroresInsertActToV3 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PErroresInsertActToV3.class.getName());
    String part0 = "", part1 = "", part2 = "", T_reg = "", T_regNI = "", texto = "";
    int TTRegNI = 0;
    String[] errorarray;
    ArrayList<Object[]> ArrayErroresInsInicio;
    QueryProcedureActToV3 QPActToV3 = new QueryProcedureActToV3();

    /**
     * Creates new form PErroresInsertActToV3
     */
    public PErroresInsertActToV3() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(75);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID_TABLA", "TABLA", "DESCRIPCION"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/actualizar.png"))); // NOI18N
        BtnActualizar.setText("    Actualizar");
        BtnActualizar.addActionListener(this::BtnActualizarActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnActualizar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(BtnActualizar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed

        new Thread(() -> {
            DespliegaErroresInicio();
        }).start();
    }//GEN-LAST:event_BtnActualizarActionPerformed

    public void limpiarTabla() {
        T_reg = "";
        T_regNI = "";
        TTRegNI = 0;
        texto = "";
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    public void TextAreaInicio() {
        int progres = 5;
        String[] ArrayTablas = {
            "V3_TR_CONTROL_EXPEDIENTEJL",
            "V3_TR_AUDIENCIASJL",
            "V3_TR_ORDINARIOJL",
            "V3_TR_PART_ACT_ORDINARIOJL",
            "V3_TR_PART_DEM_ORDINARIOJL",
            "V3_TR_INDIVIDUALJL",
            "V3_TR_PART_ACT_INDIVIDUALJL",
            "V3_TR_PART_DEM_INDIVIDUALJL",
            "V3_TR_COLECTIVOJL",
            "V3_TR_PART_ACT_COLECTIVOJL",
            "V3_TR_PART_DEM_COLECTIVOJL",
            "V3_TR_HUELGAJL",
            "V3_TR_PART_ACT_HUELGAJL",
            "V3_TR_PART_DEM_HUELGAJL",
            "V3_TR_COLECT_ECONOMJL",
            "V3_TR_PART_ACT_COLECT_ECONOMJL",
            "V3_TR_PART_DEM_COLECT_ECONOMJL",
            "V3_TR_PARAPROCESALJL",
            "V3_TR_PREF_CREDITOJL",
            "V3_TR_TERCERIASJL",
            "V3_TR_EJECUCIONJL"
        };

        texto = "";
        TTRegNI = 0;

        for (String tabla : ArrayTablas) {
            T_reg = QPActToV3.Total_Reg_insertadosTR(tabla, PMapeoProcesarActToV3.Cve_Entidad, PMapeoProcesarActToV3.Cve_ClaveOrgano, PMapeoProcesarActToV3.Periodo);
            T_regNI = QPActToV3.Total_Reg_NITR(tabla, PMapeoProcesarActToV3.Cve_Entidad, PMapeoProcesarActToV3.Cve_ClaveOrgano, PMapeoProcesarActToV3.Periodo);
            TTRegNI += Integer.parseInt(T_regNI);
            texto += tabla + "\n\n"
                    + "   Reg_TR: " + T_reg
                    + "   Reg_NoIn: " + T_regNI
                    + "\n------------------------------------------\n";

            progres += 5;
        }
    }

    public void DespliegaErroresInicio() {
        limpiarTabla();
        TextAreaInicio();
        ArrayErroresInsInicio = QPActToV3.TErroresInserTRInicio(PMapeoProcesarActToV3.Cve_ClaveOrgano, PMapeoProcesarActToV3.Cve_Entidad, PMapeoProcesarActToV3.Periodo);

        if (TTRegNI > 0) {
            DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
            Object[] fila = new Object[3];
            for (int j = 0; j < ArrayErroresInsInicio.size(); j++) {
                String Periodo = Arrays.toString(ArrayErroresInsInicio.get(j)).replace("[", "").replace("]", "");
                errorarray = Periodo.split(",");

                part0 = errorarray[0].trim();
                part1 = errorarray[1].trim();
                part2 = errorarray[2].trim();

                fila[0] = part0;
                fila[1] = part1;
                fila[2] = part2;

                TablaError.addRow(fila);
            }
            Class<?> col_class = jTable1.getColumnClass(0);
            jTable1.setDefaultEditor(col_class, null);

        } else {
            limpiarTabla();
            JOptionPane.showMessageDialog(null, "No se encontraron registros con Error de insert", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PErroresInsertActToV3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
