/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import static Screen_laborales.PValidacion.BD;
import static Screen_laborales.PValidacion.version;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import mx.org.querys.NotNull_Estruc_Definitiva.EDQueryGenerales;
import mx.org.querys.V1querys;
import mx.org.querys.V2querysNE;
import mx.org.querys.V3Querys;
import mx.org.querys.federal.FedV1Querys;
import mx.org.querys.QEstatus;

/**
 *
 * @author ANTONIO.CORIA
 */
public class PEstatus extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Estatus
     */
    public static String version="",BD="",Entidad="",Clave_organo="",Periodo="",Tid_control="",Tclave_organo="",Tsede="",Tentidad_clave="",Tentidad_nombre="",Tmunicipio_clave="",Tmunicipio_nombre="",Tperiodo="",Testatus="";
     
    ArrayList<String[]> ArrayClave_organo,ArrayClave_entidad,ArrayPeriodo,ArrayTablaEstatus;
    V1querys query=new V1querys();//Intanciar clase V1querys con nombre query
    V2querysNE queryNE=new V2querysNE();//Intanciar clase V2querysNE con nombre queryNE
    V3Querys V3queryNE=new V3Querys();//Intanciar clase V3querys con nombre V3queryNE
    QEstatus Est= new QEstatus();
    FedV1Querys V1FedQuerys=new FedV1Querys();
    EDQueryGenerales EDQuerys = new EDQueryGenerales();
    
    public PEstatus() {
        initComponents();
        this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
       PanelDatos.setVisible(false);
       Pversiones.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Pversiones = new javax.swing.JPanel();
        Rver1 = new javax.swing.JRadioButton();
        Rver2 = new javax.swing.JRadioButton();
        Rver3 = new javax.swing.JRadioButton();
        Rver4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        PanelDatos = new javax.swing.JPanel();
        Jentidad = new javax.swing.JLabel();
        Centidad = new javax.swing.JComboBox();
        Jorgano = new javax.swing.JLabel();
        Corgano = new javax.swing.JComboBox();
        Jperiodo = new javax.swing.JLabel();
        Cperiodo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaE = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        total_organos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JOEstatal = new javax.swing.JRadioButton();
        JOFederal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estatus");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Pversiones.setBackground(new java.awt.Color(255, 255, 255));
        Pversiones.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione Version de BD"));

        Rver1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rver1);
        Rver1.setText("Estructura Ver. 1.0");
        Rver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rver1ActionPerformed(evt);
            }
        });

        Rver2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rver2);
        Rver2.setText("Estructura Ver. 2.0");
        Rver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rver2ActionPerformed(evt);
            }
        });

        Rver3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rver3);
        Rver3.setText("Estructura Ver. 3.0");
        Rver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rver3ActionPerformed(evt);
            }
        });

        Rver4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rver4);
        Rver4.setText("Estructura Definitiva");
        Rver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rver4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PversionesLayout = new javax.swing.GroupLayout(Pversiones);
        Pversiones.setLayout(PversionesLayout);
        PversionesLayout.setHorizontalGroup(
            PversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PversionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Rver1)
                .addGap(18, 18, 18)
                .addComponent(Rver2)
                .addGap(18, 18, 18)
                .addComponent(Rver3)
                .addGap(18, 18, 18)
                .addComponent(Rver4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PversionesLayout.setVerticalGroup(
            PversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PversionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rver1)
                    .addComponent(Rver2)
                    .addComponent(Rver3)
                    .addComponent(Rver4))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        PanelDatos.setBackground(new java.awt.Color(255, 255, 255));

        Jentidad.setText("Entidad:");

        Centidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CentidadItemStateChanged(evt);
            }
        });
        Centidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CentidadMouseClicked(evt);
            }
        });
        Centidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CentidadActionPerformed(evt);
            }
        });

        Jorgano.setText("Organo Jurisdiccional:");

        Corgano.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CorganoItemStateChanged(evt);
            }
        });
        Corgano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorganoActionPerformed(evt);
            }
        });

        Jperiodo.setText("Periodo");

        Cperiodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CperiodoItemStateChanged(evt);
            }
        });
        Cperiodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CperiodoActionPerformed(evt);
            }
        });

        TablaE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_CONTROL", "CLAVE_ORGANO", "SEDE", "E_CLAVE", "E_NOMBRE", "M_CLAVE", "M_NOMBRE", "PERIODO", "ESTATUS"
            }
        ));
        TablaE.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        TablaE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaEMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TablaE);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/consultar.png"))); // NOI18N
        jButton2.setToolTipText("Seleccione para despliegue de periodos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Organos:");

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Jentidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Jorgano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Corgano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(Jperiodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_organos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total_organos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jentidad)
                            .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jorgano)
                            .addComponent(Corgano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jperiodo)
                            .addComponent(Cperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione BD"));

        JOEstatal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(JOEstatal);
        JOEstatal.setText("Estatal");
        JOEstatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOEstatalActionPerformed(evt);
            }
        });

        JOFederal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(JOFederal);
        JOFederal.setText("Federal");
        JOFederal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOFederalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(JOEstatal)
                .addGap(18, 18, 18)
                .addComponent(JOFederal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JOEstatal)
                    .addComponent(JOFederal))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pversiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pversiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void MuestraPanel(){
      PanelDatos.setVisible(true);
    }
    
   public void limpiartabla(){
    DefaultTableModel temp = (DefaultTableModel) TablaE.getModel();
    int filas = TablaE.getRowCount();

    for (int a = 0; filas > a; a++) {
        temp.removeRow(0);
    }
}
    
    private void Rver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rver1ActionPerformed
          if(Rver1.isSelected()){ 
           MuestraPanel();
           limpiartabla();
           version="";
           version="1.0";
           llenaComboEntidad();
           
          }
    }//GEN-LAST:event_Rver1ActionPerformed

    private void Rver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rver2ActionPerformed
        if(Rver2.isSelected()){  
        MuestraPanel();
       limpiartabla();
        version="";   
        version="2.0";
        llenaComboEntidad();
        
        }
    }//GEN-LAST:event_Rver2ActionPerformed

    private void Rver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rver3ActionPerformed
        if(Rver3.isSelected()){  
        MuestraPanel();
        limpiartabla();
        version="";     
        version="3.0";
        llenaComboEntidad();
       
        }
    }//GEN-LAST:event_Rver3ActionPerformed

     public void llenaComboClaveOrgano(){
         System.out.println(version+BD);
         Clave_organo="";    
         if (version.equals("1.0") && (BD.equals("Estatal")) )
        {
        ArrayClave_organo=query.Clave_organoEstatus(); 
            System.out.println("entro a v1 estatal");
        }
        if (version.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=queryNE.Clave_organoNEstatus();    
        System.out.println("entro a v2 estatal");
        }
         if (version.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=V3queryNE.Clave_organoNEstatus();    
        }
         if (version.equals("Estructura_Definita") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=EDQuerys.Clave_organoNEstatus();    
        }
        if (version.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayClave_organo=V1FedQuerys.Clave_organoNEstatus();    
        } 
        Corgano.removeAllItems();
         for (int i=0;i<ArrayClave_organo.size();i++){
          String Organo=(Arrays.toString(ArrayClave_organo.get(i)));
          Corgano.addItem(Organo.replace("[","").replace("]",""));
        }
         
        
         Clave_organo=Corgano.getSelectedItem().toString();
         System.out.println("claveeee organo"+Clave_organo);
         
         
    }
    
     
      public void llenaComboEntidad(){
         
          Entidad=""; 
        if (version.equals("1.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=query.Entidad();    
        }
        if (version.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=queryNE.EntidadNE();    
        }
        if (version.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=V3queryNE.EntidadNE();    
        }
         if (version.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayClave_entidad=V1FedQuerys.EntidadNE();    
        }
         if (version.equals("Estructura_Definita") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=EDQuerys.EntidadNE();    
        }
        
         Centidad.removeAllItems();
         for (int i=0;i<ArrayClave_entidad.size();i++){
          String Organo=(Arrays.toString(ArrayClave_entidad.get(i)));
          Centidad.addItem(Organo.replace("[","").replace("]",""));
        }
      
            
         Entidad=Centidad.getSelectedItem().toString();
          System.out.println("entidaaaad "+Entidad);
         
    }
      
      
      public void llenaComboPeriodo(){
         
        if (version.equals("1.0") && (BD.equals("Estatal")))
        {
        ArrayPeriodo=query.PeriodoEstatus();    
        }
        if (version.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayPeriodo=queryNE.PeriodoNEstatus();    
        }
        if (version.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayPeriodo=V3queryNE.PeriodoNEstatus();    
        }
        if (version.equals("Estructura_Definita") && (BD.equals("Estatal")))
        {
        ArrayPeriodo=EDQuerys.PeriodoNEstatus();    
        }
         if (version.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayPeriodo=V1FedQuerys.PeriodoNEstatus();    
        }
         Cperiodo.removeAllItems();
         for (int i=0;i<ArrayPeriodo.size();i++){
          String Organo=(Arrays.toString(ArrayPeriodo.get(i)));
          Cperiodo.addItem(Organo.replace("[","").replace("]",""));
        }
    }
    
      
       public void llenaTablaEstatus(){
         
        if (version.equals("1.0") && (BD.equals("Estatal")))
        {
        ArrayTablaEstatus=Est.V1Estatus();    
        }
        if (version.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayTablaEstatus=Est.V2Estatus();    
        }
        if (version.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayTablaEstatus=Est.V3Estatus();    
        }
        if (version.equals("Estructura_Definita") && (BD.equals("Estatal")))
        {
        ArrayTablaEstatus=Est.EDEstatus();    
        }
         if (version.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayTablaEstatus=Est.V1Federal();    
        }
         DefaultTableModel TablaPeriodo = (DefaultTableModel) TablaE.getModel();     
        Object[] fila = new Object[9];      
        for(int j=0; j<ArrayTablaEstatus.size(); j++){
        String Periodo=Arrays.toString(ArrayTablaEstatus.get(j));
        String[] pp=Periodo.split(",");
        fila[0]=pp[0].replace("[", "").replace("]", "").trim();
        fila[1]=pp[1].replace("[", "").replace("]", "").trim();
        fila[2]=pp[2].replace("[", "").replace("]", "").trim();
        fila[3]=pp[3].replace("[", "").replace("]", "").trim();
        fila[4]=pp[4].replace("[", "").replace("]", "").trim();
        fila[5]=pp[5].replace("[", "").replace("]", "").trim();
        fila[6]=pp[6].replace("[", "").replace("]", "").trim();
        fila[7]=pp[7].replace("[", "").replace("]", "").trim();
        fila[8]=pp[8].replace("[", "").replace("]", "").trim();
        TablaPeriodo.addRow(fila);
        Class<?> col_class = TablaE.getColumnClass(0);
        TablaE.setDefaultEditor(col_class, null); 
        }
    }
    
    
    
    private void CentidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CentidadItemStateChanged
        // TODO add your handling code here:7
      /*  llenaComboClaveOrgano();
        llenaComboPeriodo();     */  
      
    }//GEN-LAST:event_CentidadItemStateChanged

    private void CentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CentidadActionPerformed
if ((Centidad.getSelectedIndex()>=0))
         {
           Entidad="";  
           Entidad=Centidad.getSelectedItem().toString();
             System.out.println("imorimeee entidad papu"+Entidad);
           total_organos.setText(V3queryNE.Total_Organos(Entidad));
           llenaComboClaveOrgano();
           llenaComboPeriodo();
             
         }
         
    }//GEN-LAST:event_CentidadActionPerformed

    private void CorganoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CorganoItemStateChanged
        // TODO add your handling code here:
       /*llenaComboPeriodo();*/
    }//GEN-LAST:event_CorganoItemStateChanged

    private void CorganoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorganoActionPerformed
       
    }//GEN-LAST:event_CorganoActionPerformed

    private void CperiodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CperiodoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CperiodoItemStateChanged

    private void CperiodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CperiodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CperiodoActionPerformed

    private void JOEstatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOEstatalActionPerformed

        // TODO add your handling code here:
         if(JOEstatal.isSelected()){
       BD="";
       BD="Estatal";
       Pversiones.setVisible(true);
       Rver2.setVisible(true);
        Rver3.setVisible(true);
        Rver4.setVisible(true);
         }
    }//GEN-LAST:event_JOEstatalActionPerformed

    private void JOFederalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOFederalActionPerformed
        // TODO add your handling code here:
        if(JOFederal.isSelected()){
        BD="";
        BD="Federal";
        Pversiones.setVisible(true);
        Rver2.setVisible(false);
        Rver3.setVisible(false);
        }
    }//GEN-LAST:event_JOFederalActionPerformed

    private void CentidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentidadMouseClicked

    }//GEN-LAST:event_CentidadMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        limpiartabla();
        Entidad="";
        Clave_organo="";
        Periodo="";
        Entidad=Centidad.getSelectedItem().toString();
        Clave_organo=Corgano.getSelectedItem().toString();
        Periodo=Cperiodo.getSelectedItem().toString();
        llenaTablaEstatus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TablaEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEMousePressed
        // TODO add your handling code here:
        
         int selectedRowIndex = TablaE.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)TablaE.getModel();
            if ((evt.getClickCount()==2)){
          Tid_control=model.getValueAt(selectedRowIndex, 0).toString();  
          Tclave_organo=model.getValueAt(selectedRowIndex, 1).toString();  
          Tsede=model.getValueAt(selectedRowIndex, 2).toString();  
          Tentidad_clave=model.getValueAt(selectedRowIndex, 3).toString();  
          Tentidad_nombre=model.getValueAt(selectedRowIndex, 4).toString();  
          Tmunicipio_clave=model.getValueAt(selectedRowIndex, 5).toString();  
          Tmunicipio_nombre=model.getValueAt(selectedRowIndex, 6).toString();  
          Tperiodo=model.getValueAt(selectedRowIndex, 7).toString();
          Testatus=model.getValueAt(selectedRowIndex, 8).toString();
          PCambioEstatus CEstatus= new PCambioEstatus();    
          CEstatus.setVisible(true);
                  
                
          
      }
    }//GEN-LAST:event_TablaEMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       PMenu men = new PMenu();
       men.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void Rver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rver4ActionPerformed
        // TODO add your handling code here:
        if(Rver4.isSelected()){  
        MuestraPanel();
        limpiartabla();
        version="";     
        version="Estructura_Definita";
        llenaComboEntidad();
       
        }
    }//GEN-LAST:event_Rver4ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PEstatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Centidad;
    private javax.swing.JComboBox Corgano;
    private javax.swing.JComboBox Cperiodo;
    private javax.swing.JRadioButton JOEstatal;
    private javax.swing.JRadioButton JOFederal;
    private javax.swing.JLabel Jentidad;
    private javax.swing.JLabel Jorgano;
    private javax.swing.JLabel Jperiodo;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel Pversiones;
    private javax.swing.JRadioButton Rver1;
    private javax.swing.JRadioButton Rver2;
    private javax.swing.JRadioButton Rver3;
    private javax.swing.JRadioButton Rver4;
    private javax.swing.JTable TablaE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel total_organos;
    // End of variables declaration//GEN-END:variables
}
