/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import Conexion.OracleDAOFactory;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.BD.InsertTR;
import mx.org.querys.V1querys;
import mx.org.querys.V2querysNE;
import mx.org.querys.V3Querys;
import mx.org.querys.federal.FedV1Querys;

/**
 *
 * @author ANTONIO.CORIA
 */
public class PInsertTR extends javax.swing.JFrame {

    /**
     * Creates new form PInsertTR
     */
    
     public static String tabla="",rutaT="",Versiones="",Nombre_archivo="",Directorio="",procedimiento,clave_entidad="",clave_organo="",periodo="",NMunicipio="",NENTIDAD="",BD="";
     public static boolean ventanaAbierta = false;
     List<String> testList = new ArrayList<String>();
     List<String> testProc = new ArrayList<String>();
     String TexTabla="",TexProc;
      ArrayList<String[]> ArrayClave_organo,ArrayClave_entidad;
       V1querys query=new V1querys();//Intanciar clase V1querys con nombre query
 V2querysNE queryNE=new V2querysNE();//Intanciar clase V2querysNE con nombre queryNE
 V3Querys V3queryNE=new V3Querys();//Intanciar clase V3querys con nombre V3queryNE
FedV1Querys V1FedQuerys=new FedV1Querys();
 
    public PInsertTR() {
        initComponents();
        this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        jPanel1.setVisible(false);
        R1.setVisible(false);
        R2.setVisible(false);
        R3.setVisible(false);
        Jorgano.setVisible(false);
        CorganoJur.setVisible(false);
        Jentidad.setVisible(false);
        Centidad.setVisible(false);
        LEntidad.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Lname = new javax.swing.JLabel();
        CTablas = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        CTablas1 = new javax.swing.JComboBox();
        LEntidad2 = new javax.swing.JLabel();
        Rclave_entidad = new javax.swing.JRadioButton();
        Rclave_organo = new javax.swing.JRadioButton();
        Jentidad = new javax.swing.JLabel();
        Centidad = new javax.swing.JComboBox();
        Jorgano = new javax.swing.JLabel();
        CorganoJur = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Textoperiodo1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        LEntidad = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        JOEstatal = new javax.swing.JRadioButton();
        JOFederal = new javax.swing.JRadioButton();
        R1 = new javax.swing.JRadioButton();
        R2 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INSERT TR");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Tabla"));

        Lname.setText("PROCEDIMIENTO:");

        CTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTablasActionPerformed(evt);
            }
        });

        jLabel1.setText("TABLA:");

        CTablas1.setName(""); // NOI18N
        CTablas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTablas1ActionPerformed(evt);
            }
        });

        LEntidad2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LEntidad2.setText("Entidad:");

        Rclave_entidad.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rclave_entidad);
        Rclave_entidad.setText("Clave Entidad");
        Rclave_entidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rclave_entidadActionPerformed(evt);
            }
        });

        Rclave_organo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rclave_organo);
        Rclave_organo.setText("Clave Organo");
        Rclave_organo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rclave_organoActionPerformed(evt);
            }
        });

        Jentidad.setText("Entidad:");

        Centidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CentidadItemStateChanged(evt);
            }
        });
        Centidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CentidadActionPerformed(evt);
            }
        });

        Jorgano.setText("Organo Jurisdiccional:");

        CorganoJur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CorganoJurItemStateChanged(evt);
            }
        });
        CorganoJur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorganoJurActionPerformed(evt);
            }
        });

        jLabel4.setText("Periodo:");

        Textoperiodo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Textoperiodo1KeyReleased(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/consultar.png"))); // NOI18N
        jButton2.setToolTipText("Seleccione para despliegue de periodos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LEntidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/errorins.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LEntidad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Jorgano)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Jentidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Rclave_entidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rclave_organo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Lname)
                                    .addComponent(jLabel1)
                                    .addComponent(CTablas1, 0, 371, Short.MAX_VALUE)
                                    .addComponent(CTablas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Lname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CTablas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LEntidad2)
                        .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rclave_entidad)
                    .addComponent(Rclave_organo))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jentidad)
                    .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jorgano)
                    .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione BD"));

        JOEstatal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(JOEstatal);
        JOEstatal.setText("Estatal");
        JOEstatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOEstatalActionPerformed(evt);
            }
        });

        JOFederal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(JOFederal);
        JOFederal.setText("Federal");
        JOFederal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOFederalActionPerformed(evt);
            }
        });

        R1.setText("VERSION 1.0");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });

        R2.setText("VERSION 2.0");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });

        R3.setText("VERSION 3.0");
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JOEstatal)
                    .addComponent(JOFederal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(R1)
                .addGap(18, 18, 18)
                .addComponent(R2)
                .addGap(18, 18, 18)
                .addComponent(R3)
                .addGap(104, 104, 104))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(JOEstatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JOFederal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1)
                    .addComponent(R2)
                    .addComponent(R3))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
        if(R1.isSelected()){
            Versiones="";
            Versiones="1.0";
           lLCTablas();
        }
    }//GEN-LAST:event_R1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        if(R2.isSelected()){
            Versiones="";
            Versiones="2.0";
           lLCTablas();
        }
    }//GEN-LAST:event_R2ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        if(R3.isSelected()){
            Versiones="";
            Versiones="3.0";
           lLCTablas();
           llenaCombo();
           llenaComboEntidad();
        }
    }//GEN-LAST:event_R3ActionPerformed

    public void llenaComboEntidad(){
         
        if (Versiones.equals("1.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=query.Entidad();    
        }
        if (Versiones.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=queryNE.EntidadNE();    
        }
        if (Versiones.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=V3queryNE.EntidadNE();    
        }
         if (Versiones.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayClave_entidad=V1FedQuerys.EntidadNE();    
        }
        
         Centidad.removeAllItems();
         for (int i=0;i<ArrayClave_entidad.size();i++){
          String Organo=(Arrays.toString(ArrayClave_entidad.get(i)));
          Centidad.addItem(Organo.replace("[","").replace("]",""));
        }
    }
    
    public void llenaCombo(){
         
        if (Versiones.equals("1.0") && (BD.equals("Estatal")) )
        {
        ArrayClave_organo=query.Clave_organo();    
        }
        if (Versiones.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=queryNE.Clave_organoNE();    
        }
         if (Versiones.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=V3queryNE.Clave_organoNE();    
        }
        if (Versiones.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayClave_organo=V1FedQuerys.Clave_organoNE();    
        } 
         CorganoJur.removeAllItems();
         for (int i=0;i<ArrayClave_organo.size();i++){
          String Organo=(Arrays.toString(ArrayClave_organo.get(i)));
          CorganoJur.addItem(Organo.replace("[","").replace("]",""));
        }
    }
    
    
    
    private void CTablas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTablas1ActionPerformed
        // TODO add your handling code here:
        if (CTablas1.getSelectedIndex() == -1){
        }else{
            procedimiento=CTablas1.getSelectedItem().toString();
            if(procedimiento.equals("INICIO"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("INICIO()");
                // Lname.setText("CONTROL EXPEDIENTE");

            }
            if(procedimiento.equals("CONTROL_EXPEDIENTE"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_CONTROL_EXPEDIENTEJL");
                // Lname.setText("CONTROL EXPEDIENTE");

            }
            if(procedimiento.equals("AUDIENCIAS"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_AUDIENCIASJL");
                //Lname.setText("AUDIENCIAS");
            }
            if(procedimiento.equals("ORDINARIO"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_ORDINARIOJL");
                CTablas.addItem("V3_TR_PART_ACT_ORDINARIOJL");
                CTablas.addItem("V3_TR_PART_DEM_ORDINARIOJL");
                // Lname.setText("T1 ORDINARIO");
            }
            if(procedimiento.equals("INDIVIDUAL"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_INDIVIDUALJL");
                CTablas.addItem("V3_TR_PART_ACT_INDIVIDUALJL");
                CTablas.addItem("V3_TR_PART_DEM_INDIVIDUALJL");
                // Lname.setText("T2 INDIVIDUAL");
            }
            if(procedimiento.equals("COLECTIVO"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_COLECTIVOJL");
                CTablas.addItem("V3_TR_PART_ACT_COLECTIVOJL");
                CTablas.addItem("V3_TR_PART_DEM_COLECTIVOJL");
                // Lname.setText("T3 COLECTIVO");
            }
            if(procedimiento.equals("HUELGA"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_HUELGAJL");
                CTablas.addItem("V3_TR_PART_ACT_HUELGAJL");
                CTablas.addItem("V3_TR_PART_DEM_HUELGAJL");
                // Lname.setText("T4 HUELGA");
            }
            if(procedimiento.equals("COLECTIVO_ECONOMICO"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_COLECT_ECONOMJL");
                CTablas.addItem("V3_TR_PART_ACT_COLECT_ECONOMJL");
                CTablas.addItem("V3_TR_PART_DEM_COLECT_ECONOMJL");
                Lname.setText("T5 COLECT ECONOM");
            }
            if(procedimiento.equals("TERCERIAS"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_TERCERIASJL");
                //  Lname.setText("T6 TERCERIAS");
            }
            if(procedimiento.equals("PREFERENCIA_CREDITO"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_PREF_CREDITOJL");
                // Lname.setText("T7 PREF CREDITO");
            }
            if(procedimiento.equals("PARAPROCESAL"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_PARAPROCESALJL");
                // Lname.setText("T8 PARAPROCESAL");
            }
            if(procedimiento.equals("EJECUCION"))
            {
                CTablas.removeAllItems();
                CTablas.addItem("V3_TR_EJECUCIONJL");
                // Lname.setText("T9 EJECUCION");
            }
        }
    }//GEN-LAST:event_CTablas1ActionPerformed

    private void CTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTablasActionPerformed
        // TODO add your handling code here:
        if (CTablas.getSelectedIndex() == -1){
        }else{
            tabla=CTablas.getSelectedItem().toString();
        }
    }//GEN-LAST:event_CTablasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                   
            new Thread(() -> {
            Valores();
            try {
             cargando carga= new cargando();
             carga.setVisible(true);
             InsertTR tr = new InsertTR();
             tr.InsertaTR();
             carga.setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(PInsertTMP.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Rclave_entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rclave_entidadActionPerformed
        // TODO add your handling code here:
        //evento valida si el radiobutton  entidad se selecciona muestra LEntidad,LEntidad2,Jentidad,Centidad en jframe PValidacion.
        if (Rclave_entidad.isSelected())
        {
            Valores();
            NEntidad();
            LEntidad.setVisible(true);
            LEntidad2.setVisible(true);
            Jorgano.setVisible(false);
            CorganoJur.setVisible(false);
            Jentidad.setVisible(true);
            Centidad.setVisible(true);
        }
    }//GEN-LAST:event_Rclave_entidadActionPerformed

    private void Rclave_organoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rclave_organoActionPerformed
        // TODO add your handling code here:
        //evento valida si el radiobutton  clave de organo se selecciona muestra LEntidad,LEntidad2,Jorgano,CorganoJur en jframe PValidacion.
        if(Rclave_organo.isSelected())
        {
            Valores();
            NEntidad_COrgano();
            LEntidad.setVisible(true);
            LEntidad2.setVisible(true);
            Jentidad.setVisible(false);
            Centidad.setVisible(false);
            Jorgano.setVisible(true);
            CorganoJur.setVisible(true);
        }

    }//GEN-LAST:event_Rclave_organoActionPerformed

    private void CentidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CentidadItemStateChanged
        // TODO add your handling code here:
        NEntidad();
    }//GEN-LAST:event_CentidadItemStateChanged

    private void CentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CentidadActionPerformed
        // TODO add your handling code here:
        /* if (Centidad.getSelectedItem().toString().equals("04"))
        {

        }else{

        }*/
        
        Valores();
    }//GEN-LAST:event_CentidadActionPerformed

    private void CorganoJurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CorganoJurItemStateChanged
        // TODO add your handling code here:
        NEntidad_COrgano();
    }//GEN-LAST:event_CorganoJurItemStateChanged

    private void CorganoJurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorganoJurActionPerformed
        // TODO add your handling code here:

        /* if (CorganoJur.getSelectedItem().toString().substring(0, 2).equals("04"))
        {

        }else{

        }*/
        Valores();
    }//GEN-LAST:event_CorganoJurActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Valores();
        PConPer per = new PConPer();
        per.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void JOEstatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOEstatalActionPerformed
        // TODO add your handling code here:
        if(JOEstatal.isSelected()){
            R1.setVisible(true);
            R2.setVisible(true);
            R3.setVisible(true);
            BD="Estatal";
            Centidad.removeAllItems();
            CorganoJur.removeAllItems();
        }

    }//GEN-LAST:event_JOEstatalActionPerformed

    private void JOFederalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOFederalActionPerformed
        // TODO add your handling code here:
        if(JOFederal.isSelected()){
            BD="Federal";
            Centidad.removeAllItems();
            CorganoJur.removeAllItems();
        }
    }//GEN-LAST:event_JOFederalActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        clave_entidad="";
        clave_organo="";
        PMenu menu = new PMenu();
        menu.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       Valores();
        if (!ventanaAbierta) {
            Errores_InsertTR Error = new Errores_InsertTR();
            ventanaAbierta = true;
            Error.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana de errores de insert ya está abierta.");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void Textoperiodo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Textoperiodo1KeyReleased
        // TODO add your handling code here:
        Valores();
    }//GEN-LAST:event_Textoperiodo1KeyReleased
  
     public  void Valores(){
        if(Rclave_organo.isSelected())
        {
            clave_entidad="";
            clave_organo="";
            clave_organo=CorganoJur.getSelectedItem().toString();
            periodo=Textoperiodo1.getText();
            NMunicipio=LEntidad.getText();
            NENTIDAD=LEntidad.getText();
            tabla=CTablas.getSelectedItem().toString();
            System.out.println("valoreeeees"+clave_organo+" "+clave_entidad+" "+periodo+" "+tabla);
          
        }
        else if (Rclave_entidad.isSelected()){
            clave_entidad="";
            clave_organo="";
            clave_entidad=Centidad.getSelectedItem().toString();
            periodo=Textoperiodo1.getText();
            NMunicipio=LEntidad.getText();
            NENTIDAD=LEntidad.getText();
            tabla=CTablas.getSelectedItem().toString();
            System.out.println("valoreeeees"+clave_organo+" "+clave_entidad+" "+periodo+" "+tabla);
           
        }
    }
    
    
     public void lLCTablas(){
       jPanel1.setVisible(true);
       
       if (Versiones.equals("1.0"))
        {
            System.out.println(Versiones);     
        testList.clear();
        testList.add("Control");
        testList.add("Ordinario");
        testList.add("Especial individual");
        testList.add("Especial colectivo");
        testList.add("Huelga");
        testList.add("Seguridad Social");
        testList.add("Colectivo_Nat_Económica");
        testList.add("Paraprocesal");
        testList.add("Tercerías");
        testList.add("Preferencia de crédito");
        testList.add("Ejecución");  
        }
        if (Versiones.equals("2.0"))
        {
         System.out.println(Versiones);
         testList.clear();   
         CTablas.removeAllItems();
         testList.add("Control_expediente");
        testList.add("T.1.0_audiencias");
        testList.add("T.1.1_ordinario");
        testList.add("T.1.2_part_ordinario");
        testList.add("T.2.1_esp_indiv");
        testList.add("T.2.2_part_esp_indiv");
        testList.add("T.3.1_esp_colec");
        testList.add("T.3.2_part_esp_colec");
        testList.add("T.4.1_huelga");
        testList.add("T.4.2_part_huelga");
        testList.add("T.5.1_seg_soc");  
        testList.add("T.5.2_part_seg_soc"); 
        testList.add("T.7.1_parapro");
        testList.add("T.8.1_terce");
        testList.add("T.9.1_pref_cred");  
        testList.add("T.10.1_ejecu");
        }
         if (Versiones.equals("3.0"))
        {
        System.out.println(Versiones);
        testProc.clear();
        testProc.add("INICIO");
        testProc.add("CONTROL_EXPEDIENTE");
        testProc.add("AUDIENCIAS");
        testProc.add("ORDINARIO");
        testProc.add("INDIVIDUAL");
        testProc.add("COLECTIVO");
        testProc.add("HUELGA");
        testProc.add("COLECTIVO_ECONOMICO");
        testProc.add("TERCERIAS");
        testProc.add("PREFERENCIA_CREDITO");
        testProc.add("PARAPROCESAL");
        testProc.add("EJECUCION");
        } 
         CTablas1.removeAllItems();
         
         for (int i=0;i<testProc.size();i++){
          TexProc=testProc.get(i).toString();
           CTablas1.addItem(TexProc);   
        } 
        
        
    }
    
     
     public void NEntidad(){
      if (Centidad.getItemCount()>0)
    {  
        switch(Centidad.getSelectedItem().toString()){
            case "01":
             LEntidad.setText("Aguascalientes");
                break;
            case "02":
             LEntidad.setText("Baja California");
                break;
            case "03":
                LEntidad.setText("Baja California Sur");
                break;
            case "04":
                LEntidad.setText("Campeche");
                break;
            case "05":
                LEntidad.setText("Coahuila de Zaragoza");
                break;
            case "06":
                LEntidad.setText("Colima");
                break;
            case "07":
                LEntidad.setText("Chiapas");
                break;
            case "08":
                LEntidad.setText("Chihuahua");
                break;
            case "09":
                LEntidad.setText("Ciudad de México");
                break;
            case "10":
                LEntidad.setText("Durango");
                break;
            case "11":
                LEntidad.setText("Guanajuato");
                break;
            case "12":
                LEntidad.setText("Guerrero");
                break;
            case "13":
                LEntidad.setText("Hidalgo");
                break;
            case "14":
                LEntidad.setText("Jalisco");
                break;
            case "15":
                LEntidad.setText("México");
                break;
            case "16":
                LEntidad.setText("Michoacán de Ocampo");
                break;
            case "17":
                LEntidad.setText("Morelos");
                break;
            case "18":
                LEntidad.setText("Nayarit");
                break;
            case "19":
                LEntidad.setText("Nuevo León");
                break;
            case "20":
                LEntidad.setText("Oaxaca");
                break;
            case "21":
                LEntidad.setText("Puebla");
                break;
            case "22":
                LEntidad.setText("Querétaro");
                break;
            case "23":
                LEntidad.setText("Quintana Roo");
                break;
            case "24":
                LEntidad.setText("San Luis Potosí");
                break;
            case "25":
                LEntidad.setText("Sinaloa");
                break;
            case "26":
                LEntidad.setText("Sonora");
                break;
            case "27":
                LEntidad.setText("Tabasco");
                break;
            case "28":
                LEntidad.setText("Tamaulipas");
                break;
            case "29":
                LEntidad.setText("Tlaxcala");
                break;
            case "30":
                LEntidad.setText("Veracruz de Ignacio de la Llave");
                break;
            case "31":
                LEntidad.setText("Yucatán");
                break;
            case "32":
                LEntidad.setText("Zacatecas");
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se Encontro Entidad", "Valida", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "Favor de contactar al Administrador", "Valida", JOptionPane.WARNING_MESSAGE);
        }
        
    }
    }
     
     
     public void NEntidad_COrgano(){  
      
    if (CorganoJur.getItemCount()>0)
    {
        System.out.println(CorganoJur.getSelectedItem().toString().substring(0, 2));
        switch(CorganoJur.getSelectedItem().toString().substring(0, 2)){
            case "01":
             LEntidad.setText("Aguascalientes");
                break;
            case "02":
             LEntidad.setText("Baja California");
                break;
            case "03":
                LEntidad.setText("Baja California Sur");
                break;
            case "04":
                LEntidad.setText("Campeche");
                break;
            case "05":
                LEntidad.setText("Coahuila de Zaragoza");
                break;
            case "06":
                LEntidad.setText("Colima");
                break;
            case "07":
                LEntidad.setText("Chiapas");
                break;
            case "08":
                LEntidad.setText("Chihuahua");
                break;
            case "09":
                LEntidad.setText("Ciudad de México");
                break;
            case "10":
                LEntidad.setText("Durango");
                break;
            case "11":
                LEntidad.setText("Guanajuato");
                break;
            case "12":
                LEntidad.setText("Guerrero");
                break;
            case "13":
                LEntidad.setText("Hidalgo");
                break;
            case "14":
                LEntidad.setText("Jalisco");
                break;
            case "15":
                LEntidad.setText("México");
                break;
            case "16":
                LEntidad.setText("Michoacán de Ocampo");
                break;
            case "17":
                LEntidad.setText("Morelos");
                break;
            case "18":
                LEntidad.setText("Nayarit");
                break;
            case "19":
                LEntidad.setText("Nuevo León");
                break;
            case "20":
                LEntidad.setText("Oaxaca");
                break;
            case "21":
                LEntidad.setText("Puebla");
                break;
            case "22":
                LEntidad.setText("Querétaro");
                break;
            case "23":
                LEntidad.setText("Quintana Roo");
                break;
            case "24":
                LEntidad.setText("San Luis Potosí");
                break;
            case "25":
                LEntidad.setText("Sinaloa");
                break;
            case "26":
                LEntidad.setText("Sonora");
                break;
            case "27":
                LEntidad.setText("Tabasco");
                break;
            case "28":
                LEntidad.setText("Tamaulipas");
                break;
            case "29":
                LEntidad.setText("Tlaxcala");
                break;
            case "30":
                LEntidad.setText("Veracruz de Ignacio de la Llave");
                break;
            case "31":
                LEntidad.setText("Yucatán");
                break;
            case "32":
                LEntidad.setText("Zacatecas");
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se Encontro Entidad", "Valida", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "Favor de contactar al Administrador", "Valida", JOptionPane.WARNING_MESSAGE);
        }
    }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PInsertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PInsertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PInsertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PInsertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PInsertTR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CTablas;
    private javax.swing.JComboBox CTablas1;
    private javax.swing.JComboBox Centidad;
    private javax.swing.JComboBox CorganoJur;
    private javax.swing.JRadioButton JOEstatal;
    private javax.swing.JRadioButton JOFederal;
    private javax.swing.JLabel Jentidad;
    private javax.swing.JLabel Jorgano;
    private javax.swing.JLabel LEntidad;
    private javax.swing.JLabel LEntidad2;
    private javax.swing.JLabel Lname;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JRadioButton Rclave_entidad;
    private javax.swing.JRadioButton Rclave_organo;
    public javax.swing.JTextField Textoperiodo1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
