/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screen_laborales;

import Conexion.OracleConexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author ANTONIO.CORIA
 */
public class PMapeoProcesarActToV3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PMapeoProcesarActToV3.class.getName());
    public static String Cve_Entidad="",Cve_ClaveOrgano="",Periodo="";
    
    
    /**
     * Creates new form PMapeoProcesarToV3
     */
    public PMapeoProcesarActToV3() {
        initComponents();
        this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        Jentidad.setVisible(false);
        Centidad.setVisible(false);
        LPer.setVisible(false);
        Textoperiodo1.setVisible(false);
        jButton2.setVisible(false);
        Jorgano.setVisible(false);
        CorganoJur.setVisible(false);
        LTabla.setVisible(false);
        jProgressBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Rclave_organo = new javax.swing.JRadioButton();
        Rclave_entidad = new javax.swing.JRadioButton();
        Jentidad = new javax.swing.JLabel();
        Centidad = new javax.swing.JComboBox<>();
        LPer = new javax.swing.JLabel();
        Textoperiodo1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Jorgano = new javax.swing.JLabel();
        CorganoJur = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        LTabla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesar Act To V3"));

        buttonGroup1.add(Rclave_organo);
        Rclave_organo.setText("Clave Organo");
        Rclave_organo.addActionListener(this::Rclave_organoActionPerformed);

        buttonGroup1.add(Rclave_entidad);
        Rclave_entidad.setText("Clave Entidad");
        Rclave_entidad.addActionListener(this::Rclave_entidadActionPerformed);

        Jentidad.setText("Entidad:");

        Centidad.setToolTipText("");

        LPer.setText("Periodo:");

        Textoperiodo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Textoperiodo1KeyReleased(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/consultar.png"))); // NOI18N
        jButton2.setToolTipText("Seleccione para despliegue de periodos");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        Jorgano.setText("Organo Jurisdiccional:");

        CorganoJur.addItemListener(this::CorganoJurItemStateChanged);
        CorganoJur.addActionListener(this::CorganoJurActionPerformed);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Insertar.png"))); // NOI18N
        jButton1.setText("Procesar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(LPer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Rclave_entidad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rclave_organo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Jentidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Jorgano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rclave_organo)
                    .addComponent(Rclave_entidad))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jentidad)
                    .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jorgano)
                    .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LPer)
                        .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(LTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Valores();
        PConPerToV3 per = new PConPerToV3();
        per.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void CorganoJurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CorganoJurItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_CorganoJurItemStateChanged

    private void CorganoJurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorganoJurActionPerformed
        // TODO add your handling code here:

        /* if (CorganoJur.getSelectedItem().toString().substring(0, 2).equals("04"))
        {

        }else{

        }*/
    }//GEN-LAST:event_CorganoJurActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
      new Thread(() -> {  
        Valores();
            
            
            
     }).start();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        PMenu menu=new PMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void Rclave_organoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rclave_organoActionPerformed
        // TODO add your handling code here:
          if(Rclave_organo.isSelected())
        {
            Jorgano.setVisible(true);
            CorganoJur.setVisible(true);
            Jentidad.setVisible(false);
            Centidad.setVisible(false);
            LPer.setVisible(true);
            Textoperiodo1.setVisible(true);
            jButton2.setVisible(true);
           try{
                OracleConexion conexion = new  OracleConexion();
                conexion.Conectar();
                ResultSet rs = conexion.consultar(" select distinct  CASE \n" +
                "        WHEN LENGTH(CLAVE_ORGANO) < 7 \n" +
                "        THEN SUBSTR(CLAVE_ORGANO, 1, LENGTH(CLAVE_ORGANO) - 1) || '0' || SUBSTR(CLAVE_ORGANO, -1, 1)\n" +
                "        ELSE CLAVE_ORGANO \n" +
                "    END AS clave_organo  from v3_tr_control_expedientejl ORDER BY CLAVE_ORGANO ");
                while (rs.next()) {
                    CorganoJur.addItem(rs.getString("CLAVE_ORGANO"));
                }
               
           }
           catch(SQLException e){
              e.printStackTrace();
           }
        }
        
    }//GEN-LAST:event_Rclave_organoActionPerformed

    private void Rclave_entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rclave_entidadActionPerformed
        // TODO add your handling code here:
          if (Rclave_entidad.isSelected())
        {
            
            Jorgano.setVisible(false);
            CorganoJur.setVisible(false);
            Jentidad.setVisible(true);
            Centidad.setVisible(true);
            LPer.setVisible(true);
            Textoperiodo1.setVisible(true);
            jButton2.setVisible(true);
            Centidad.addItem("01");
            Centidad.addItem("02");
            Centidad.addItem("03");
            Centidad.addItem("04");
            Centidad.addItem("05");
            Centidad.addItem("06");
            Centidad.addItem("07");
            Centidad.addItem("08");
            Centidad.addItem("09");
            Centidad.addItem("10");
            Centidad.addItem("11");
            Centidad.addItem("11");
            Centidad.addItem("12");
            Centidad.addItem("13");
            Centidad.addItem("14");
            Centidad.addItem("15");
            Centidad.addItem("16");
            Centidad.addItem("17");
            Centidad.addItem("18");
            Centidad.addItem("19");
            Centidad.addItem("20");
            Centidad.addItem("21");
            Centidad.addItem("22");
            Centidad.addItem("23");
            Centidad.addItem("24");
            Centidad.addItem("25");
            Centidad.addItem("26");
            Centidad.addItem("27");
            Centidad.addItem("28");
            Centidad.addItem("29");
            Centidad.addItem("30");
            Centidad.addItem("31");
            Centidad.addItem("32");
        }
    }//GEN-LAST:event_Rclave_entidadActionPerformed

    private void Textoperiodo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Textoperiodo1KeyReleased
        // TODO add your handling code here:
            Textoperiodo1.setText(
        Textoperiodo1.getText().toUpperCase()
    );
    }//GEN-LAST:event_Textoperiodo1KeyReleased

    public void Valores(){     
        if (Rclave_entidad.isSelected()){
            Cve_Entidad=Centidad.getSelectedItem().toString();
            Cve_ClaveOrgano="";
            System.out.println("CVE Entidad:"+Cve_Entidad);
        }
        if (Rclave_organo.isSelected()){
            Cve_ClaveOrgano=CorganoJur.getSelectedItem().toString();
            Cve_Entidad="";
            System.out.println("CVE Organo:"+Cve_ClaveOrgano);
        }
        Periodo=Textoperiodo1.getText();
        System.out.println("Periodo"+Periodo);       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PMapeoProcesarActToV3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Centidad;
    private javax.swing.JComboBox CorganoJur;
    private javax.swing.JLabel Jentidad;
    private javax.swing.JLabel Jorgano;
    private javax.swing.JLabel LPer;
    private javax.swing.JLabel LTabla;
    private javax.swing.JRadioButton Rclave_entidad;
    private javax.swing.JRadioButton Rclave_organo;
    private javax.swing.JTextField Textoperiodo1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
