/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import Exportar_Valida.EDValidaciones;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import mx.org.querys.V1querys;
import mx.org.querys.V1QOrdinario;
import Exportar_Valida.V1Validaciones;
import Exportar_Valida.V2ValidacionesNE;
import Exportar_Valida.V3validaciones;
import Exportar_Valida.FED_V1validaciones;
import java.awt.Color;
import mx.org.querys.NotNull_Estruc_Definitiva.EDQueryGenerales;
import mx.org.querys.V2querysNE;
import mx.org.querys.V3Querys;
import mx.org.querys.federal.FedV1Querys;




/**
 *
 * @author ANTONIO.CORIA
 */
public class PValidacion extends javax.swing.JFrame {

public static String version="",versionF="",BD="",clave_entidad="",clave_organo="",periodo="",periodoAnt="",NMunicipio="",FechaJI="",FechaJF="",AñoJuridico="",NENTIDAD="";//variables publicas
public static int Maximo=0;
String Clave_organo;
 ArrayList<String[]> ArrayClave_organo,ArrayClave_entidad;
 V1querys query=new V1querys();//Intanciar clase V1querys con nombre query
 V2querysNE queryNE=new V2querysNE();//Intanciar clase V2querysNE con nombre queryNE
 V3Querys V3queryNE=new V3Querys();//Intanciar clase V3querys con nombre V3queryNE
 EDQueryGenerales EDQuerys = new EDQueryGenerales();
 FedV1Querys V1FedQuerys=new FedV1Querys();

 
 V1QOrdinario Ordinario= new V1QOrdinario();
 V1Validaciones Valida= new V1Validaciones();
 V2ValidacionesNE ValidaNE= new V2ValidacionesNE();
 V3validaciones V3ValidaNE= new V3validaciones();
 EDValidaciones EDvalida=new EDValidaciones();
 FED_V1validaciones FedValida=new FED_V1validaciones();
 
    
    public PValidacion() {
        initComponents();
        this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        PAgrupamiento.setVisible(false);//PANEL AGRUPAMIENTO VISIBLE = FALSE
        Jentidad.setVisible(false);
        Centidad.setVisible(false);
        Jorgano.setVisible(false);
        CorganoJur.setVisible(false);
        LEntidad.setVisible(false);
        LEntidad2.setVisible(false);
        JT1.setVisible(false);
        JT2.setVisible(false);
        JL1.setVisible(false);
        Pversiones.setVisible(false);
        JT1.setText("01/09/2021");
        JT2.setText("01/08/2022");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jComboBox3 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        PAgrupamiento = new javax.swing.JPanel();
        Rclave_organo = new javax.swing.JRadioButton();
        Rclave_entidad = new javax.swing.JRadioButton();
        Centidad = new javax.swing.JComboBox();
        Jentidad = new javax.swing.JLabel();
        Jorgano = new javax.swing.JLabel();
        CorganoJur = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        LEntidad2 = new javax.swing.JLabel();
        LEntidad = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Textoperiodo1 = new javax.swing.JTextField();
        Textoperiodo2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Pversiones = new javax.swing.JPanel();
        Rver1 = new javax.swing.JRadioButton();
        Rver2 = new javax.swing.JRadioButton();
        Rver3 = new javax.swing.JRadioButton();
        Rver4 = new javax.swing.JRadioButton();
        JL1 = new javax.swing.JLabel();
        JT1 = new javax.swing.JTextField();
        JT2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        JOEstatal = new javax.swing.JRadioButton();
        JOFederal = new javax.swing.JRadioButton();
        Lable = new javax.swing.JLabel();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Validacion BD");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        PAgrupamiento.setBackground(new java.awt.Color(255, 255, 255));
        PAgrupamiento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Variables a Validar"));

        Rclave_organo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rclave_organo);
        Rclave_organo.setText("Clave Organo");
        Rclave_organo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rclave_organoActionPerformed(evt);
            }
        });

        Rclave_entidad.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Rclave_entidad);
        Rclave_entidad.setText("Clave Entidad");
        Rclave_entidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rclave_entidadActionPerformed(evt);
            }
        });

        Centidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CentidadItemStateChanged(evt);
            }
        });
        Centidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CentidadActionPerformed(evt);
            }
        });

        Jentidad.setText("Entidad:");

        Jorgano.setText("Organo Jurisdiccional:");

        CorganoJur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CorganoJurItemStateChanged(evt);
            }
        });
        CorganoJur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorganoJurActionPerformed(evt);
            }
        });

        jLabel4.setText("Periodo:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/consultar.png"))); // NOI18N
        jButton2.setToolTipText("Seleccione para despliegue de periodos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LEntidad2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LEntidad2.setText("Entidad:");

        LEntidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Insertar.png"))); // NOI18N
        jButton1.setText("Validar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Textoperiodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Textoperiodo1ActionPerformed(evt);
            }
        });

        Textoperiodo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Textoperiodo2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Periodo Anterior:");

        javax.swing.GroupLayout PAgrupamientoLayout = new javax.swing.GroupLayout(PAgrupamiento);
        PAgrupamiento.setLayout(PAgrupamientoLayout);
        PAgrupamientoLayout.setHorizontalGroup(
            PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAgrupamientoLayout.createSequentialGroup()
                .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAgrupamientoLayout.createSequentialGroup()
                        .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PAgrupamientoLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PAgrupamientoLayout.createSequentialGroup()
                                        .addComponent(Jorgano)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PAgrupamientoLayout.createSequentialGroup()
                                        .addComponent(Jentidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PAgrupamientoLayout.createSequentialGroup()
                                        .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PAgrupamientoLayout.createSequentialGroup()
                                                .addComponent(Textoperiodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(PAgrupamientoLayout.createSequentialGroup()
                                .addComponent(Rclave_organo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rclave_entidad))
                            .addGroup(PAgrupamientoLayout.createSequentialGroup()
                                .addComponent(LEntidad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 258, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAgrupamientoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        PAgrupamientoLayout.setVerticalGroup(
            PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAgrupamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LEntidad2)
                    .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rclave_entidad)
                    .addComponent(Rclave_organo))
                .addGap(23, 23, 23)
                .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jentidad)
                    .addComponent(Centidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jorgano)
                    .addComponent(CorganoJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Textoperiodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAgrupamientoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PAgrupamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Textoperiodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAgrupamientoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAgrupamientoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        Pversiones.setBackground(new java.awt.Color(255, 255, 255));
        Pversiones.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione Version de BD"));

        Rver1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rver1);
        Rver1.setText("Estructura Ver. 1.0");
        Rver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rver1ActionPerformed(evt);
            }
        });

        Rver2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rver2);
        Rver2.setText("Estructura Ver. 2.0");
        Rver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rver2ActionPerformed(evt);
            }
        });

        Rver3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rver3);
        Rver3.setText("Estructura Ver. 3.0");
        Rver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rver3ActionPerformed(evt);
            }
        });

        Rver4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rver4);
        Rver4.setText("Estructura Definitiva");
        Rver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rver4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PversionesLayout = new javax.swing.GroupLayout(Pversiones);
        Pversiones.setLayout(PversionesLayout);
        PversionesLayout.setHorizontalGroup(
            PversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PversionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rver3)
                    .addComponent(Rver2)
                    .addGroup(PversionesLayout.createSequentialGroup()
                        .addComponent(Rver1)
                        .addGap(42, 42, 42)
                        .addComponent(Rver4)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        PversionesLayout.setVerticalGroup(
            PversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PversionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rver1)
                    .addComponent(Rver4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rver2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rver3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        JL1.setText("Periodo Judicial:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione BD"));

        JOEstatal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(JOEstatal);
        JOEstatal.setText("Estatal");
        JOEstatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOEstatalActionPerformed(evt);
            }
        });

        JOFederal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(JOFederal);
        JOFederal.setText("Federal");
        JOFederal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOFederalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JOEstatal)
                    .addComponent(JOFederal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JOEstatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JOFederal)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lable, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JT1)
                    .addComponent(JT2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PAgrupamiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pversiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL1)
                            .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lable, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pversiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(PAgrupamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(JT1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

       //EVENTO AL CERRAR JFRAME PVALIDACION SE MAXIMIZA PANTALLA MENU 
       PMenu men = new PMenu();
       men.setVisible(true);
      
        
    }//GEN-LAST:event_formWindowClosing

  
    
    
    private void Rver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rver2ActionPerformed
        // TODO add your handling code here:
        //EVENTO AL SELECCIONAR RADIO BUTTON Estructura Ver. 2.0 SE ASIGNA VARIABLE version=2.0 corre proceso LLENACOMBO() Y LLENACOMBOENTIDAD()
        if(Rver2.isSelected()){
            PAgrupamiento.setVisible(true);
           version="";
            version="2.0";
             llenaCombo();
             llenaComboEntidad();
        }
    }//GEN-LAST:event_Rver2ActionPerformed

    private void Rver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rver1ActionPerformed
        // TODO add your handling code here:
       //EVENTO AL SELECCIONAR RADIO BUTTON Estructura Ver. 2.0 SE ASIGNA VARIABLE version=2.0 corre proceso LLENACOMBO() Y LLENACOMBOENTIDAD()
        if((Rver1.isSelected()) &&  (BD.equals("Estatal"))){
            PAgrupamiento.setVisible(true);
            version="";
            version="1.0";
             llenaCombo();
             llenaComboEntidad();
        }
         if((Rver1.isSelected()) &&  (BD.equals("Federal"))){
            PAgrupamiento.setVisible(true);
            version="";
            version="1.0";
             llenaCombo();
             llenaComboEntidad();
        }
        
        
    }//GEN-LAST:event_Rver1ActionPerformed

    //proceso que llena combo CorganoJur para asignar todas las claves de organo existentes en la bd
    public void llenaCombo(){
         
        if (version.equals("1.0") && (BD.equals("Estatal")) )
        {
        ArrayClave_organo=query.Clave_organo();    
        }
        if (version.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=queryNE.Clave_organoNE();    
        }
        if (version.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=V3queryNE.Clave_organoNE();    
        }
        if (version.equals("Estructura_Definitiva") && (BD.equals("Estatal")))
        {
        ArrayClave_organo=EDQuerys.Clave_organoNE();    
        }
        if (version.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayClave_organo=V1FedQuerys.Clave_organoNE();    
        } 
         CorganoJur.removeAllItems();
         for (int i=0;i<ArrayClave_organo.size();i++){
          String Organo=(Arrays.toString(ArrayClave_organo.get(i)));
          CorganoJur.addItem(Organo.replace("[","").replace("]",""));
        }
    }
    
    //proceso que llena combo Centidad para asignar todas las claves de entidad existentes en la bd
     public void llenaComboEntidad(){
         
        if (version.equals("1.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=query.Entidad();    
        }
        if (version.equals("2.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=queryNE.EntidadNE();    
        }
        if (version.equals("3.0") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=V3queryNE.EntidadNE();    
        }
        if (version.equals("Estructura_Definitiva") && (BD.equals("Estatal")))
        {
        ArrayClave_entidad=EDQuerys.EntidadNE();    
        }
         if (version.equals("1.0") && (BD.equals("Federal")))
        {
        ArrayClave_entidad=V1FedQuerys.EntidadNE();    
        }
        
         Centidad.removeAllItems();
         for (int i=0;i<ArrayClave_entidad.size();i++){
          String Organo=(Arrays.toString(ArrayClave_entidad.get(i)));
          Centidad.addItem(Organo.replace("[","").replace("]",""));
        }
    }
    
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here
    }//GEN-LAST:event_formWindowOpened

    
    
    private void Rclave_organoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rclave_organoActionPerformed
        // TODO add your handling code here:
       //evento valida si el radiobutton  clave de organo se selecciona muestra LEntidad,LEntidad2,Jorgano,CorganoJur en jframe PValidacion.
        if(Rclave_organo.isSelected())
        {
            NEntidad_COrgano();
            LEntidad.setVisible(true);
            LEntidad2.setVisible(true);
            Jentidad.setVisible(false);
            Centidad.setVisible(false);
            Jorgano.setVisible(true);
            CorganoJur.setVisible(true);
        }
        
    }//GEN-LAST:event_Rclave_organoActionPerformed

    private void Rclave_entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rclave_entidadActionPerformed
        // TODO add your handling code here:
         //evento valida si el radiobutton  entidad se selecciona muestra LEntidad,LEntidad2,Jentidad,Centidad en jframe PValidacion.
        if (Rclave_entidad.isSelected())
        {
            NEntidad();   
            LEntidad.setVisible(true);
            LEntidad2.setVisible(true);
            Jorgano.setVisible(false);
            CorganoJur.setVisible(false);
             Jentidad.setVisible(true);
            Centidad.setVisible(true);
        }
    }//GEN-LAST:event_Rclave_entidadActionPerformed

    //boton que al dar click muestra los periodos segun la clave de organo o entidad seleccionada.
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Valores();
        PConPer per = new PConPer();
        per.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
      clave_entidad="";
      clave_organo="";
        PConPer per= new PConPer();
       per.setVisible(false); 
    }//GEN-LAST:event_formWindowClosed

    //asignacion de valores publicos clave_entidad,clave_organo,periodo para ser usados en clases V1Validaciones,V2Validaciones,V3Validaciones
    public void Valores(){
        
        FechaJI=JT1.getText();
        FechaJF=JT2.getText();
        AñoJuridico="(2020,2021,2022)";
        
        if(Rclave_organo.isSelected())
        {
            clave_entidad="";
            clave_organo="";
            clave_organo=CorganoJur.getSelectedItem().toString();
            periodo=Textoperiodo1.getText();
            periodoAnt=Textoperiodo2.getText();
            NMunicipio=LEntidad.getText();
            NENTIDAD=LEntidad.getText();
            System.out.println(clave_entidad+"+"+clave_organo+"+"+periodo+"+"+FechaJI+"+"+FechaJF+"+"+AñoJuridico);
        }
        else if (Rclave_entidad.isSelected()){
            clave_entidad="";
            clave_organo="";
            clave_entidad=Centidad.getSelectedItem().toString();
            periodo=Textoperiodo1.getText();
            periodoAnt=Textoperiodo2.getText();
            NMunicipio=LEntidad.getText();
            NENTIDAD=LEntidad.getText();
            System.out.println(clave_entidad+"+"+clave_organo+"+"+periodo+"+"+FechaJI+"+"+FechaJF+"+"+AñoJuridico);
        }
    }
    
    //boton de validacion al dar click corre clase V1Validaciones,V2Validaciones o V3validaciones segun la version seleccionada
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
new Thread(() -> {
    //Aquí ejecutamos nuestras tareas costosas
    if(Rclave_organo.isSelected()==true || Rclave_entidad.isSelected()== true){
     }
     if (!Centidad.getSelectedItem().toString().equals("") && !CorganoJur.getSelectedItem().toString().equals("")  
             && !JT1.getText().replace(" ", "").equals("")){
        //clase exportar validaciones falta
       
         Valores();
         try{            
       if (version.equals("1.0") && (BD.equals("Estatal")))
         {
         Valida.Valida_Laborales();
         }
         if (version.equals("2.0") && (BD.equals("Estatal")))
         {
             System.out.println("ENTROO A VALIDAR");
          ValidaNE.Valida_LaboralesNE();
         }
         if (version.equals("3.0") && (BD.equals("Estatal")))
         {
             System.out.println("ENTROO A VALIDAR");
          V3ValidaNE.Valida_LaboralesNE();
          JOptionPane.showMessageDialog(null, "Nota: Favor de asignar estatus en apartado Estatus de Menu Principal", "Valida", JOptionPane.WARNING_MESSAGE);
          PMenu menu = new PMenu();
          menu.setVisible(true);
          this.setVisible(false);
         }
         if (version.equals("1.0") && (BD.equals("Federal")))
         {
             System.out.println("ENTROO A VALIDAR");
             FedValida.Valida_LaboralesNE();
             
         }
         if (version.equals("Estructura_Definitiva") && (BD.equals("Estatal")))
         {
             System.out.println("ENTROO A VALIDAR");
          //V3ValidaNE.Valida_LaboralesNE();
          EDvalida.Valida_LaboralesNE();
          JOptionPane.showMessageDialog(null, "Nota: Favor de asignar estatus en apartado Estatus de Menu Principal", "Valida", JOptionPane.WARNING_MESSAGE);
          PMenu menu = new PMenu();
          menu.setVisible(true);
          this.setVisible(false);             
         }
        }catch(Exception ex){ 
       }
             }else{
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Valida", JOptionPane.WARNING_MESSAGE);
        }
}).start();        
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    //proceso para asignarle el texto a LEntidad segun la clave de entidad seleccionada
    public void NEntidad(){
      if (Centidad.getItemCount()>0)
    {  
        switch(Centidad.getSelectedItem().toString()){
            case "01":
             LEntidad.setText("Aguascalientes");
                break;
            case "02":
             LEntidad.setText("Baja California");
                break;
            case "03":
                LEntidad.setText("Baja California Sur");
                break;
            case "04":
                LEntidad.setText("Campeche");
                break;
            case "05":
                LEntidad.setText("Coahuila de Zaragoza");
                break;
            case "06":
                LEntidad.setText("Colima");
                break;
            case "07":
                LEntidad.setText("Chiapas");
                break;
            case "08":
                LEntidad.setText("Chihuahua");
                break;
            case "09":
                LEntidad.setText("Ciudad de México");
                break;
            case "10":
                LEntidad.setText("Durango");
                break;
            case "11":
                LEntidad.setText("Guanajuato");
                break;
            case "12":
                LEntidad.setText("Guerrero");
                break;
            case "13":
                LEntidad.setText("Hidalgo");
                break;
            case "14":
                LEntidad.setText("Jalisco");
                break;
            case "15":
                LEntidad.setText("México");
                break;
            case "16":
                LEntidad.setText("Michoacán de Ocampo");
                break;
            case "17":
                LEntidad.setText("Morelos");
                break;
            case "18":
                LEntidad.setText("Nayarit");
                break;
            case "19":
                LEntidad.setText("Nuevo León");
                break;
            case "20":
                LEntidad.setText("Oaxaca");
                break;
            case "21":
                LEntidad.setText("Puebla");
                break;
            case "22":
                LEntidad.setText("Querétaro");
                break;
            case "23":
                LEntidad.setText("Quintana Roo");
                break;
            case "24":
                LEntidad.setText("San Luis Potosí");
                break;
            case "25":
                LEntidad.setText("Sinaloa");
                break;
            case "26":
                LEntidad.setText("Sonora");
                break;
            case "27":
                LEntidad.setText("Tabasco");
                break;
            case "28":
                LEntidad.setText("Tamaulipas");
                break;
            case "29":
                LEntidad.setText("Tlaxcala");
                break;
            case "30":
                LEntidad.setText("Veracruz de Ignacio de la Llave");
                break;
            case "31":
                LEntidad.setText("Yucatán");
                break;
            case "32":
                LEntidad.setText("Zacatecas");
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se Encontro Entidad", "Valida", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "Favor de contactar al Administrador", "Valida", JOptionPane.WARNING_MESSAGE);
        }
        
    }
    }
    
//proceso para asignarle el texto a LEntidad segun la clave de organo seleccionada    
public void NEntidad_COrgano(){  
      
    if (CorganoJur.getItemCount()>0)
    {
        System.out.println(CorganoJur.getSelectedItem().toString().substring(0, 2));
        switch(CorganoJur.getSelectedItem().toString().substring(0, 2)){
            case "01":
             LEntidad.setText("Aguascalientes");
                break;
            case "02":
             LEntidad.setText("Baja California");
                break;
            case "03":
                LEntidad.setText("Baja California Sur");
                break;
            case "04":
                LEntidad.setText("Campeche");
                break;
            case "05":
                LEntidad.setText("Coahuila de Zaragoza");
                break;
            case "06":
                LEntidad.setText("Colima");
                break;
            case "07":
                LEntidad.setText("Chiapas");
                break;
            case "08":
                LEntidad.setText("Chihuahua");
                break;
            case "09":
                LEntidad.setText("Ciudad de México");
                break;
            case "10":
                LEntidad.setText("Durango");
                break;
            case "11":
                LEntidad.setText("Guanajuato");
                break;
            case "12":
                LEntidad.setText("Guerrero");
                break;
            case "13":
                LEntidad.setText("Hidalgo");
                break;
            case "14":
                LEntidad.setText("Jalisco");
                break;
            case "15":
                LEntidad.setText("México");
                break;
            case "16":
                LEntidad.setText("Michoacán de Ocampo");
                break;
            case "17":
                LEntidad.setText("Morelos");
                break;
            case "18":
                LEntidad.setText("Nayarit");
                break;
            case "19":
                LEntidad.setText("Nuevo León");
                break;
            case "20":
                LEntidad.setText("Oaxaca");
                break;
            case "21":
                LEntidad.setText("Puebla");
                break;
            case "22":
                LEntidad.setText("Querétaro");
                break;
            case "23":
                LEntidad.setText("Quintana Roo");
                break;
            case "24":
                LEntidad.setText("San Luis Potosí");
                break;
            case "25":
                LEntidad.setText("Sinaloa");
                break;
            case "26":
                LEntidad.setText("Sonora");
                break;
            case "27":
                LEntidad.setText("Tabasco");
                break;
            case "28":
                LEntidad.setText("Tamaulipas");
                break;
            case "29":
                LEntidad.setText("Tlaxcala");
                break;
            case "30":
                LEntidad.setText("Veracruz de Ignacio de la Llave");
                break;
            case "31":
                LEntidad.setText("Yucatán");
                break;
            case "32":
                LEntidad.setText("Zacatecas");
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se Encontro Entidad", "Valida", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "Favor de contactar al Administrador", "Valida", JOptionPane.WARNING_MESSAGE);
        }
    }
        
    }


    private void CentidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CentidadItemStateChanged
        // TODO add your handling code here:
        NEntidad();
    }//GEN-LAST:event_CentidadItemStateChanged

    private void CorganoJurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CorganoJurItemStateChanged
        // TODO add your handling code here:
        NEntidad_COrgano();
    }//GEN-LAST:event_CorganoJurItemStateChanged

    //evento para asignar la version al seleccionar radiobutton Estrucutura ver 3.0
    private void Rver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rver3ActionPerformed
        // TODO add your handling code here:
           if(Rver3.isSelected()){
            PAgrupamiento.setVisible(true);
           version="";
            version="3.0";
             llenaCombo();
             llenaComboEntidad();
        }
    }//GEN-LAST:event_Rver3ActionPerformed

    private void CentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CentidadActionPerformed
        // TODO add your handling code here:
       /* if (Centidad.getSelectedItem().toString().equals("04"))
        {
            
        }else{
           
        }*/
    }//GEN-LAST:event_CentidadActionPerformed

    private void CorganoJurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorganoJurActionPerformed
        // TODO add your handling code here:
       
        /* if (CorganoJur.getSelectedItem().toString().substring(0, 2).equals("04"))
        {
            
        }else{
            
         }*/
    }//GEN-LAST:event_CorganoJurActionPerformed

    private void JOEstatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOEstatalActionPerformed
        // TODO add your handling code here:
         if(JOEstatal.isSelected()){
            Rver2.setVisible(true);
            Rver3.setVisible(true);
            Rver4.setVisible(true);
            Pversiones.setVisible(true);
            BD="Estatal";
            Centidad.removeAllItems();
            CorganoJur.removeAllItems();
        }
        
        
    }//GEN-LAST:event_JOEstatalActionPerformed

    private void JOFederalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOFederalActionPerformed
        // TODO add your handling code here:
         if(JOFederal.isSelected()){
            Rver2.setVisible(false);
            Rver3.setVisible(false);
            Pversiones.setVisible(true);
            BD="Federal";
            Centidad.removeAllItems();
            CorganoJur.removeAllItems();
        }
    }//GEN-LAST:event_JOFederalActionPerformed

    private void Rver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rver4ActionPerformed
        // TODO add your handling code here:
           if(Rver4.isSelected()){
            PAgrupamiento.setVisible(true);
           version="";
            version="Estructura_Definitiva";
             llenaCombo();
             llenaComboEntidad();
        }
    }//GEN-LAST:event_Rver4ActionPerformed

    private void Textoperiodo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Textoperiodo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Textoperiodo2ActionPerformed

    private void Textoperiodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Textoperiodo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Textoperiodo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PValidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PValidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PValidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PValidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PValidacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Centidad;
    private javax.swing.JComboBox CorganoJur;
    private javax.swing.JLabel JL1;
    private javax.swing.JRadioButton JOEstatal;
    private javax.swing.JRadioButton JOFederal;
    public javax.swing.JTextField JT1;
    public javax.swing.JTextField JT2;
    private javax.swing.JLabel Jentidad;
    private javax.swing.JLabel Jorgano;
    private javax.swing.JLabel LEntidad;
    private javax.swing.JLabel LEntidad2;
    public static javax.swing.JLabel Lable;
    public javax.swing.JPanel PAgrupamiento;
    public static javax.swing.JPanel Pversiones;
    private javax.swing.JRadioButton Rclave_entidad;
    private javax.swing.JRadioButton Rclave_organo;
    private javax.swing.JRadioButton Rver1;
    private javax.swing.JRadioButton Rver2;
    private javax.swing.JRadioButton Rver3;
    private javax.swing.JRadioButton Rver4;
    public javax.swing.JTextField Textoperiodo1;
    public javax.swing.JTextField Textoperiodo2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
