/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import static Screen_laborales.Errores_InsertTR.Ttabla;
import java.awt.Color;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Reg_NI extends javax.swing.JFrame {

    /**
     * Creates new form Reg_NI
     */
    public Reg_NI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
    }

    
    public void Query_NI(){
    
        System.out.println("tabla"+Ttabla);
        jTextArea1.setText("");
        if (Ttabla.equals("V3_TR_CONTROL_EXPEDIENTEJL"))
        {
         jTextArea1.setText("select * from(\n" +
"  SELECT \n" +
"     ID_CONTROL,\n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"SEDE,\n" +
"JUECES_LABORAL_TOTAL,\n" +
"JUECES_LABORAL_SUB_HOM,\n" +
"JUECES_LABORAL_SUB_MUJ,\n" +
"JUECES_LABORAL_INDIV_HOM,\n" +
"JUECES_LABORAL_INDIV_MUJ,\n" +
"JUECES_LABORAL_COLEC_HOM,\n" +
"JUECES_LABORAL_COLEC_MUJ,\n" +
"JUECES_LABORAL_MIX_HOM,\n" +
"JUECES_LABORAL_MIX_MUJ,\n" +
"HORARIO,\n" +
"ENTIDAD_CLAVE,\n" +
"ENTIDAD_NOMBRE,\n" +
"case when length(MUNICIPIO_CLAVE) >3 OR PERIODO IN (SELECT UNIQUE(PERIODO) FROM V1_TR_CONTROLJL) then MUNICIPIO_CLAVE else ((ENTIDAD_CLAVE||MUNICIPIO_CLAVE)) end MUNICIPIO_CLAVE,\n" +
"MUNICIPIO_NOMBRE,\n" +
"COLONIA_NOMBRE,\n" +
"LATITUD_ORG1 LATITUD_ORG,\n" +
"LONGITUD_ORG1  LONGITUD_ORG,\n" +
"CON_V3_TC_CIRCUNS_ORGANOJL(CIRCUNS_ORG_JUR)CIRCUNS_ORG_JUR,\n" +
"OTRO_ESP_CIRCUNS,\n" +
"CON_V3_TC_JURISDICCIONJL(JURISDICCION)JURISDICCION,\n" +
"ORDINARIO,\n" +
"ESPECIAL_INDIVI,\n" +
"ESPECIAL_COLECT,\n" +
"HUELGA,\n" +
"COL_NATU_ECONOMICA,\n" +
"PARAP_VOLUNTARIO,\n" +
"TERCERIAS,\n" +
"PREF_CREDITO,\n" +
"EJECUCION,\n" +
"PERIODO\n" +
"  FROM V3_TMP_CONTROL_EXPEDIENTEJL\n" +
"  WHERE CLAVE_ORGANO||PERIODO  NOT IN (SELECT CLAVE_ORGANO||PERIODO  FROM V3_TR_CONTROL_EXPEDIENTEJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"' ) OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"' );");    
        }
       if (Ttabla.equals("V3_TR_AUDIENCIASJL")){
           jTextArea1.setText("select * from(\n" +
" SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"CON_V3_TC_AUD_TIPO_PROCEJL(TIPO_PROCED)TIPO_PROCED,\n" +
"ID_AUDIENCIA,\n" +
"CON_V3_TC_AUD_TIPO_AUDIENJL(ORDINARIO_TA)ORDINARIO_TA,\n" +
"CON_V3_TC_AUD_TIPO_AUDIENJL(ESPECIAL_INDIVI_TA)ESPECIAL_INDIVI_TA,\n" +
"CON_V3_TC_AUD_TIPO_AUDIENJL(ESPECIAL_COLECT_TA)ESPECIAL_COLECT_TA,\n" +
"CON_V3_TC_AUD_TIPO_AUDIENJL(HUELGA_TA)HUELGA_TA,\n" +
"CON_V3_TC_AUD_TIPO_AUDIENJL(COL_NATU_ECONOMICA_TA)COL_NATU_ECONOMICA_TA,\n" +
"ESP_OTRO_AUDIENCIA,\n" +
"FECHA_AUDIEN_CELEBRADA,\n" +
"INICIO,\n" +
"CONCLU,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_AUDIENCIASJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_AUDIENCIA  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_AUDIENCIA  FROM V3_TR_AUDIENCIASJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       } 
       if (Ttabla.equals("V3_TR_ORDINARIOJL")){
           jTextArea1.setText("select * from(\n" +
" SELECT \n" +
"     NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"FECHA_APERTURA_EXPEDIENTE,\n" +
"CON_V3_TC_TIPO_ASUNTOJL(TIPO_ASUNTO) TIPO_ASUNTO,\n" +
"CON_V3_TC_NAT_CONFLICTOJL(NAT_CONFLICTO) NAT_CONFLICTO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CONTRATO_ESCRITO) CONTRATO_ESCRITO,\n" +
"CON_V3_TC_TIPO_CONTRATOJL(TIPO_CONTRATO) TIPO_CONTRATO,\n" +
"RAMA_INDUS_INVOLUCRADA,\n" +
"CON_V3_TC_SECTOR_RAMAJL(SECTOR_RAMA) SECTOR_RAMA,\n" +
"CON_V3_TC_SUBSECTOR_RAMAJL(SUBSECTOR_RAMA) SUBSECTOR_RAMA,\n" +
"ENTIDAD_CLAVE,\n" +
"ENTIDAD_NOMBRE,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE)>3 OR PERIODO IN (SELECT UNIQUE(PERIODO) FROM V1_TR_CONTROLJL) then MUNICIPIO_CLAVE else ((ENTIDAD_CLAVE||MUNICIPIO_CLAVE)) end MUNICIPIO_CLAVE,\n" +
"MUNICIPIO_NOMBRE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(SUBCONTRATACION) SUBCONTRATACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DESPIDO) DESPIDO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(RESCISION_RL) RESCISION_RL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(TERMINACION_RESCISION_RL) TERMINACION_RESCISION_RL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(VIOLACION_CONTRATO) VIOLACION_CONTRATO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(RIESGO_TRABAJO) RIESGO_TRABAJO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(REVISION_CONTRATO) REVISION_CONTRATO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PART_UTILIDADES) PART_UTILIDADES,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_MOTIV_CONFLICTO) OTRO_MOTIV_CONFLICTO,\n" +
"OTRO_ESP_CONFLICTO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CIRCUNS_MOTIVO_CONFL) CIRCUNS_MOTIVO_CONFL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DETERM_EMPLEO_EMBARAZO) DETERM_EMPLEO_EMBARAZO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DETERM_EMPLEO_EDAD) DETERM_EMPLEO_EDAD,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DETERM_EMPLEO_GENERO) DETERM_EMPLEO_GENERO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DETERM_EMPLEO_ORIEN_SEX) DETERM_EMPLEO_ORIEN_SEX,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DETERM_EMPLEO_DISCAPACIDAD) DETERM_EMPLEO_DISCAPACIDAD,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DETERM_EMPLEO_SOCIAL) DETERM_EMPLEO_SOCIAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DETERM_EMPLEO_ORIGEN) DETERM_EMPLEO_ORIGEN,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DETERM_EMPLEO_RELIGION) DETERM_EMPLEO_RELIGION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DETERM_EMPLEO_MIGRA) DETERM_EMPLEO_MIGRA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_DISCRIMINACION) OTRO_DISCRIMINACION,\n" +
"OTRO_ESP_DISCRIMI,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(TRATA_LABORAL) TRATA_LABORAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(TRABAJO_FORZOSO) TRABAJO_FORZOSO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(TRABAJO_INFANTIL) TRABAJO_INFANTIL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(HOSTIGAMIENTO) HOSTIGAMIENTO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ACOSO_SEXUAL) ACOSO_SEXUAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PAGO_PRESTACIONES) PAGO_PRESTACIONES,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INDEMNIZACION) INDEMNIZACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(REINSTALACION) REINSTALACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(SALARIO_RETENIDO) SALARIO_RETENIDO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUMENTO_SALARIO) AUMENTO_SALARIO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DERECHO_ASCENSO) DERECHO_ASCENSO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DERECHO_PREFERENCIA) DERECHO_PREFERENCIA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DERECHO_ANTIGUEDAD) DERECHO_ANTIGUEDAD,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_CONCEPTO) OTRO_CONCEPTO,\n" +
"OTRO_ESP_RECLAMADO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AGUINALDO) AGUINALDO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(VACACIONES) VACACIONES,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PRIMA_VACACIONAL) PRIMA_VACACIONAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PRIMA_ANTIGUEDAD) PRIMA_ANTIGUEDAD,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_TIPO_PREST) OTRO_TIPO_PREST,\n" +
"OTRO_ESP_PRESTAC,\n" +
"MOTIVO_CONFLICTO_COLECT,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCOMPETENCIA) INCOMPETENCIA,\n" +
"CON_V3_TC_TIPO_INCOMPETENCIAJL(TIPO_INCOMPETENCIA) TIPO_INCOMPETENCIA,\n" +
"OTRO_ESP_INCOMP,\n" +
"FECHA_PRES_DEMANDA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CONSTANCIA_CONS_EXPEDIDA) CONSTANCIA_CONS_EXPEDIDA,\n" +
"CONSTANCIA_CLAVE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ASUN_EXCEP_CONCILIACION) ASUN_EXCEP_CONCILIACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PREVE_DEMANDA) PREVE_DEMANDA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DESAHOGO_PREV_DEMANDA) DESAHOGO_PREV_DEMANDA,\n" +
"CON_V3_TC_ESTATUS_DEMANDAJL(ESTATUS_DEMANDA) ESTATUS_DEMANDA,\n" +
"CON_V3_TC_CAU_IMPI_ADMI_DEMJL(CAU_IMP_ADM_DEMANDA) CAU_IMP_ADM_DEMANDA,\n" +
"FECHA_ADMI_DEMANDA,\n" +
"CANTIDAD_ACTORES,\n" +
"CANTIDAD_DEMANDADOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUDIENCIA_PRELIM) AUDIENCIA_PRELIM,\n" +
"FECHA_AUDIENCIA_PRELIM,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUDIENCIA_JUICIO) AUDIENCIA_JUICIO,\n" +
"FECHA_AUDIENCIA_JUICIO,\n" +
"CON_V3_TC_ESTATUS_EXPEDIENTEJL(ESTATUS_EXPEDIENTE) ESTATUS_EXPEDIENTE,\n" +
"FECHA_ACTO_PROCESAL,\n" +
"CON_V3_TC_FASE_EXPEDIENTEJL(FASE_SOLI_EXPEDIENTE) FASE_SOLI_EXPEDIENTE,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCIONFE)FORMA_SOLUCIONFE,\n" +
"OTRO_ESP_SOLUCIONFE,\n" +
"FECHA_DICTO_RESOLUCIONFE,\n" +
"MONTO_SOLUCION_FE,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCIONAP) FORMA_SOLUCIONAP,\n" +
"OTRO_ESP_SOLUCIONAP,\n" +
"FECHA_DICTO_RESOLUCIONAP,\n" +
"MONTO_SOLUCION_AP,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCIONAJ) FORMA_SOLUCIONAJ,\n" +
"OTRO_ESP_SOLUCIONAJ,\n" +
"FECHA_RESOLUCIONAJ,\n" +
"CON_V3_TC_TIPO_SENTENCIAJL(TIPO_SENTENCIAAJ) TIPO_SENTENCIA,\n" +
"MONTO_SOLUCIONAJ,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"FROM V3_TMP_ORDINARIOJL \n" +
" WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  FROM V3_TR_ORDINARIOJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }  
       if (Ttabla.equals("V3_TR_PART_ACT_ORDINARIOJL")){
           jTextArea1.setText("select * from(\n" +
"select * from(\n" +
" SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_ACTOR,\n" +
"CASE WHEN ACTOR='9' AND SUBSTR(CLAVE_ORGANO,0,2)='24' THEN '10' ELSE CON_V3_TC_ACTORJL(ACTOR) END ACTOR,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_ACT)DEFENSA_ACT,\n" +
"CON_V3_TC_SEXO_TRABAJADORJL(SEXO)SEXO,\n" +
"CON_V3_TC_EDAD_TRABAJADORJL(EDAD)EDAD,\n" +
"CON_V3_TC_OCUPACI_TRABAJADORJL(OCUPACION)OCUPACION,\n" +
"NSS,\n" +
"CURP,\n" +
"RFC_TRABAJADOR,\n" +
"CON_V3_TC_JORNADA_TRABAJADORJL(JORNADA)JORNADA,\n" +
"NOMBRE_SINDICATO,\n" +
"REG_ASOC_SINDICAL,\n" +
"CON_V3_TC_TIPO_SINDICATOJL(TIPO_SINDICATO)TIPO_SINDICATO,\n" +
"OTRO_ESP_SINDICATO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ORG_OBRERA)ORG_OBRERA,\n" +
"CON_V3_TC_ORGAN_OBRERAJL(NOMBRE_ORG_OBRERA)NOMBRE_ORG_OBRERA,\n" +
"OTRO_ESP_OBRERA,\n" +
"CANT_TRABAJA_INV,\n" +
"HOMBRES,\n" +
"MUJERES,\n" +
"NO_IDENTIFICADO,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_ACT_ORDINARIOJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  FROM V3_TR_PART_ACT_ORDINARIOJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }  
       if (Ttabla.equals("V3_TR_PART_DEM_ORDINARIOJL")){
           jTextArea1.setText("select * from(\n" +
"  SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_DEMANDADO,\n" +
"CON_V3_TC_DEMANDADOJL(DEMANDADO)DEMANDADO,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_DEM)DEFENSA_DEM,\n" +
"CON_V3_TC_TIPO_PATRONJL(TIPO)TIPO,\n" +
"RFC_PATRON,\n" +
"RAZON_SOCIAL_EMPR,\n" +
"CALLE,\n" +
"N_EXT,\n" +
"N_INT,\n" +
"COLONIA,\n" +
"CP,\n" +
"ENTIDAD_NOMBRE_EMPR,\n" +
"ENTIDAD_CLAVE_EMPR,\n" +
"MUNICIPIO_NOMBRE_EMPR,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE_EMPR)>3 then MUNICIPIO_CLAVE_EMPR else ((ENTIDAD_CLAVE_EMPR||MUNICIPIO_CLAVE_EMPR)) end MUNICIPIO_CLAVE_EMPR,\n" +
" LATITUD1_EMPR LATITUD_EMPR,\n" +
" LONGITUD1_EMPR LONGITUD_EMPR,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_DEM_ORDINARIOJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  FROM V3_TR_PART_DEM_ORDINARIOJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }  
      if (Ttabla.equals("V3_TR_INDIVIDUALJL")){
           jTextArea1.setText("select * from(\n" +
"SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"FECHA_APERTURA_EXPEDIENTE,\n" +
"CON_V3_TC_TIPO_ASUNTOJL(TIPO_ASUNTO)TIPO_ASUNTO,\n" +
"CON_V3_TC_NAT_CONFLICTOJL(NAT_CONFLICTO)NAT_CONFLICTO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CONTRATO_ESCRITO)CONTRATO_ESCRITO,\n" +
"CON_V3_TC_TIPO_CONTRATOJL(TIPO_CONTRATO)TIPO_CONTRATO,\n" +
"RAMA_INDUS_INVOLUCRADA,\n" +
"CON_V3_TC_SECTOR_RAMAJL(SECTOR_RAMA)SECTOR_RAMA,\n" +
"CON_V3_TC_SUBSECTOR_RAMAJL(SUBSECTOR_RAMA)SUBSECTOR_RAMA,\n" +
"ENTIDAD_CLAVE,\n" +
"ENTIDAD_NOMBRE,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE)>3 OR PERIODO IN (SELECT UNIQUE(PERIODO) FROM V1_TR_CONTROLJL)  then MUNICIPIO_CLAVE else ((ENTIDAD_CLAVE||MUNICIPIO_CLAVE)) end MUNICIPIO_CLAVE,\n" +
"MUNICIPIO_NOMBRE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(SUBCONTRATACION)SUBCONTRATACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INDOLE_TRABAJO)INDOLE_TRABAJO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PRESTACION_FP)PRESTACION_FP,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ARRENDAM_TRAB)ARRENDAM_TRAB,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CAPACITACION)CAPACITACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ANTIGUEDAD)ANTIGUEDAD,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PRIMA_ANTIGUEDAD)PRIMA_ANTIGUEDAD,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CONVENIO_TRAB)CONVENIO_TRAB,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DESIGNACION_TRAB_ACT_DELIC)DESIGNACION_TRAB_ACT_DELIC,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DESIGNACION_TRAB_FALLE)DESIGNACION_TRAB_FALLE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(TERMINACION_LAB)TERMINACION_LAB,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(RECUPERACION_CARGA)RECUPERACION_CARGA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(GASTOS_TRASLADOS)GASTOS_TRASLADOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INDEMNIZACION)INDEMNIZACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PAGO_INDEMNIZACION)PAGO_INDEMNIZACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DESACUERDO_MEDICOS)DESACUERDO_MEDICOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(COBRO_PRESTACIONES)COBRO_PRESTACIONES,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CONF_SEGURO_SOCIAL)CONF_SEGURO_SOCIAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_CONF)OTRO_CONF,\n" +
"OTRO_ESP_CONF,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCOMPETENCIA)INCOMPETENCIA,\n" +
"CON_V3_TC_TIPO_INCOMPETENCIAJL(TIPO_INCOMPETENCIA)TIPO_INCOMPETENCIA,\n" +
"OTRO_ESP_INCOMP,\n" +
"FECHA_PRES_DEMANDA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CONSTANCIA_CONS_EXPEDIDA)CONSTANCIA_CONS_EXPEDIDA,\n" +
"CONSTANCIA_CLAVE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ASUN_EXCEP_CONCILIACION)ASUN_EXCEP_CONCILIACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PREVE_DEMANDA)PREVE_DEMANDA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DESAHOGO_PREV_DEMANDA)DESAHOGO_PREV_DEMANDA,\n" +
"CON_V3_TC_ESTATUS_DEMANDAJL(ESTATUS_DEMANDA)ESTATUS_DEMANDA,\n" +
"CON_V3_TC_CAU_IMPI_ADMI_DEMJL(CAU_IMPI_ADMI_DEMANDA)CAU_IMPI_ADMI_DEMANDA,\n" +
"FECHA_ADMI_DEMANDA,\n" +
"CANTIDAD_ACTORES,\n" +
"CANTIDAD_DEMANDADOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(TRAMITACION_DEPURACION)TRAMITACION_DEPURACION,\n" +
"FECHA_DEPURACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUDIENCIA_PRELIM)AUDIENCIA_PRELIM,\n" +
"FECHA_AUDIENCIA_PRELIM,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUDIENCIA_JUICIO)AUDIENCIA_JUICIO,\n" +
"FECHA_AUDIENCIA_JUICIO,\n" +
"CON_V3_TC_ESTATUS_EXPEDIENTEJL(ESTATUS_EXPEDIENTE)ESTATUS_EXPEDIENTE,\n" +
"FECHA_ACTO_PROCESAL,\n" +
"CON_V3_TC_FASE_EXPEDIENTEJL(FASE_SOLI_EXPEDIENTE)FASE_SOLI_EXPEDIENTE,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCION_AD)FORMA_SOLUCION_AD,\n" +
"OTRO_ESP_SOLUCION_AD,\n" +
"FECHA_DICTO_RESOLUCION_AD,\n" +
"CON_V3_TC_TIPO_SENTENCIAJL(TIPO_SENTENCIA_AD)TIPO_SENTENCIA_AD,\n" +
"MONTO_SOLUCION_AD,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCION_TA)FORMA_SOLUCION_TA,\n" +
"OTRO_ESP_SOLUCION_TA,\n" +
"FECHA_RESOLUCION_TA,\n" +
"CON_V3_TC_TIPO_SENTENCIAJL(TIPO_SENTENCIA_TA)TIPO_SENTENCIA_TA,\n" +
"MONTO_SOLUCIÓN_TA,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCION_AP)FORMA_SOLUCION_AP,\n" +
"OTRO_ESP_SOLUCION_AP,\n" +
"FECHA_DICTO_RESOLUCION_AP,\n" +
"MONTO_SOLUCION_AP,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCION_AJ)FORMA_SOLUCION_AJ,\n" +
"OTRO_ESP_SOLUCION_AJ,\n" +
"FECHA_DICTO_RESOLUCION_AJ,\n" +
"CON_V3_TC_TIPO_SENTENCIAJL(TIPO_SENTENCIA_AJ)TIPO_SENTENCIA_AJ,\n" +
"MONTO_SOLUCIÓN_AJ,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"FROM V3_TMP_INDIVIDUALJL\n" +
"WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  FROM V3_TR_INDIVIDUALJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }   
       if (Ttabla.equals("V3_TR_PART_ACT_INDIVIDUALJL")){
           jTextArea1.setText("select * from(\n" +
" SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_ACTOR,\n" +
"CASE WHEN ACTOR='9' AND SUBSTR(CLAVE_ORGANO,0,2)='24' THEN '10' ELSE CON_V3_TC_ACTORJL(ACTOR) END ACTOR,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_ACT)DEFENSA_ACT,\n" +
"CON_V3_TC_SEXO_TRABAJADORJL(SEXO)SEXO,\n" +
"CON_V3_TC_EDAD_TRABAJADORJL(EDAD)EDAD,\n" +
"CON_V3_TC_OCUPACI_TRABAJADORJL(OCUPACION)OCUPACION,\n" +
"NSS,\n" +
"CURP,\n" +
"RFC_TRABAJADOR,\n" +
"CON_V3_TC_JORNADA_TRABAJADORJL(JORNADA)JORNADA,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_ACT_INDIVIDUALJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  FROM V3_TR_PART_ACT_INDIVIDUALJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }  
       if (Ttabla.equals("V3_TR_PART_DEM_INDIVIDUALJL")){
           jTextArea1.setText("select * from(\n" +
"  SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_DEMANDADO,\n" +
"CON_V3_TC_DEMANDADOJL(DEMANDADO)DEMANDADO,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_DEM)DEFENSA_DEM,\n" +
"CON_V3_TC_TIPO_PATRONJL(TIPO)TIPO,\n" +
"RFC_PATRON,\n" +
"RAZON_SOCIAL_EMPR,\n" +
"CALLE,\n" +
"N_EXT,\n" +
"N_INT,\n" +
"COLONIA,\n" +
"CP,\n" +
"ENTIDAD_NOMBRE_EMPR,\n" +
"ENTIDAD_CLAVE_EMPR,\n" +
"MUNICIPIO_NOMBRE_EMPR,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE_EMPR)>3 then MUNICIPIO_CLAVE_EMPR else ((ENTIDAD_CLAVE_EMPR||MUNICIPIO_CLAVE_EMPR) ) end MUNICIPIO_CLAVE_EMPR,\n" +
"LATITUD1_EMPR LATITUD_EMPR,\n" +
"LONGITUD1_EMPR LONGITUD_EMPR,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_DEM_INDIVIDUALJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  FROM V3_TR_PART_DEM_INDIVIDUALJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }  
    if (Ttabla.equals("V3_TR_COLECTIVOJL")){
           jTextArea1.setText("select * from(\n" +
"  SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"FECHA_APERTURA_EXPEDIENTE,\n" +
"CON_V3_TC_TIPO_ASUNTOJL(TIPO_ASUNTO)TIPO_ASUNTO,\n" +
"CON_V3_TC_NAT_CONFLICTOJL(NAT_CONFLICTO)NAT_CONFLICTO,\n" +
"RAMA_INDUS_INVOLUCRAD,\n" +
"CON_V3_TC_SECTOR_RAMAJL(SECTOR_RAMA)SECTOR_RAMA,\n" +
"CON_V3_TC_SUBSECTOR_RAMAJL(SUBSECTOR_RAMA)SUBSECTOR_RAMA,\n" +
"ENTIDAD_CLAVE,\n" +
"ENTIDAD_NOMBRE,\n" +
"case when length(MUNICIPIO_CLAVE) >3 OR PERIODO IN (SELECT UNIQUE(PERIODO) FROM V1_TR_CONTROLJL) then MUNICIPIO_CLAVE else ((ENTIDAD_CLAVE||MUNICIPIO_CLAVE)) end MUNICIPIO_CLAVE,\n" +
"MUNICIPIO_NOMBRE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DECLARACION_PERDIDA_MAY)DECLARACION_PERDIDA_MAY,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(SUSPENSION_TMP)SUSPENSION_TMP,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(TERMINACION_TRAB)TERMINACION_TRAB,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CONTRATACION_COLECTIVA)CONTRATACION_COLECTIVA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OMISIONES_REGLAMENTO)OMISIONES_REGLAMENTO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(REDUCCION_PERSONAL)REDUCCION_PERSONAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(VIOLA_DERECHOS)VIOLA_DERECHOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ELECCION_SINDICALES)ELECCION_SINDICALES,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(SANCION_SINDICALES)SANCION_SINDICALES,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_CONFLICTO)OTRO_CONFLICTO,\n" +
"OTRO_ESP_CONFLICTO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(NO_IMPUTABLE_ST)NO_IMPUTABLE_ST,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCAPACIDAD_FISICA_ST)INCAPACIDAD_FISICA_ST,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(FALTA_MATERIA_PRIM_ST)FALTA_MATERIA_PRIM_ST,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(FALTA_MINISTRACION_ST)FALTA_MINISTRACION_ST,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(FUERZA_MAYOR_TC)FUERZA_MAYOR_TC,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCAPACIDAD_FISICA_TC)INCAPACIDAD_FISICA_TC,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(QUIEBRA_LEGAL_TC)QUIEBRA_LEGAL_TC,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AGOTAMIENTO_MATERIA_TC)AGOTAMIENTO_MATERIA_TC,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(LIBERTAD_ASOCIACION)LIBERTAD_ASOCIACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(LIBERTAD_SINDICAL)LIBERTAD_SINDICAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DERECHO_COLECTIVA)DERECHO_COLECTIVA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_COLECTIVA)OTRO_COLECTIVA,\n" +
"OTRO_ESP_COLECTIVA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCOMPETENCIA)INCOMPETENCIA,\n" +
"CON_V3_TC_TIPO_INCOMPETENCIAJL(TIPO_INCOMPETENCIA)TIPO_INCOMPETENCIA,\n" +
"OTRO_ESP_INCOMP,\n" +
"FECHA_PRES_DEMANDA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CONSTANCIA_CONS_EXPEDIDA)CONSTANCIA_CONS_EXPEDIDA,\n" +
"CONSTANCIA_CLAVE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ASUN_EXCEP_CONCILIACION)ASUN_EXCEP_CONCILIACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PREVE_DEMANDA)PREVE_DEMANDA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DESAHOGO_PREV_DEMANDA)DESAHOGO_PREV_DEMANDA,\n" +
"CON_V3_TC_ESTATUS_DEMANDAJL(ESTATUS_DEMANDA)ESTATUS_DEMANDA,\n" +
"FECHA_ADMI_DEMANDA,\n" +
"CANTIDAD_ACTORES,\n" +
"CANTIDAD_DEMANDADOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUTO_DEPURACION)AUTO_DEPURACION,\n" +
"FECHA_DEPURACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUDIENCIA_JUICIO)AUDIENCIA_JUICIO,\n" +
"FECHA_AUDIENCIA_JUICIO,\n" +
"CON_V3_TC_ESTATUS_EXPEDIENTEJL(ESTATUS_EXPEDIENTE)ESTATUS_EXPEDIENTE,\n" +
"FECHA_ACTO_PROCESAL,\n" +
"CON_V3_TC_FASE_EXPEDIENTEJL(FASE_SOLI_EXPEDIENTE)FASE_SOLI_EXPEDIENTE,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCION_AD)FORMA_SOLUCION_AD,\n" +
"OTRO_ESP_SOLUCION_AD,\n" +
"FECHA_DICTO_RESOLUCION_AD,\n" +
"CON_V3_TC_TIPO_SENTENCIAJL(TIPO_SENTENCIA_AD)TIPO_SENTENCIA_AD,\n" +
"MONTO_SOLUCION_AD,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCION_AJ)FORMA_SOLUCION_AJ,\n" +
"OTRO_ESP_SOLUCION_AJ,\n" +
"FECHA_RESOLUCION_AJ,\n" +
"CON_V3_TC_TIPO_SENTENCIAJL(TIPO_SENTENCIA_AJ)TIPO_SENTENCIA_AJ,\n" +
"MONTO_SOLUCION_AJ,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_COLECTIVOJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  FROM V3_TR_COLECTIVOJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
     if (Ttabla.equals("V3_TR_PART_ACT_COLECTIVOJL")){
           jTextArea1.setText("select * from(\n" +
" SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_ACTOR,\n" +
"CASE WHEN ACTOR='9' AND SUBSTR(CLAVE_ORGANO,0,2)='24' THEN '10' ELSE CON_V3_TC_ACTORJL(ACTOR) END ACTOR,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_ACT)DEFENSA_ACT,\n" +
"NOMBRE_SINDICATO,\n" +
"REG_ASOC_SINDICAL,\n" +
"CON_V3_TC_TIPO_SINDICATOJL(TIPO_SINDICATO)TIPO_SINDICATO,\n" +
"OTRO_ESP_SINDICATO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ORG_OBRERA)ORG_OBRERA,\n" +
"CON_V3_TC_ORGAN_OBRERAJL(NOMBRE_ORG_OBRERA)NOMBRE_ORG_OBRERA,\n" +
"OTRO_ESP_OBRERA,\n" +
"CANT_TRABAJA_INV,\n" +
"HOMBRES,\n" +
"MUJERES,\n" +
"NO_IDENTIFICADO,\n" +
"CON_V3_TC_TIPO_PATRONJL(TIPO)TIPO,\n" +
"RFC_PATRON,\n" +
"RAZON_SOCIAL_EMPR,\n" +
"CALLE,\n" +
"N_EXT,\n" +
"N_INT,\n" +
"COLONIA,\n" +
"CP,\n" +
"ENTIDAD_NOMBRE_EMPR,\n" +
"ENTIDAD_CLAVE_EMPR,\n" +
"MUNICIPIO_NOMBRE_EMPR,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE_EMPR)>3 then MUNICIPIO_CLAVE_EMPR else ((ENTIDAD_CLAVE_EMPR||MUNICIPIO_CLAVE_EMPR) ) end  MUNICIPIO_CLAVE_EMPR,\n" +
" LATITUD_EMPR1  LATITUD_EMPR,\n" +
" LONGITUD_EMPR1  LONGITUD_EMPR,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_ACT_COLECTIVOJL  \n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  FROM V3_TR_PART_ACT_COLECTIVOJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
      if (Ttabla.equals("V3_TR_PART_DEM_COLECTIVOJL")){
           jTextArea1.setText("select * from(\n" +
" SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_DEMANDADO,\n" +
"CON_V3_TC_DEMANDADOJL(DEMANDADO)DEMANDADO,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_DEM)DEFENSA_DEM,\n" +
"NOMBRE_SINDICATO_DEM,\n" +
"REG_ASOC_SINDICAL_DEM,\n" +
"CON_V3_TC_TIPO_SINDICATOJL(TIPO_SINDICATO_DEM)TIPO_SINDICATO_DEM,\n" +
"OTRO_ESP_SINDICATO_DEM,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ORG_OBRERA_DEM)ORG_OBRERA_DEM,\n" +
"CON_V3_TC_ORGAN_OBRERAJL(NOMBRE_ORG_OBRERA_DEM)NOMBRE_ORG_OBRERA_DEM,\n" +
"OTRO_ESP_OBRERA_DEM,\n" +
"CANT_TRABAJA_INV_DEM,\n" +
"HOMBRES_DEM,\n" +
"MUJERES_DEM,\n" +
"NO_IDENTIFICADO_DEM,\n" +
"CON_V3_TC_TIPO_PATRONJL(TIPO_DEM_PAT)TIPO_DEM_PAT,\n" +
"RFC_PATRON_DEM,\n" +
"RAZON_SOCIAL_EMPR_DEM,\n" +
"CALLE,\n" +
"N_EXT,\n" +
"N_INT,\n" +
"COLONIA,\n" +
"CP,\n" +
"ENTIDAD_NOMBRE_EMPR,\n" +
"ENTIDAD_CLAVE_EMPR,\n" +
"MUNICIPIO_NOMBRE_EMPR,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE_EMPR)>3 then MUNICIPIO_CLAVE_EMPR else ((ENTIDAD_CLAVE_EMPR||MUNICIPIO_CLAVE_EMPR) )end MUNICIPIO_CLAVE_EMPR,\n" +
" LATITUD1_EMPR  LATITUD_EMPR,\n" +
" LONGITUD1_EMPR LONGITUD_EMPR,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_DEM_COLECTIVOJL  \n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  FROM V3_TR_PART_DEM_COLECTIVOJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
       if (Ttabla.equals("V3_TR_HUELGAJL")){
           jTextArea1.setText("select * from(\n" +
"  SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"FECHA_APERTURA_EXPEDIENTE,\n" +
"CON_V3_TC_TIPO_ASUNTOJL(TIPO_ASUNTO)TIPO_ASUNTO,\n" +
"RAMA_INDUS_INVOLUCRAD,\n" +
"CON_V3_TC_SECTOR_RAMAJL(SECTOR_RAMA)SECTOR_RAMA,\n" +
"CON_V3_TC_SUBSECTOR_RAMAJL(SUBSECTOR_RAMA)SUBSECTOR_RAMA,\n" +
"ENTIDAD_CLAVE,\n" +
"ENTIDAD_NOMBRE,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE)>3 OR PERIODO IN (SELECT UNIQUE(PERIODO) FROM V1_TR_CONTROLJL) then MUNICIPIO_CLAVE else ((ENTIDAD_CLAVE||MUNICIPIO_CLAVE)) end MUNICIPIO_CLAVE,\n" +
"MUNICIPIO_NOMBRE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(FIRMA_CONTRATO)FIRMA_CONTRATO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(REVISION_CONTRATO)REVISION_CONTRATO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCUMPLIM_CONTRATO)INCUMPLIM_CONTRATO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(REVISION_SALARIO)REVISION_SALARIO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(REPARTO_UTILIDADES)REPARTO_UTILIDADES,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(APOYO_OTRA_HUELGA)APOYO_OTRA_HUELGA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DESEQUILIBRIO_FAC_PROD)DESEQUILIBRIO_FAC_PROD,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_MOTIVO) OTRO_MOTIVO,\n" +
"ESPECIFIQUE_MOTIVO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCOMPETENCIA)INCOMPETENCIA,\n" +
"CON_V3_TC_TIPO_INCOMPETENCIAJL(TIPO_INCOMPETENCIA)TIPO_INCOMPETENCIA,\n" +
"ESPECIFIQUE_INCOMP,\n" +
"FECHA_PRESENTA_PETIC,\n" +
"CANTIDAD_ACTORES,\n" +
"CANTIDAD_DEMANDADOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(EMPLAZAMIENTO_HUELGA)EMPLAZAMIENTO_HUELGA,\n" +
"FECHA_EMPLAZAMIENTO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PREHUELGA)PREHUELGA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUDIENCIA_CONCILIACION)AUDIENCIA_CONCILIACION,\n" +
"FECHA_AUDIENCIA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ESTALLAMIENTO_HUELGA)ESTALLAMIENTO_HUELGA,\n" +
"CON_V3_TC_LICITUD_HUELGAJL(DECLARA_LICITUD_HUELGA)DECLARA_LICITUD_HUELGA,\n" +
"CON_V3_TC_EXISTENCIA_HUELGAJL(DECLARA_EXISTEN_HUELGA)DECLARA_EXISTEN_HUELGA,\n" +
"CON_V3_TC_ESTATUS_EXPEDIENTEJL(ESTATUS_EXPEDIENTE)ESTATUS_EXPEDIENTE,\n" +
"FECHA_ACTO_PROCESAL,\n" +
"CON_V3_TC_FASE_EXPEDIENTEJL(FASE_SOLI_EXPEDIENTE)FASE_SOLI_EXPEDIENTE,\n" +
"CON_V3_TC_FORMA_SOLUCION_PHJL(FORMA_SOLUCION_EMPLAZ)FORMA_SOLUCION_EMPLAZ,\n" +
"ESPECIFI_FORMA_EMPLAZ,\n" +
"FECHA_RESOLU_EMPLAZ,\n" +
"INCREMENTO_SOLICITADO,\n" +
"INCREMENTO_OTORGADO,\n" +
"CON_V3_TC_FORMA_SOLUCION_HJL(FORMA_SOLUCION_HUELGA)FORMA_SOLUCION_HUELGA,\n" +
"ESPECIFI_FORMA_HUELGA,\n" +
"FECHA_RESOLU_HUELGA,\n" +
"CON_V3_TC_TIPO_SENTENCIAJL(TIPO_SENTENCIA)TIPO_SENTENCIA,\n" +
"FECHA_ESTALLAM_HUELGA,\n" +
"FECHA_LEVANT_HUELGA,\n" +
"DIAS_HUELGA,\n" +
"MONTO_ESTIPULADO,\n" +
"SALARIOS_CAIDOS,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_HUELGAjl\n" +
" WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  FROM V3_TR_HUELGAJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
        if (Ttabla.equals("V3_TR_PART_ACT_HUELGAJL")){
           jTextArea1.setText("select * from(\n" +
" SELECT \n" +
"  NOMBRE_ORGANO_JURIS,\n" +
"  CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_ACTOR,\n" +
"CASE WHEN ACTOR='9' AND SUBSTR(CLAVE_ORGANO,0,2)='24' THEN '10' ELSE CON_V3_TC_ACTORJL(ACTOR) END ACTOR,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_ACT)DEFENSA_ACT,\n" +
"NOMBRE_SINDICATO,\n" +
"REG_ASOC_SINDICAL,\n" +
"CON_V3_TC_TIPO_SINDICATOJL(TIPO_SINDICATO)TIPO_SINDICATO,\n" +
"OTRO_ESP_SINDICATO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ORG_OBRERA)ORG_OBRERA,\n" +
"CON_V3_TC_ORGAN_OBRERAJL(NOMBRE_ORG_OBRERA)NOMBRE_ORG_OBRERA,\n" +
"OTRO_ESP_OBRERA,\n" +
"CANT_TRABAJA_INV,\n" +
"HOMBRES,\n" +
"MUJERES,\n" +
"NO_IDENTIFICADO,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_ACT_HUELGAJL \n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  FROM v3_tr_part_act_huelgajl) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
         if (Ttabla.equals("V3_TR_PART_DEM_HUELGAJL")){
           jTextArea1.setText("select * from(\n" +
" SELECT \n" +
"  NOMBRE_ORGANO_JURIS,\n" +
"  CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_DEMANDADO,\n" +
"CON_V3_TC_DEMANDADOJL(DEMANDADO)DEMANDADO,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_DEM)DEFENSA_DEM,\n" +
"CON_V3_TC_TIPO_PATRONJL(TIPO)TIPO,\n" +
"RFC_PATRON,\n" +
"RAZON_SOCIAL_EMPR,\n" +
"CALLE,\n" +
"N_EXT,\n" +
"N_INT,\n" +
"COLONIA,\n" +
"CP,\n" +
"ENTIDAD_NOMBRE_EMPR,\n" +
"ENTIDAD_CLAVE_EMPR,\n" +
"MUNICIPIO_NOMBRE_EMPR,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE_EMPR)>3 then MUNICIPIO_CLAVE_EMPR else ((ENTIDAD_CLAVE_EMPR||MUNICIPIO_CLAVE_EMPR)) end MUNICIPIO_CLAVE_EMPR,\n" +
" LATITUD1_EMPR LATITUD_EMPR,\n" +
" LONGITUD1_EMPR LONGITUD_EMPR,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_DEM_HUELGAJL \n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  FROM V3_TR_PART_DEM_HUELGAJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
          if (Ttabla.equals("V3_TR_COLECT_ECONOMJL")){
           jTextArea1.setText("select * from(\n" +
"SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"FECHA_APERTURA_EXPEDIENTE,\n" +
"CON_V3_TC_TIPO_ASUNTOJL(TIPO_ASUNTO)TIPO_ASUNTO,\n" +
"CON_V3_TC_NAT_CONFLICTOJL(NAT_CONFLICTO)NAT_CONFLICTO,\n" +
"RAMA_INVOLUCRAD,\n" +
"CON_V3_TC_SECTOR_RAMAJL(SECTOR_RAMA)SECTOR_RAMA,\n" +
"CON_V3_TC_SUBSECTOR_RAMAJL(SUBSECTOR_RAMA)SUBSECTOR_RAMA,\n" +
"ENTIDAD_CLAVE,\n" +
"ENTIDAD_NOMBRE,\n" +
" case when length(MUNICIPIO_CLAVE) >3 OR PERIODO IN (SELECT UNIQUE(PERIODO) FROM V1_TR_CONTROLJL) then MUNICIPIO_CLAVE else ( (ENTIDAD_CLAVE||MUNICIPIO_CLAVE) )end MUNICIPIO_CLAVE,\n" +
"MUNICIPIO_NOMBRE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(MODIF_CONDICIONES)MODIF_CONDICIONES,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(NUEVAS_CONDICIONES)NUEVAS_CONDICIONES,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(SUSPENSION_TEMPORAL)SUSPENSION_TEMPORAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(TERMINACION_COLECTIVA)TERMINACION_COLECTIVA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_MOTIVO_ECONOM)OTRO_MOTIVO_ECONOM,\n" +
"ESPECIFIQUE_ECONOM,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(EXCESO_PRODUCCION)EXCESO_PRODUCCION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCOSTEABILIDAD)INCOSTEABILIDAD,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(FALTA_FONDOS)FALTA_FONDOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCOMPETENCIA)INCOMPETENCIA,\n" +
"CON_V3_TC_TIPO_INCOMPETENCIAJL(TIPO_INCOMPETENCIA)TIPO_INCOMPETENCIA,\n" +
"ESPECIFIQUE_INCOMP,\n" +
"FECHA_PRES_DEMANDA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CONSTANCIA_CONS_EXPEDIDA)CONSTANCIA_CONS_EXPEDIDA,\n" +
"CONSTANCIA_CLAVE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ASUN_EXCEP_CONCILIACION)ASUN_EXCEP_CONCILIACION,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(PREVE_DEMANDA)PREVE_DEMANDA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DESAHOGO_PREV_DEMANDA)DESAHOGO_PREV_DEMANDA,\n" +
"CON_V3_TC_ESTATUS_DEMANDAJL(ESTATUS_DEMANDA)ESTATUS_DEMANDA,\n" +
"FECHA_ADMISION_DEMANDA,\n" +
"CANTIDAD_ACTORES,\n" +
"CANTIDAD_DEMANDADOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUDIENCIA_ECONOM)AUDIENCIA_ECONOM,\n" +
"FECHA_AUDIENCIA_ECONOM,\n" +
"CON_V3_TC_ESTATUS_EXPEDIENTEJL(ESTATUS_EXPEDIENTE)ESTATUS_EXPEDIENTE,\n" +
"FECHA_ACTO_PROCESAL,\n" +
"CON_V3_TC_FASE_EXPEDIENTEJL(FASE_SOLI_EXPEDIENTE)FASE_SOLI_EXPEDIENTE,\n" +
"CON_V3_TC_FORMA_SOLUCIONJL(FORMA_SOLUCION)FORMA_SOLUCION,\n" +
"ESPECIFIQUE_FORMA,\n" +
"FECHA_RESOLUCION,\n" +
"CON_V3_TC_TIPO_SENTENCIAJL(TIPO_SENTENCIA)TIPO_SENTENCIA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUMENTO_PERSONAL)AUMENTO_PERSONAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DISMINUCION_PERSONAL)DISMINUCION_PERSONAL,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUMENTO_JORNADALAB)AUMENTO_JORNADALAB,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DISMINUCION_JORNADALAB)DISMINUCION_JORNADALAB,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUMENTO_SEMANA)AUMENTO_SEMANA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DISMINUCION_SEMANA)DISMINUCION_SEMANA,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AUMENTO_SALARIOS)AUMENTO_SALARIOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(DISMINUCION_SALARIOS)DISMINUCION_SALARIOS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(OTRO_TIPO)OTRO_TIPO,\n" +
"ESPECIFIQUE_TIPO,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_COLECT_ECONOMJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  FROM V3_TR_COLECT_ECONOMJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
           if (Ttabla.equals("V3_TR_PART_ACT_COLECT_ECONOMJL")){
           jTextArea1.setText("select * from(\n" +
"  SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_ACTOR,\n" +
"--CASE WHEN ACTOR='9' AND SUBSTR(CLAVE_ORGANO,0,2)='24' THEN '10' ELSE CON_V3_TC_ACTORJL(ACTOR) END ACTOR,\n" +
"CON_V3_TC_ACTORJL(ACTOR)ACTOR,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_ACT)DEFENSA_ACT,\n" +
"NOMBRE_SINDICATO,\n" +
"REG_ASOC_SINDICAL,\n" +
"CON_V3_TC_TIPO_SINDICATOJL(TIPO_SINDICATO)TIPO_SINDICATO,\n" +
"OTRO_ESP_SINDICATO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ORG_OBRERA)ORG_OBRERA,\n" +
"CON_V3_TC_ORGAN_OBRERAJL(NOMBRE_ORG_OBRERA)NOMBRE_ORG_OBRERA,\n" +
"OTRO_ESP_OBRERA,\n" +
"CANT_TRABAJA_INV,\n" +
"HOMBRES,\n" +
"MUJERES,\n" +
"NO_IDENTIFICADO,\n" +
"CON_V3_TC_TIPO_PATRONJL(TIPO)TIPO,\n" +
"RFC_PATRON,\n" +
"RAZON_SOCIAL_EMPR,\n" +
"CALLE,\n" +
"N_EXT,\n" +
"N_INT,\n" +
"COLONIA,\n" +
"CP,\n" +
"ENTIDAD_NOMBRE_EMPR,\n" +
"ENTIDAD_CLAVE_EMPR,\n" +
"MUNICIPIO_NOMBRE_EMPR,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE)>3  THEN MUNICIPIO_CLAVE_EMPR else ((ENTIDAD_CLAVE_EMPR||MUNICIPIO_CLAVE_EMPR)) end  MUNICIPIO_CLAVE_EMPR,\n" +
"LATITUD_EMPR1 LATITUD_EMPR,\n" +
"LONGITUD_EMPR1 LONGITUD_EMPR,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_ACT_COLECT_ECONOMJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_ACTOR  FROM V3_TR_PART_ACT_COLECT_ECONOMJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
            if (Ttabla.equals("V3_TR_PART_DEM_COLECT_ECONOMJL")){
           jTextArea1.setText("select * from(\n" +
"  SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"ID_DEMANDADO,\n" +
"CON_V3_TC_DEMANDADOJL(DEMANDADO)DEMANDADO,\n" +
"CON_V3_TC_TIPO_DEFENSAJL(DEFENSA_DEM)DEFENSA_DEM,\n" +
"NOMBRE_SINDICATO_DEM,\n" +
"REG_ASOC_SINDICAL_DEM,\n" +
"CON_V3_TC_TIPO_SINDICATOJL(TIPO_SINDICATO_DEM)TIPO_SINDICATO_DEM,\n" +
"OTRO_ESP_SINDICATO_DEM,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(ORG_OBRERA_DEM)ORG_OBRERA_DEM,\n" +
"CON_V3_TC_ORGAN_OBRERAJL(NOMBRE_ORG_OBRERA_DEM)NOMBRE_ORG_OBRERA_DEM,\n" +
"OTRO_ESP_OBRERA_DEM,\n" +
"CANT_TRABAJA_INV_DEM,\n" +
"HOMBRES_DEM,\n" +
"MUJERES_DEM,\n" +
"NO_IDENTIFICADO_DEM,\n" +
"CON_V3_TC_TIPO_PATRONJL(TIPO_DEM_PAT)TIPO_DEM_PAT,\n" +
"RFC_PATRON_DEM,\n" +
"RAZON_SOCIAL_EMPR_DEM,\n" +
"CALLE,\n" +
"N_EXT,\n" +
"N_INT,\n" +
"COLONIA,\n" +
"CP,\n" +
"ENTIDAD_NOMBRE_EMPR,\n" +
"ENTIDAD_CLAVE_EMPR,\n" +
"MUNICIPIO_NOMBRE_EMPR,\n" +
"CASE WHEN LENGTH(MUNICIPIO_CLAVE_EMPR)>3 then MUNICIPIO_CLAVE_EMPR else ((ENTIDAD_CLAVE_EMPR||MUNICIPIO_CLAVE_EMPR)) end MUNICIPIO_CLAVE_EMPR,\n" +
"LATITUD_EMPR1 LATITUD_EMPR,\n" +
"LONGITUD_EMPR1 LONGITUD_EMPR,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PART_DEM_COLECT_ECONOMJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO||ID_DEMANDADO  FROM V3_TR_PART_DEM_COLECT_ECONOMJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
             if (Ttabla.equals("V3_TR_TERCERIASJL")){
           jTextArea1.setText("select * from(\n" +
"  SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"CLAVE_INCIDENTAL,\n" +
"FECHA_INCIDENTE,\n" +
"FECHA_APERTURA_INCIDENTAL,\n" +
"CON_V3_TC_TIPO_INCIDENTEJL(TIPO_INCIDENTE)TIPO_INCIDENTE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(CELEBRACION_AUDIENCIA)CELEBRACION_AUDIENCIA,\n" +
"FECHA_AUDIENCIA,\n" +
"CON_V3_TC_ESTATUS_EXPEDIENTEJL(ESTATUS_EXPEDIENTE)ESTATUS_EXPEDIENTE,\n" +
"CON_V3_TC_SENTE_INCIDENTALJL(SENTENCIA_INCIDENTAL)SENTENCIA_INCIDENTAL,\n" +
"FECHA_RESOLUCION,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
" FROM V3_TMP_TERCERIASJL \n" +
" WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  FROM V3_TR_TERCERIASJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
              if (Ttabla.equals("V3_TR_PREF_CREDITOJL")){
           jTextArea1.setText("select * from(\n" +
" SELECT \n" +
"    NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"FECHA_APERTURA_EXPEDIENTE,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AVISO_ORGANO_JURIS)AVISO_ORGANO_JURIS,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(AVISO_AUTORIDAD_ADMIN)AVISO_AUTORIDAD_ADMIN,\n" +
"FECHA_PRESENTACION,\n" +
"FECHA_ADMISION,\n" +
"CON_V3_TC_PROMOVENTEJL(PROMOVENTE)PROMOVENTE,\n" +
"ESPECIFIQUE,\n" +
"CON_V3_TC_ESTATUS_EXPEDIENTEJL(ESTATUS_EXPE)ESTATUS_EXPE,\n" +
"FECHA_RESOLUCION,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PREF_CREDITOJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  FROM V3_TR_PREF_CREDITOJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
               if (Ttabla.equals("V3_TR_PARAPROCESALJL")){
           jTextArea1.setText("select * from(\n" +
"   SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"FECHA_APERTURA_EXPEDIENTE,\n" +
"RAMA_INVOLUCRAD,\n" +
"CON_V3_TC_SECTOR_RAMAJL(SECTOR_RAMA)SECTOR_RAMA,\n" +
"CON_V3_TC_SUBSECTOR_RAMAJL(SUBSECTOR_RAMA)SUBSECTOR_RAMA,\n" +
"CON_V3_TC_MOTIVO_SOLICITUDJL(MOTIVO_SOLICITUD)MOTIVO_SOLICITUD,\n" +
"ESPECIFIQUE_MOTIVO,\n" +
"CON_V3_TC_RESPUESTA_SIMPLEJL(INCOMPETENCIA)INCOMPETENCIA,\n" +
"CON_V3_TC_TIPO_INCOMPETENCIAJL(TIPO_INCOMPETENCIA)TIPO_INCOMPETENCIA,\n" +
"ESPECIFIQUE_INCOMP,\n" +
"FECHA_PRESENTA_SOLI,\n" +
"FECHA_ADMISION_SOLI,\n" +
"CON_V3_TC_PROMOVENTEJL(PROMOVENTE)PROMOVENTE,\n" +
"ESPECIFIQUE_PROMOVENTE,\n" +
"CON_V3_TC_ESTATUS_EXPEDIENTEJL(ESTATUS_EXPEDIENTE)ESTATUS_EXPEDIENTE,\n" +
"FECHA_CONCLUSION_EXPE,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_PARAPROCESALJL\n" +
"   WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  FROM V3_TR_PARAPROCESALJL) --WHERE ANIO=p_anio) AND ANIO=p_anio\n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
                if (Ttabla.equals("V3_TR_EJECUCIONJL")){
           jTextArea1.setText("select * from(\n" +
"  SELECT \n" +
"NOMBRE_ORGANO_JURIS,\n" +
"CLAVE_ORGANO,\n" +
"TRIM(EXPEDIENTE_CLAVE) EXPEDIENTE_CLAVE,\n" +
"FECHA_APERTURA_EXPEDIENTE,\n" +
"CON_V3_TC_MOTIVO_PROMOCIONJL(MOTIVO_SOLICITUD_EJ)MOTIVO_SOLICITUD_EJ,\n" +
"FECHA_PRESENTACION,\n" +
"CON_V3_TC_ESTATUS_EXPEDIENTEJL(ESTATUS_EXPE)ESTATUS_EXPE,\n" +
"FECHA_CONCLUSION,\n" +
"CON_V3_TC_FASE_CONCLUSIONJL(FASE_CONCLUSION)FASE_CONCLUSION,\n" +
"COMENTARIOS,\n" +
"PERIODO\n" +
"  FROM V3_TMP_EJECUCIONJL\n" +
"  WHERE CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  NOT IN (SELECT CLAVE_ORGANO||EXPEDIENTE_CLAVE||PERIODO  FROM V3_TR_EJECUCIONJL) --WHERE ANIO=p_anio) AND ANIO=p_anio  \n" +
" order by CLAVE_ORGANO)where CLAVE_ORGANO IN ('"+PInsertTR.clave_organo+"') OR SUBSTR(CLAVE_ORGANO,0,2) IN ('"+PInsertTR.clave_entidad+"');");
       }
    
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Query NI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        System.out.println("entroooooo a REG_NI");
        Query_NI();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg_NI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg_NI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg_NI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg_NI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg_NI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
