/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen_laborales;

import static Screen_laborales.PAcumula.pru;
import java.awt.Color;
import javax.swing.JOptionPane;
import mx.org.querys.V3Querys;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Reg_Acumula extends javax.swing.JFrame {

    /**
     * Creates new form Reg_Acumula
     */
    public Reg_Acumula() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        LProgress.setVisible(false);
        jProgressBar1.setVisible(false);
    }
    
    
    public void MuestraAcum(){
    LProgress.setVisible(true);
    jProgressBar1.setVisible(true);    
    PAcumula Ac=new PAcumula();
    V3Querys V3q=new V3Querys();
    String RegAcum="",txt="";
    int progres=5;
    String[] ArrayTablas = new String[20];
    ArrayTablas[0]="V3_TR_AUDIENCIASJL";
    ArrayTablas[1]="V3_TR_ORDINARIOJL";
    ArrayTablas[2]="V3_TR_PART_ACT_ORDINARIOJL";
    ArrayTablas[3]="V3_TR_PART_DEM_ORDINARIOJL";
    ArrayTablas[4]="V3_TR_INDIVIDUALJL";
    ArrayTablas[5]="V3_TR_PART_ACT_INDIVIDUALJL";
    ArrayTablas[6]="V3_TR_PART_DEM_INDIVIDUALJL";
    ArrayTablas[7]="V3_TR_COLECTIVOJL";
    ArrayTablas[8]="V3_TR_PART_ACT_COLECTIVOJL";
    ArrayTablas[9]="V3_TR_PART_DEM_COLECTIVOJL";
    ArrayTablas[10]="V3_TR_HUELGAJL";
    ArrayTablas[11]="V3_TR_PART_ACT_HUELGAJL";
    ArrayTablas[12]="V3_TR_PART_DEM_HUELGAJL";
    ArrayTablas[13]="V3_TR_COLECT_ECONOMJL";
    ArrayTablas[14]="V3_TR_PART_ACT_COLECT_ECONOMJL";
    ArrayTablas[15]="V3_TR_PART_DEM_COLECT_ECONOMJL";
    ArrayTablas[16]="V3_TR_PARAPROCESALJL";
    ArrayTablas[17]="V3_TR_PREF_CREDITOJL";
    ArrayTablas[18]="V3_TR_TERCERIASJL";
    ArrayTablas[19]="V3_TR_EJECUCIONJL";    
       
    
     for (int i=0;i<=19;i++)
     { 
     RegAcum=V3q.Total_Reg_Acum(ArrayTablas[i], Ac.clave_organo, Ac.periodo2, Ac.periodo);
     txt=txt+" TABLA:"+ArrayTablas[i]+" \n"
             + "Dif_Reg_Acumulados:"+RegAcum+" \n"
             + "--------------------------------- \n";
       progres=progres+5;
         jProgressBar1.setValue(progres);
     }
    jProgressBar1.setValue(0);
    LProgress.setVisible(false);
    jProgressBar1.setVisible(false); 
    jTextArea1.setText(txt);
    if (pru.equals("1")){
        JOptionPane.showMessageDialog(null, "Los Registros de prueba se han mostrado correctamente");
    }
    if (pru.equals("0")){
    JOptionPane.showMessageDialog(null, "Los Registros se han acumulado correctamente");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        LProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        LProgress.setText("Procesando........");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LProgress))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         new Thread(() -> { 
        MuestraAcum();
        }).start();    
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg_Acumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg_Acumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg_Acumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg_Acumula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg_Acumula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LProgress;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
