/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screen_laborales;

import mx.org.BD.ReadCSV_Audiencias;
import mx.org.BD.ReadCSV_Colect_Econom;
import mx.org.BD.ReadCSV_Colectivo;
import mx.org.BD.ReadCSV_Control_Expediente;
import mx.org.BD.ReadCSV_Ejecucion;
import mx.org.BD.ReadCSV_Huelga;
import mx.org.BD.ReadCSV_Individual;
import mx.org.BD.ReadCSV_Ordinario;
import mx.org.BD.ReadCSV_Paraprocesal;
import mx.org.BD.ReadCSV_Part_Act_Colect_Econom;
import mx.org.BD.ReadCSV_Part_Act_Colectivo;
import mx.org.BD.ReadCSV_Part_Act_Huelga;
import mx.org.BD.ReadCSV_Part_Act_Individual;
import mx.org.BD.ReadCSV_Part_Act_Ordinario;
import mx.org.BD.ReadCSV_Part_Dem_Colect_Econom;
import mx.org.BD.ReadCSV_Part_Dem_Colectivo;
import mx.org.BD.ReadCSV_Part_Dem_Huelga;
import mx.org.BD.ReadCSV_Part_Dem_Individual;
import mx.org.BD.ReadCSV_Part_Dem_Ordinario;
import mx.org.BD.ReadCSV_Pref_Credito;
import mx.org.BD.ReadCSV_Tercerias;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Total_Insertados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Total_Insertados.class.getName());

    /**
     * Creates new form Total_Insertados
     */
    public Total_Insertados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ReadCSV_Audiencias readAud = new ReadCSV_Audiencias();
        ReadCSV_Control_Expediente readControl = new ReadCSV_Control_Expediente();
        ReadCSV_Ordinario readOrd = new ReadCSV_Ordinario();
        ReadCSV_Part_Act_Ordinario readPartActOrd = new ReadCSV_Part_Act_Ordinario();
        ReadCSV_Part_Dem_Ordinario readPartDemOrd = new ReadCSV_Part_Dem_Ordinario();
        ReadCSV_Individual readInd = new ReadCSV_Individual();
        ReadCSV_Part_Act_Individual readPartActInd = new ReadCSV_Part_Act_Individual();
        ReadCSV_Part_Dem_Individual readPartDemInd = new ReadCSV_Part_Dem_Individual();
        ReadCSV_Colectivo readCol = new ReadCSV_Colectivo();
        ReadCSV_Part_Act_Colectivo readActCol = new ReadCSV_Part_Act_Colectivo();
        ReadCSV_Part_Dem_Colectivo readDemCol = new ReadCSV_Part_Dem_Colectivo();
        ReadCSV_Huelga readHuel = new ReadCSV_Huelga();
        ReadCSV_Part_Act_Huelga readActHuel = new ReadCSV_Part_Act_Huelga();
        ReadCSV_Part_Dem_Huelga readDemHuel = new ReadCSV_Part_Dem_Huelga();
        ReadCSV_Colect_Econom readColect = new ReadCSV_Colect_Econom();
        ReadCSV_Part_Act_Colect_Econom readActColect = new ReadCSV_Part_Act_Colect_Econom();
        ReadCSV_Part_Dem_Colect_Econom readDemColect = new ReadCSV_Part_Dem_Colect_Econom();
        ReadCSV_Tercerias readTer = new ReadCSV_Tercerias();
        ReadCSV_Pref_Credito readPref = new ReadCSV_Pref_Credito();
        ReadCSV_Paraprocesal readPar = new ReadCSV_Paraprocesal();
        ReadCSV_Ejecucion readEjec = new ReadCSV_Ejecucion();
         
         String CantidadTexto="";
         CantidadTexto="Total registros leidos de CSV \n"
                  + "V3_TMP_CONTROL_EXPEDIENTEJL="+String.valueOf(readControl.TotalRegistros)+"\n"
                  + "V3_TMP_AUDIENCIASJL="+String.valueOf(readAud.TotalRegistros)+"\n"
                 + "V3_TMP_ORDINARIOJL="+String.valueOf(readOrd.TotalRegistros)+"\n"
                 + "V3_TMP_PART_ACT_ORDINARIOJL="+String.valueOf(readPartActOrd.TotalRegistros)+"\n"
                 + "V3_TMP_PART_DEM_ORDINARIOJL="+String.valueOf(readPartDemOrd.TotalRegistros)+"\n"
                 + "V3_TMP_INDIVIDUALJL="+String.valueOf(readInd.TotalRegistros)+"\n"
                 + "V3_TMP_PART_ACT_INDIVIDUALJL="+String.valueOf(readPartActInd.TotalRegistros)+"\n"
                 + "V3_TMP_PART_DEM_INDIVIDUALJL="+String.valueOf(readPartDemInd.TotalRegistros)+"\n"
                 + "V3_TMP_COLECTIVOJL="+String.valueOf(readCol.TotalRegistros)+"\n"
                 + "V3_TMP_PART_ACT_COLECTIVOJL="+String.valueOf(readActCol.TotalRegistros)+"\n"
                 + "V3_TMP_PART_DEM_COLECTIVOJL="+String.valueOf(readDemCol.TotalRegistros)+"\n"
                 + "V3_TMP_HUELGAJL="+String.valueOf(readHuel.TotalRegistros)+"\n"
                 + "V3_TMP_PART_ACT_HUELGAJL="+String.valueOf(readActHuel.TotalRegistros)+"\n"
                 + "V3_TMP_PART_DEM_HUELGAJL="+String.valueOf(readDemHuel.TotalRegistros)+"\n"
                 + "V3_TMP_COLECT_ECONOMJL="+String.valueOf(readColect.TotalRegistros)+"\n"
                 + "V3_TMP_PART_ACT_COLECT_ECONOMJL="+String.valueOf(readActColect.TotalRegistros)+"\n"
                 + "V3_TMP_PART_DEM_COLECT_ECONOMJL="+String.valueOf(readDemColect.TotalRegistros)+"\n"
                 + "V3_TMP_TERCERIASJL="+String.valueOf(readTer.TotalRegistros)+"\n"
                 + "V3_TMP_PREF_CREDITOJL="+String.valueOf(readPref.TotalRegistros)+"\n"
                 + "V3_TMP_PARAPROCESALJL="+String.valueOf(readPar.TotalRegistros)+"\n"
                 + "V3_TMP_EJECUCIONJL="+String.valueOf(readEjec.TotalRegistros)+"\n";
                jTextArea2.setText(CantidadTexto);
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Total_Insertados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
