/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screen_laborales;

import LeerQuery.QueryProcedureTR_Fed;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author ANDREA.HERNANDEZL
 */
public class Total_InsertadosTR extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Total_InsertadosTR.class.getName());

    /**
     * Creates new form Total_InsertadosTR
     */
    public Total_InsertadosTR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        mostrarResumen();
    }//GEN-LAST:event_formWindowOpened

    private void mostrarResumen() {
        try {
            QueryProcedureTR_Fed q = new QueryProcedureTR_Fed();
            ArrayList<Integer> tmp = q.conteoTMP_Federal();   // 10 valores
            ArrayList<Integer> tr = q.conteoTR_Federal();      // 17 valores

            jTextPane1.setText("");
            StyledDocument doc = jTextPane1.getStyledDocument();

            SimpleAttributeSet titulo = new SimpleAttributeSet();
            StyleConstants.setForeground(titulo, Color.BLACK);
            StyleConstants.setBold(titulo, true);
            doc.insertString(doc.getLength(), "Total registros TMP_FED vs TR_FED\n\n", titulo);

            // Las 10 tablas base
            agregarRegistroColor("TMP_FED_AUDIENCIAS", tmp.get(0), "TR_FED_AUDIENCIAS", tr.get(0));
            agregarRegistroColor("TMP_FED_COLECTIVO", tmp.get(1), "TR_FED_COLECTIVO", tr.get(1));
            agregarRegistroColor("TMP_FED_COLECTIVO_ECONOMICO", tmp.get(2), "TR_FED_COLECTIVO_ECONOMICO", tr.get(2));
            agregarRegistroColor("TMP_FED_CONTROL_EXPEDIENTE", tmp.get(3), "TR_FED_CONTROL_EXPEDIENTE", tr.get(5));
            agregarRegistroColor("TMP_FED_EJECUCION", tmp.get(4), "TR_FED_EJECUCION", tr.get(6));
            agregarRegistroColor("TMP_FED_HUELGA", tmp.get(5), "TR_FED_HUELGA", tr.get(7));
            agregarRegistroColor("TMP_FED_INDIVIDUAL", tmp.get(6), "TR_FED_INDIVIDUAL", tr.get(9));
            agregarRegistroColor("TMP_FED_ORDINARIO", tmp.get(7), "TR_FED_ORDINARIO", tr.get(11));
            agregarRegistroColor("TMP_FED_PARAPROCESAL", tmp.get(8), "TR_FED_PARAPROCESAL", tr.get(13));
            agregarRegistroColor("TMP_FED_SEG_SOCIAL", tmp.get(9), "TR_FED_SEG_SOCIAL", tr.get(15));

            // Las 6 tablas PREST_RECL, mismo formato, sin subtítulo aparte
            agregarRegistroColor("TR_FED_COLECTIVO_ECONOMICO_PREST_RECL", tr.get(3), "", 0);
            agregarRegistroColor("TR_FED_COLECTIVO_PREST_RECL", tr.get(4), "", 0);
            agregarRegistroColor("TR_FED_HUELGA_PREST_RECL", tr.get(8), "", 0);
            agregarRegistroColor("TR_FED_INDIVIDUAL_PREST_RECL", tr.get(10), "", 0);
            agregarRegistroColor("TR_FED_ORDINARIO_PREST_RECL", tr.get(12), "", 0);
            agregarRegistroColor("TR_FED_PARAPROCESAL_PREST_RECL", tr.get(14), "", 0);
            agregarRegistroColor("TR_FED_SEG_SOCIAL_PREST_RECL", tr.get(16), "", 0);

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, null, e);
            e.printStackTrace();
        }
    }

    private void agregarRegistroColor(String nombreIzq, int totalIzq, String nombreDer, int totalDer) {
        try {
            StyledDocument doc = jTextPane1.getStyledDocument();
            SimpleAttributeSet estiloNormal = new SimpleAttributeSet();
            StyleConstants.setForeground(estiloNormal, Color.BLACK);
            SimpleAttributeSet estiloRojo = new SimpleAttributeSet();
            StyleConstants.setForeground(estiloRojo, Color.RED);
            StyleConstants.setBold(estiloRojo, true);

            doc.insertString(doc.getLength(), nombreIzq + " = ", estiloNormal);
            doc.insertString(doc.getLength(), String.valueOf(totalIzq), estiloRojo);
            doc.insertString(doc.getLength(), "    |    " + nombreDer + " = ", estiloNormal);
            doc.insertString(doc.getLength(), String.valueOf(totalDer), estiloRojo);
            doc.insertString(doc.getLength(), "\n", estiloNormal);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Total_InsertadosTR().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
