/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screen_laborales;

import LeerQuery.QueryRalFed;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import mx.org.BD.ReadCSV_Audiencias;
import mx.org.BD.ReadCSV_Colect_Econom;
import mx.org.BD.ReadCSV_Colectivo;
import mx.org.BD.ReadCSV_Control_Expediente;
import mx.org.BD.ReadCSV_Ejecucion;
import mx.org.BD.ReadCSV_Huelga;
import mx.org.BD.ReadCSV_Individual;
import mx.org.BD.ReadCSV_Ordinario;
import mx.org.BD.ReadCSV_Paraprocesal;
import mx.org.BD.ReadCSV_Part_Act_Colect_Econom;
import mx.org.BD.ReadCSV_Part_Act_Colectivo;
import mx.org.BD.ReadCSV_Part_Act_Huelga;
import mx.org.BD.ReadCSV_Part_Act_Individual;
import mx.org.BD.ReadCSV_Part_Act_Ordinario;
import mx.org.BD.ReadCSV_Part_Dem_Colect_Econom;
import mx.org.BD.ReadCSV_Part_Dem_Colectivo;
import mx.org.BD.ReadCSV_Part_Dem_Huelga;
import mx.org.BD.ReadCSV_Part_Dem_Individual;
import mx.org.BD.ReadCSV_Part_Dem_Ordinario;
import mx.org.BD.ReadCSV_Pref_Credito;
import mx.org.BD.ReadCSV_Tercerias;
import mx.org.BD.federal.ReadCSV_Audiencias_Fed;
import mx.org.BD.federal.ReadCSV_ColectivoEconomico_Fed;
import mx.org.BD.federal.ReadCSV_Colectivo_Fed;
import mx.org.BD.federal.ReadCSV_ControlExpediente_Fed;
import mx.org.BD.federal.ReadCSV_Ejecucion_Fed;
import mx.org.BD.federal.ReadCSV_Huelga_Fed;
import mx.org.BD.federal.ReadCSV_Individual_Fed;
import mx.org.BD.federal.ReadCSV_Ordinario_Fed;
import mx.org.BD.federal.ReadCSV_Paraprocesal_Fed;
import mx.org.BD.federal.ReadCSV_SegSocial_Fed;
import mx.org.querys.V3Querys;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Total_Insertados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Total_Insertados.class.getName());

    /**
     * Creates new form Total_Insertados
     */
    public Total_Insertados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (PInsertTMP.Versiones.equals("0.0")) {
            mostrarTotalesFederal();
            return;
        }
        ReadCSV_Audiencias readAud = new ReadCSV_Audiencias();
        ReadCSV_Control_Expediente readControl = new ReadCSV_Control_Expediente();
        ReadCSV_Ordinario readOrd = new ReadCSV_Ordinario();
        ReadCSV_Part_Act_Ordinario readPartActOrd = new ReadCSV_Part_Act_Ordinario();
        ReadCSV_Part_Dem_Ordinario readPartDemOrd = new ReadCSV_Part_Dem_Ordinario();
        ReadCSV_Individual readInd = new ReadCSV_Individual();
        ReadCSV_Part_Act_Individual readPartActInd = new ReadCSV_Part_Act_Individual();
        ReadCSV_Part_Dem_Individual readPartDemInd = new ReadCSV_Part_Dem_Individual();
        ReadCSV_Colectivo readCol = new ReadCSV_Colectivo();
        ReadCSV_Part_Act_Colectivo readActCol = new ReadCSV_Part_Act_Colectivo();
        ReadCSV_Part_Dem_Colectivo readDemCol = new ReadCSV_Part_Dem_Colectivo();
        ReadCSV_Huelga readHuel = new ReadCSV_Huelga();
        ReadCSV_Part_Act_Huelga readActHuel = new ReadCSV_Part_Act_Huelga();
        ReadCSV_Part_Dem_Huelga readDemHuel = new ReadCSV_Part_Dem_Huelga();
        ReadCSV_Colect_Econom readColect = new ReadCSV_Colect_Econom();
        ReadCSV_Part_Act_Colect_Econom readActColect = new ReadCSV_Part_Act_Colect_Econom();
        ReadCSV_Part_Dem_Colect_Econom readDemColect = new ReadCSV_Part_Dem_Colect_Econom();
        ReadCSV_Tercerias readTer = new ReadCSV_Tercerias();
        ReadCSV_Pref_Credito readPref = new ReadCSV_Pref_Credito();
        ReadCSV_Paraprocesal readPar = new ReadCSV_Paraprocesal();
        ReadCSV_Ejecucion readEjec = new ReadCSV_Ejecucion();
        V3Querys Q=new V3Querys();
        
       ArrayList<String[]> ArrayResult =Q.TRegistrosV3Temporal(PInsertTMP.clave_organo,PInsertTMP.clave_entidad,PInsertTMP.Periodo);
        
         String CantidadTexto="";
         jTextPane1.setText("");
      try {
    StyledDocument doc = jTextPane1.getStyledDocument();

    SimpleAttributeSet titulo = new SimpleAttributeSet();
    StyleConstants.setForeground(titulo, Color.BLACK);
    StyleConstants.setBold(titulo, true);
    doc.insertString(doc.getLength(), "Total registros leídos de CSV VS TMP\n\n", titulo);
    agregarRegistroColor(jTextPane1, "CSV_CONTROL_EXPEDIENTEJL", readControl.TotalRegistros,"TMP_CONTROL_EXPEDIENTEJL",Integer.parseInt(ArrayResult.get(0)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_AUDIENCIASJL", readAud.TotalRegistros,"TMP_AUDIENCIASJL",Integer.parseInt(ArrayResult.get(1)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_ORDINARIOJL", readOrd.TotalRegistros,"TMP_ORDINARIOJL",Integer.parseInt(ArrayResult.get(2)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_ACT_ORDINARIOJL", readPartActOrd.TotalRegistros,"TMP_PART_ACT_ORDINARIOJL",Integer.parseInt(ArrayResult.get(3)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_DEM_ORDINARIOJL", readPartDemOrd.TotalRegistros,"TMP_PART_DEM_ORDINARIOJL",Integer.parseInt(ArrayResult.get(4)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_INDIVIDUALJL", readInd.TotalRegistros,"TMP_NDIVIDUALJL",Integer.parseInt(ArrayResult.get(5)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_ACT_INDIVIDUALJL", readPartActInd.TotalRegistros,"TMP_PART_ACT_INDIVIDUALJL",Integer.parseInt(ArrayResult.get(6)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_DEM_INDIVIDUALJL", readPartDemInd.TotalRegistros,"TMP_PART_DEM_INDIVIDUALJL",Integer.parseInt(ArrayResult.get(7)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_COLECTIVOJL", readCol.TotalRegistros,"TMP_COLECTIVOJL",Integer.parseInt(ArrayResult.get(8)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_ACT_COLECTIVOJL", readActCol.TotalRegistros,"TMP_PART_ACT_COLECTIVOJL",Integer.parseInt(ArrayResult.get(9)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_DEM_COLECTIVOJL", readDemCol.TotalRegistros,"TMP_PART_DEM_COLECTIVOJL",Integer.parseInt(ArrayResult.get(10)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_HUELGAJL", readHuel.TotalRegistros,"TMP_HUELGAJL",Integer.parseInt(ArrayResult.get(11)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_ACT_HUELGAJL", readActHuel.TotalRegistros,"TMP_PART_ACT_HUELGAJL",Integer.parseInt(ArrayResult.get(12)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_DEM_HUELGAJL", readDemHuel.TotalRegistros,"TMP_PART_DEM_HUELGAJL",Integer.parseInt(ArrayResult.get(13)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_COLECT_ECONOMJL", readColect.TotalRegistros,"TMP_COLECT_ECONOMJL",Integer.parseInt(ArrayResult.get(14)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_ACT_COLECT_ECONOMJL", readActColect.TotalRegistros,"TMP_PART_ACT_COLECT_ECONOMJL",Integer.parseInt(ArrayResult.get(15)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PART_DEM_COLECT_ECONOMJL", readDemColect.TotalRegistros,"TMP_PART_DEM_COLECT_ECONOMJL",Integer.parseInt(ArrayResult.get(16)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_TERCERIASJL", readTer.TotalRegistros,"TMP_TERCERIASJL",Integer.parseInt(ArrayResult.get(17)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PREF_CREDITOJL", readPref.TotalRegistros,"TMP_PREF_CREDITOJL",Integer.parseInt(ArrayResult.get(18)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_PARAPROCESALJL", readPar.TotalRegistros,"TMP_PARAPROCESALJL",Integer.parseInt(ArrayResult.get(19)[0].trim()));
    agregarRegistroColor(jTextPane1, "CSV_EJECUCIONJL", readEjec.TotalRegistros,"TMP_EJECUCIONJL",Integer.parseInt(ArrayResult.get(20)[0].trim()));

} catch (Exception e) {
    e.printStackTrace();
}
        
        
    }//GEN-LAST:event_formWindowOpened

   public void agregarRegistroColor(JTextPane texto, String CSV, int total, String TextTabla, int totalTmp) {
    try {
        StyledDocument doc = texto.getStyledDocument();

        SimpleAttributeSet estiloNormal = new SimpleAttributeSet();
        StyleConstants.setForeground(estiloNormal, Color.BLACK);
        SimpleAttributeSet estiloRojo = new SimpleAttributeSet();
        StyleConstants.setForeground(estiloRojo, Color.RED);
        StyleConstants.setBold(estiloRojo, true);
        doc.insertString(doc.getLength(), CSV + " = ", estiloNormal);
        doc.insertString(doc.getLength(), String.valueOf(total), estiloRojo);
        doc.insertString(doc.getLength(), "    |    " + TextTabla + " = ", estiloNormal);
        doc.insertString(doc.getLength(), String.valueOf(totalTmp), estiloRojo);
        doc.insertString(doc.getLength(), "\n", estiloNormal);

    } catch (Exception e) {
        e.printStackTrace();
    }
}
   
    private void mostrarTotalesFederal() {

        ReadCSV_ControlExpediente_Fed readControl = new ReadCSV_ControlExpediente_Fed();
        ReadCSV_Audiencias_Fed readAudFed = new ReadCSV_Audiencias_Fed();
        ReadCSV_Ordinario_Fed readOrd = new ReadCSV_Ordinario_Fed();
        ReadCSV_Individual_Fed readInd = new ReadCSV_Individual_Fed();
        ReadCSV_Colectivo_Fed readCol = new ReadCSV_Colectivo_Fed();
        ReadCSV_Huelga_Fed readHuel = new ReadCSV_Huelga_Fed();
        ReadCSV_SegSocial_Fed readSeg = new ReadCSV_SegSocial_Fed();
        ReadCSV_ColectivoEconomico_Fed readEco = new ReadCSV_ColectivoEconomico_Fed();
        ReadCSV_Paraprocesal_Fed readPar = new ReadCSV_Paraprocesal_Fed();
        ReadCSV_Ejecucion_Fed readEjec = new ReadCSV_Ejecucion_Fed();

        QueryRalFed q = new QueryRalFed();
        ArrayList<String[]> ArrayResult = q.TRegistrosTMPFederal();
        jTextPane1.setText("");

        try {

            StyledDocument doc = jTextPane1.getStyledDocument();

            SimpleAttributeSet titulo = new SimpleAttributeSet();
            StyleConstants.setForeground(titulo, Color.BLACK);
            StyleConstants.setBold(titulo, true);

            doc.insertString(doc.getLength(),
                    "Total registros leídos de CSV VS TMP FEDERAL\n\n",
                    titulo);

            agregarRegistroColor(jTextPane1,"CSV_CONTROL_EXPEDIENTE", readControl.TotalRegistros, "TMP_FED_CONTROL_EXPEDIENTE", Integer.parseInt(ArrayResult.get(0)[0]));
            agregarRegistroColor(jTextPane1,"CSV_AUDIENCIAS", readAudFed.TotalRegistros, "TMP_FED_AUDIENCIAS", Integer.parseInt(ArrayResult.get(1)[0]));
            agregarRegistroColor(jTextPane1,"CSV_ORDINARIO", readOrd.TotalRegistros, "TMP_FED_ORDINARIO", Integer.parseInt(ArrayResult.get(2)[0]));
            agregarRegistroColor(jTextPane1,"CSV_INDIVIDUAL", readInd.TotalRegistros, "TMP_FED_INDIVIDUAL", Integer.parseInt(ArrayResult.get(3)[0]));
            agregarRegistroColor(jTextPane1,"CSV_COLECTIVO", readCol.TotalRegistros, "TMP_FED_COLECTIVO", Integer.parseInt(ArrayResult.get(4)[0]));
            agregarRegistroColor(jTextPane1,"CSV_HUELGA", readHuel.TotalRegistros, "TMP_FED_HUELGA", Integer.parseInt(ArrayResult.get(5)[0]));
            agregarRegistroColor(jTextPane1,"CSV_SEG_SOCIAL", readSeg.TotalRegistros, "TMP_FED_SEG_SOCIAL", Integer.parseInt(ArrayResult.get(6)[0]));
            agregarRegistroColor(jTextPane1,"CSV_COLECTIVO_ECONOMICO", readEco.TotalRegistros, "TMP_FED_COLECTIVO_ECONOMICO", Integer.parseInt(ArrayResult.get(7)[0]));
            agregarRegistroColor(jTextPane1,"CSV_PARAPROCESAL", readPar.TotalRegistros, "TMP_FED_PARAPROCESAL", Integer.parseInt(ArrayResult.get(8)[0]));
            agregarRegistroColor(jTextPane1,"CSV_EJECUCION", readEjec.TotalRegistros, "TMP_FED_EJECUCION", Integer.parseInt(ArrayResult.get(9)[0]));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Total_Insertados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
