/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package mx.org.query.federal;

import Conexion.OracleConexionRalFed;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ANDREA.HERNANDEZL
 */
public class RF_Fechas_Ordinario {

    OracleConexionRalFed conexion = new OracleConexionRalFed();
    String sql;
    ArrayList<String[]> Array;
    ResultSet resul;

    public ArrayList Fed_OrdinarioFFuturas() {
        conexion.ConectarFed();
        Array = new ArrayList();
        sql = "SELECT\n"
                + "    NOMBRE_ORGANO_JURIS,\n"
                + "    ID_ORGANOJ,\n"
                + "    CLAVE_EXPEDIENTE,\n"
                + "    FECHA_PRESENTACION,\n"
                + "    FECHA_APERTURA_EXPEDIENTE,\n"
                + "    FECHA_ADM_DEMANDA,\n"
                + "    FECHA_ULT_ACT_PROC,\n"
                + "    FECHA_AUDIENCIA_PRELIM,\n"
                + "    FECHA_AUD_JUICIO,\n"
                + "    FECHA_SENTENCIA,\n"
                + "    FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "    RTRIM(\n"
                + "        CASE\n"
                + "            WHEN FECHA_PRESENTACION > SYSDATE THEN\n"
                + "                'FECHA_PRESENTACION (' || TO_CHAR(FECHA_PRESENTACION,'DD/MM/YYYY') || ') es mayor al día de hoy, '\n"
                + "            ELSE ''\n"
                + "        END ||\n"
                + "\n"
                + "        CASE\n"
                + "            WHEN FECHA_APERTURA_EXPEDIENTE > SYSDATE THEN\n"
                + "                'FECHA_APERTURA_EXPEDIENTE (' || TO_CHAR(FECHA_APERTURA_EXPEDIENTE,'DD/MM/YYYY') || ') es mayor al día de hoy, '\n"
                + "            ELSE ''\n"
                + "        END ||\n"
                + "\n"
                + "        CASE\n"
                + "            WHEN FECHA_ADM_DEMANDA > SYSDATE THEN\n"
                + "                'FECHA_ADM_DEMANDA (' || TO_CHAR(FECHA_ADM_DEMANDA,'DD/MM/YYYY') || ') es mayor al día de hoy, '\n"
                + "            ELSE ''\n"
                + "        END ||\n"
                + "\n"
                + "        CASE\n"
                + "            WHEN FECHA_ULT_ACT_PROC > SYSDATE THEN\n"
                + "                'FECHA_ULT_ACT_PROC (' || TO_CHAR(FECHA_ULT_ACT_PROC,'DD/MM/YYYY') || ') es mayor al día de hoy, '\n"
                + "            ELSE ''\n"
                + "        END ||\n"
                + "\n"
                + "        CASE\n"
                + "            WHEN FECHA_AUDIENCIA_PRELIM > SYSDATE THEN\n"
                + "                'FECHA_AUDIENCIA_PRELIM (' || TO_CHAR(FECHA_AUDIENCIA_PRELIM,'DD/MM/YYYY') || ') es mayor al día de hoy, '\n"
                + "            ELSE ''\n"
                + "        END ||\n"
                + "\n"
                + "        CASE\n"
                + "            WHEN FECHA_AUD_JUICIO > SYSDATE THEN\n"
                + "                'FECHA_AUD_JUICIO (' || TO_CHAR(FECHA_AUD_JUICIO,'DD/MM/YYYY') || ') es mayor al día de hoy, '\n"
                + "            ELSE ''\n"
                + "        END ||\n"
                + "\n"
                + "        CASE\n"
                + "            WHEN FECHA_SENTENCIA > SYSDATE THEN\n"
                + "                'FECHA_SENTENCIA (' || TO_CHAR(FECHA_SENTENCIA,'DD/MM/YYYY') || ') es mayor al día de hoy, '\n"
                + "            ELSE ''\n"
                + "        END ||\n"
                + "\n"
                + "        CASE\n"
                + "            WHEN FECHA_DICTO_SOLUCION > SYSDATE THEN\n"
                + "                'FECHA_DICTO_SOLUCION (' || TO_CHAR(FECHA_DICTO_SOLUCION,'DD/MM/YYYY') || ') es mayor al día de hoy, '\n"
                + "            ELSE ''\n"
                + "        END,\n"
                + "    ', ') AS CAMPOS_CON_ERROR\n"
                + "\n"
                + "FROM TR_FED_ORDINARIO\n"
                + "\n"
                + "WHERE\n"
                + "       FECHA_PRESENTACION > SYSDATE\n"
                + "    OR FECHA_APERTURA_EXPEDIENTE > SYSDATE\n"
                + "    OR FECHA_ADM_DEMANDA > SYSDATE\n"
                + "    OR FECHA_ULT_ACT_PROC > SYSDATE\n"
                + "    OR FECHA_AUDIENCIA_PRELIM > SYSDATE\n"
                + "    OR FECHA_AUD_JUICIO > SYSDATE\n"
                + "    OR FECHA_SENTENCIA > SYSDATE\n"
                + "    OR FECHA_DICTO_SOLUCION > SYSDATE\n"
                + "\n"
                + "ORDER BY\n"
                + "    NOMBRE_ORGANO_JURIS,\n"
                + "    CLAVE_EXPEDIENTE";
        System.out.println(sql);
        resul = conexion.consultarFed(sql);
        try {
            while (resul.next()) {
                Array.add(new String[]{
                    resul.getString("id_organoj"),
                    resul.getString("clave_expediente"),
                    resul.getString("campos_con_error")});
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(RF_Fechas_Ordinario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Array;
    }

    public ArrayList Fed_OrdinarioFPresentacion() {
        conexion.ConectarFed();
        Array = new ArrayList();
        sql = "WITH fechas AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "WITH fechas AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        fecha_presentacion,\n"
                + "        fecha_apertura_expediente,\n"
                + "        fecha_adm_demanda,\n"
                + "        fecha_ult_act_proc,\n"
                + "        fecha_audiencia_prelim,\n"
                + "        fecha_aud_juicio,\n"
                + "        fecha_sentencia,\n"
                + "        fecha_dicto_solucion,\n"
                + "\n"
                + "        nullif(fecha_presentacion, DATE '1899-09-09')        AS fecha_presentacion_valida,\n"
                + "        nullif(fecha_apertura_expediente, DATE '1899-09-09') AS fecha_apertura_expediente_valida,\n"
                + "        nullif(fecha_adm_demanda, DATE '1899-09-09')         AS fecha_adm_demanda_valida,\n"
                + "        nullif(fecha_ult_act_proc, DATE '1899-09-09')        AS fecha_ult_act_proc_valida,\n"
                + "        nullif(fecha_audiencia_prelim, DATE '1899-09-09')    AS fecha_audiencia_prelim_valida,\n"
                + "        nullif(fecha_aud_juicio, DATE '1899-09-09')          AS fecha_aud_juicio_valida,\n"
                + "        nullif(fecha_sentencia, DATE '1899-09-09')           AS fecha_sentencia_valida,\n"
                + "        nullif(fecha_dicto_solucion, DATE '1899-09-09')      AS fecha_dicto_solucion_valida\n"
                + "    FROM\n"
                + "        tr_fed_ordinario\n"
                + "), validacion AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        fecha_presentacion,\n"
                + "        fecha_apertura_expediente,\n"
                + "        fecha_adm_demanda,\n"
                + "        fecha_ult_act_proc,\n"
                + "        fecha_audiencia_prelim,\n"
                + "        fecha_aud_juicio,\n"
                + "        fecha_sentencia,\n"
                + "        fecha_dicto_solucion,\n"
                + "        rtrim(\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida > fecha_apertura_expediente_valida THEN\n"
                + "                    'FECHA_APERTURA_EXPEDIENTE ('\n"
                + "                    || to_char(fecha_apertura_expediente, 'DD/MM/YYYY')\n"
                + "                    || ') es menor que FECHA_PRESENTACION ('\n"
                + "                    || to_char(fecha_audiencia_prelim, 'DD/MM/YYYY')\n"
                + "                    || '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida > fecha_adm_demanda_valida THEN\n"
                + "                    'FECHA_ADM_DEMANDA ('\n"
                + "                    || to_char(fecha_adm_demanda, 'DD/MM/YYYY')\n"
                + "                    || ') es menor que FECHA_PRESENTACION ('\n"
                + "                    || to_char(fecha_audiencia_prelim, 'DD/MM/YYYY')\n"
                + "                    || '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida > fecha_ult_act_proc_valida THEN\n"
                + "                    'FECHA_ULT_ACT_PROC ('\n"
                + "                    || to_char(fecha_ult_act_proc, 'DD/MM/YYYY')\n"
                + "                    || ') es menor que FECHA_PRESENTACION ('\n"
                + "                    || to_char(fecha_audiencia_prelim, 'DD/MM/YYYY')\n"
                + "                    || '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida > fecha_audiencia_prelim_valida THEN\n"
                + "                    'FECHA_AUDIENCIA_PRELIM ('\n"
                + "                    || to_char(fecha_audiencia_prelim, 'DD/MM/YYYY')\n"
                + "                    || ') es menor que FECHA_PRESENTACION ('\n"
                + "                    || to_char(fecha_audiencia_prelim, 'DD/MM/YYYY')\n"
                + "                    || '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida > fecha_aud_juicio_valida THEN\n"
                + "                    'FECHA_AUD_JUICIO ('\n"
                + "                    || to_char(fecha_aud_juicio, 'DD/MM/YYYY')\n"
                + "                    || ') es menor que FECHA_PRESENTACION ('\n"
                + "                    || to_char(fecha_audiencia_prelim, 'DD/MM/YYYY')\n"
                + "                    || '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida > fecha_sentencia_valida THEN\n"
                + "                    'FECHA_SENTENCIA ('\n"
                + "                    || to_char(fecha_sentencia, 'DD/MM/YYYY')\n"
                + "                    || ') es menor que FECHA_PRESENTACION ('\n"
                + "                    || to_char(fecha_audiencia_prelim, 'DD/MM/YYYY')\n"
                + "                    || '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            || CASE\n"
                + "            WHEN fecha_presentacion_valida > fecha_dicto_solucion_valida THEN\n"
                + "                'FECHA_DICTO_SOLUCION ('\n"
                + "                || to_char(fecha_dicto_solucion, 'DD/MM/YYYY')\n"
                + "                || ') es menor que FECHA_PRESENTACION ('\n"
                + "                || to_char(fecha_audiencia_prelim, 'DD/MM/YYYY')\n"
                + "                || '), '\n"
                + "            ELSE ''\n"
                + "        END) AS campos_con_error\n"
                + "    FROM\n"
                + "        fechas\n"
                + ")\n"
                + "SELECT\n"
                + "    nombre_organo_juris,\n"
                + "    id_organoj,\n"
                + "    clave_expediente,\n"
                + "    fecha_presentacion,\n"
                + "    fecha_apertura_expediente,\n"
                + "    fecha_adm_demanda,\n"
                + "    fecha_ult_act_proc,\n"
                + "    fecha_audiencia_prelim,\n"
                + "    fecha_aud_juicio,\n"
                + "    fecha_sentencia,\n"
                + "    fecha_dicto_solucion,\n"
                + "    campos_con_error\n"
                + "FROM\n"
                + "    validacion\n"
                + "WHERE\n"
                + "    campos_con_error IS NOT NULL\n"
                + "ORDER BY\n"
                + "    nombre_organo_juris,\n"
                + "    clave_expediente";
        System.out.println(sql);
        resul = conexion.consultarFed(sql);
        try {
            while (resul.next()) {
                Array.add(new String[]{
                    resul.getString("id_organoj"),
                    resul.getString("clave_expediente"),
                    resul.getString("campos_con_error")});
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(RF_Fechas_Ordinario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Array;
    }

    public ArrayList Fed_OrdinarioFPresentacion2() {
        conexion.ConectarFed();
        Array = new ArrayList();
        sql = "RTRIM(\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida IS NOT NULL\n"
                + "                 AND fecha_apertura_expediente_valida IS NOT NULL\n"
                + "                 AND fecha_presentacion_valida >\n"
                + "                     fecha_apertura_expediente_valida\n"
                + "                THEN\n"
                + "                    'FECHA_APERTURA_EXPEDIENTE (' ||\n"
                + "                    TO_CHAR(fecha_apertura_expediente, 'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_PRESENTACION (' ||\n"
                + "                    TO_CHAR(fecha_presentacion, 'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida IS NOT NULL\n"
                + "                 AND fecha_adm_demanda_valida IS NOT NULL\n"
                + "                 AND fecha_presentacion_valida >\n"
                + "                     fecha_adm_demanda_valida\n"
                + "                THEN\n"
                + "                    'FECHA_ADM_DEMANDA (' ||\n"
                + "                    TO_CHAR(fecha_adm_demanda, 'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_PRESENTACION (' ||\n"
                + "                    TO_CHAR(fecha_presentacion, 'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida IS NOT NULL\n"
                + "                 AND fecha_ult_act_proc_valida IS NOT NULL\n"
                + "                 AND fecha_presentacion_valida >\n"
                + "                     fecha_ult_act_proc_valida\n"
                + "                THEN\n"
                + "                    'FECHA_ULT_ACT_PROC (' ||\n"
                + "                    TO_CHAR(fecha_ult_act_proc, 'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_PRESENTACION (' ||\n"
                + "                    TO_CHAR(fecha_presentacion, 'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida IS NOT NULL\n"
                + "                 AND fecha_audiencia_prelim_valida IS NOT NULL\n"
                + "                 AND fecha_presentacion_valida >\n"
                + "                     fecha_audiencia_prelim_valida\n"
                + "                THEN\n"
                + "                    'FECHA_AUDIENCIA_PRELIM (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim, 'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_PRESENTACION (' ||\n"
                + "                    TO_CHAR(fecha_presentacion, 'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida IS NOT NULL\n"
                + "                 AND fecha_aud_juicio_valida IS NOT NULL\n"
                + "                 AND fecha_presentacion_valida >\n"
                + "                     fecha_aud_juicio_valida\n"
                + "                THEN\n"
                + "                    'FECHA_AUD_JUICIO (' ||\n"
                + "                    TO_CHAR(fecha_aud_juicio, 'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_PRESENTACION (' ||\n"
                + "                    TO_CHAR(fecha_presentacion, 'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida IS NOT NULL\n"
                + "                 AND fecha_sentencia_valida IS NOT NULL\n"
                + "                 AND fecha_presentacion_valida >\n"
                + "                     fecha_sentencia_valida\n"
                + "                THEN\n"
                + "                    'FECHA_SENTENCIA (' ||\n"
                + "                    TO_CHAR(fecha_sentencia, 'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_PRESENTACION (' ||\n"
                + "                    TO_CHAR(fecha_presentacion, 'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN fecha_presentacion_valida IS NOT NULL\n"
                + "                 AND fecha_dicto_solucion_valida IS NOT NULL\n"
                + "                 AND fecha_presentacion_valida >\n"
                + "                     fecha_dicto_solucion_valida\n"
                + "                THEN\n"
                + "                    'FECHA_DICTO_SOLUCION (' ||\n"
                + "                    TO_CHAR(fecha_dicto_solucion, 'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_PRESENTACION (' ||\n"
                + "                    TO_CHAR(fecha_presentacion, 'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END,\n"
                + "            ', '\n"
                + "        ) AS campos_con_error\n"
                + "    FROM fechas\n"
                + ")\n"
                + "SELECT\n"
                + "    nombre_organo_juris,\n"
                + "    id_organoj,\n"
                + "    clave_expediente,\n"
                + "    fecha_presentacion,\n"
                + "    fecha_apertura_expediente,\n"
                + "    fecha_adm_demanda,\n"
                + "    fecha_ult_act_proc,\n"
                + "    fecha_audiencia_prelim,\n"
                + "    fecha_aud_juicio,\n"
                + "    fecha_sentencia,\n"
                + "    fecha_dicto_solucion,\n"
                + "    campos_con_error\n"
                + "FROM validacion\n"
                + "WHERE campos_con_error IS NOT NULL\n"
                + "ORDER BY\n"
                + "    nombre_organo_juris,\n"
                + "    clave_expediente";
        System.out.println(sql);
        resul = conexion.consultarFed(sql);
        try {
            while (resul.next()) {
                Array.add(new String[]{
                    resul.getString("id_organoj"),
                    resul.getString("clave_expediente"),
                    resul.getString("campos_con_error")});
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(RF_Fechas_Ordinario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Array;
    }

    public ArrayList Fed_OrdinarioFAdmisionDemanda() {
        conexion.ConectarFed();
        Array = new ArrayList();
        sql = "ITH fechas AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "NULLIF(FECHA_PRESENTACION, DATE '1899-09-09') AS FECHA_PRESENTACION_valida,\n"
                + "NULLIF(FECHA_APERTURA_EXPEDIENTE, DATE '1899-09-09') AS FECHA_APERTURA_EXPEDIENTE_valida,\n"
                + "NULLIF(FECHA_ADM_DEMANDA, DATE '1899-09-09') AS FECHA_ADM_DEMANDA_valida,\n"
                + "NULLIF(FECHA_ULT_ACT_PROC, DATE '1899-09-09') AS FECHA_ULT_ACT_PROC_valida,\n"
                + "NULLIF(FECHA_AUDIENCIA_PRELIM, DATE '1899-09-09') AS FECHA_AUDIENCIA_PRELIM_valida,\n"
                + "NULLIF(FECHA_AUD_JUICIO, DATE '1899-09-09') AS FECHA_AUD_JUICIO_valida,\n"
                + "NULLIF(FECHA_SENTENCIA, DATE '1899-09-09') AS FECHA_SENTENCIA_valida,\n"
                + "NULLIF(FECHA_DICTO_SOLUCION, DATE '1899-09-09') AS FECHA_DICTO_SOLUCION_valida\n"
                + "\n"
                + "        FROM tr_fed_ordinario\n"
                + "),\n"
                + "validacion AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "\n"
                + "       RTRIM(\n"
                + "            \n"
                + "            CASE\n"
                + "                WHEN FECHA_ADM_DEMANDA_valida> FECHA_ULT_ACT_PROC_valida THEN\n"
                + "                    'FECHA_ULT_ACT_PROC (' ||\n"
                + "                    TO_CHAR(FECHA_ULT_ACT_PROC,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_ADM_DEMANDA (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_ADM_DEMANDA_valida> FECHA_AUDIENCIA_PRELIM_valida THEN\n"
                + "                    'FECHA_AUDIENCIA_PRELIM (' ||\n"
                + "                    TO_CHAR(FECHA_AUDIENCIA_PRELIM,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_ADM_DEMANDA (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_ADM_DEMANDA_valida> FECHA_AUD_JUICIO_valida THEN\n"
                + "                    'FECHA_AUD_JUICIO (' ||\n"
                + "                    TO_CHAR(FECHA_AUD_JUICIO,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_ADM_DEMANDA (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_ADM_DEMANDA_valida> FECHA_SENTENCIA_valida THEN\n"
                + "                    'FECHA_SENTENCIA (' ||\n"
                + "                    TO_CHAR(FECHA_SENTENCIA,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_ADM_DEMANDA (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_ADM_DEMANDA_valida> FECHA_DICTO_SOLUCION_valida THEN\n"
                + "                    'FECHA_DICTO_SOLUCION (' ||\n"
                + "                    TO_CHAR(FECHA_DICTO_SOLUCION,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_ADM_DEMANDA (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "\n"
                + "        ) AS campos_con_error\n"
                + "    FROM fechas\n"
                + ")\n"
                + "\n"
                + "SELECT\n"
                + "    nombre_organo_juris,\n"
                + "    id_organoj,\n"
                + "    clave_expediente,FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "    campos_con_error\n"
                + "FROM validacion\n"
                + "WHERE campos_con_error IS NOT NULL\n"
                + "ORDER BY\n"
                + "    nombre_organo_juris,\n"
                + "    clave_expediente";
        System.out.println(sql);
        resul = conexion.consultarFed(sql);
        try {
            while (resul.next()) {
                Array.add(new String[]{
                    resul.getString("id_organoj"),
                    resul.getString("clave_expediente"),
                    resul.getString("campos_con_error")});
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(RF_Fechas_Ordinario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Array;
    }

    public ArrayList Fed_Ordinario_FUltimoActoProcesal() {
        conexion.ConectarFed();
        Array = new ArrayList();
        sql = "WITH fechas AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "NULLIF(FECHA_PRESENTACION, DATE '1899-09-09') AS FECHA_PRESENTACION_valida,\n"
                + "NULLIF(FECHA_APERTURA_EXPEDIENTE, DATE '1899-09-09') AS FECHA_APERTURA_EXPEDIENTE_valida,\n"
                + "NULLIF(FECHA_ADM_DEMANDA, DATE '1899-09-09') AS FECHA_ADM_DEMANDA_valida,\n"
                + "NULLIF(FECHA_ULT_ACT_PROC, DATE '1899-09-09') AS FECHA_ULT_ACT_PROC_valida,\n"
                + "NULLIF(FECHA_AUDIENCIA_PRELIM, DATE '1899-09-09') AS FECHA_AUDIENCIA_PRELIM_valida,\n"
                + "NULLIF(FECHA_AUD_JUICIO, DATE '1899-09-09') AS FECHA_AUD_JUICIO_valida,\n"
                + "NULLIF(FECHA_SENTENCIA, DATE '1899-09-09') AS FECHA_SENTENCIA_valida,\n"
                + "NULLIF(FECHA_DICTO_SOLUCION, DATE '1899-09-09') AS FECHA_DICTO_SOLUCION_valida\n"
                + "\n"
                + "        FROM tr_fed_ordinario\n"
                + "),\n"
                + "validacion AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "\n"
                + "      RTRIM(\n"
                + "            \n"
                + "            \n"
                + "            CASE\n"
                + "                WHEN FECHA_ULT_ACT_PROC_valida> FECHA_AUDIENCIA_PRELIM_valida THEN\n"
                + "                    'FECHA_AUDIENCIA_PRELIM (' ||\n"
                + "                    TO_CHAR(FECHA_AUDIENCIA_PRELIM,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_ULT_ACT_PROC (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_ULT_ACT_PROC_valida> FECHA_AUD_JUICIO_valida THEN\n"
                + "                    'FECHA_AUD_JUICIO (' ||\n"
                + "                    TO_CHAR(FECHA_AUD_JUICIO,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_ULT_ACT_PROC (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_ULT_ACT_PROC_valida> FECHA_SENTENCIA_valida THEN\n"
                + "                    'FECHA_SENTENCIA (' ||\n"
                + "                    TO_CHAR(FECHA_SENTENCIA,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_ULT_ACT_PROC (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_ULT_ACT_PROC_valida> FECHA_DICTO_SOLUCION_valida THEN\n"
                + "                    'FECHA_DICTO_SOLUCION (' ||\n"
                + "                    TO_CHAR(FECHA_DICTO_SOLUCION,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_ULT_ACT_PROC (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "\n"
                + "        ) AS campos_con_error\n"
                + "    FROM fechas\n"
                + ")\n"
                + "\n"
                + "SELECT\n"
                + "    nombre_organo_juris,\n"
                + "    id_organoj,\n"
                + "    clave_expediente,FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "    campos_con_error\n"
                + "FROM validacion\n"
                + "WHERE campos_con_error IS NOT NULL\n"
                + "ORDER BY\n"
                + "    nombre_organo_juris,\n"
                + "    clave_expediente";
        System.out.println(sql);
        resul = conexion.consultarFed(sql);
        try {
            while (resul.next()) {
                Array.add(new String[]{
                    resul.getString("id_organoj"),
                    resul.getString("clave_expediente"),
                    resul.getString("campos_con_error")});
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(RF_Fechas_Ordinario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Array;
    }

    public ArrayList Fed_Ordinario_FAudienciaPreliminar() {
        conexion.ConectarFed();
        Array = new ArrayList();
        sql = "WITH fechas AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "NULLIF(FECHA_PRESENTACION, DATE '1899-09-09') AS FECHA_PRESENTACION_valida,\n"
                + "NULLIF(FECHA_APERTURA_EXPEDIENTE, DATE '1899-09-09') AS FECHA_APERTURA_EXPEDIENTE_valida,\n"
                + "NULLIF(FECHA_ADM_DEMANDA, DATE '1899-09-09') AS FECHA_ADM_DEMANDA_valida,\n"
                + "NULLIF(FECHA_ULT_ACT_PROC, DATE '1899-09-09') AS FECHA_ULT_ACT_PROC_valida,\n"
                + "NULLIF(FECHA_AUDIENCIA_PRELIM, DATE '1899-09-09') AS FECHA_AUDIENCIA_PRELIM_valida,\n"
                + "NULLIF(FECHA_AUD_JUICIO, DATE '1899-09-09') AS FECHA_AUD_JUICIO_valida,\n"
                + "NULLIF(FECHA_SENTENCIA, DATE '1899-09-09') AS FECHA_SENTENCIA_valida,\n"
                + "NULLIF(FECHA_DICTO_SOLUCION, DATE '1899-09-09') AS FECHA_DICTO_SOLUCION_valida\n"
                + "\n"
                + "        FROM tr_fed_ordinario\n"
                + "),\n"
                + "validacion AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "\n"
                + "     RTRIM(\n"
                + "            \n"
                + "            \n"
                + "            \n"
                + "            CASE\n"
                + "                WHEN FECHA_AUDIENCIA_PRELIM_valida> FECHA_AUD_JUICIO_valida THEN\n"
                + "                    'FECHA_AUD_JUICIO (' ||\n"
                + "                    TO_CHAR(FECHA_AUD_JUICIO,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_AUDIENCIA_PRELIM (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_AUDIENCIA_PRELIM_valida> FECHA_SENTENCIA_valida THEN\n"
                + "                    'FECHA_SENTENCIA (' ||\n"
                + "                    TO_CHAR(FECHA_SENTENCIA,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_AUDIENCIA_PRELIM (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_AUDIENCIA_PRELIM_valida> FECHA_DICTO_SOLUCION_valida THEN\n"
                + "                    'FECHA_DICTO_SOLUCION (' ||\n"
                + "                    TO_CHAR(FECHA_DICTO_SOLUCION,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_AUDIENCIA_PRELIM (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "\n"
                + "        ) AS campos_con_error\n"
                + "    FROM fechas\n"
                + ")\n"
                + "\n"
                + "SELECT\n"
                + "    nombre_organo_juris,\n"
                + "    id_organoj,\n"
                + "    clave_expediente,FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "    campos_con_error\n"
                + "FROM validacion\n"
                + "WHERE campos_con_error IS NOT NULL\n"
                + "ORDER BY\n"
                + "    nombre_organo_juris,\n"
                + "    clave_expediente";
        System.out.println(sql);
        resul = conexion.consultarFed(sql);
        try {
            while (resul.next()) {
                Array.add(new String[]{
                    resul.getString("id_organoj"),
                    resul.getString("clave_expediente"),
                    resul.getString("campos_con_error")});
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(RF_Fechas_Ordinario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Array;
    }

    public ArrayList Fed_Ordinario_FAudienciaJuicio() {
        conexion.ConectarFed();
        Array = new ArrayList();
        sql = "WITH fechas AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "NULLIF(FECHA_PRESENTACION, DATE '1899-09-09') AS FECHA_PRESENTACION_valida,\n"
                + "NULLIF(FECHA_APERTURA_EXPEDIENTE, DATE '1899-09-09') AS FECHA_APERTURA_EXPEDIENTE_valida,\n"
                + "NULLIF(FECHA_ADM_DEMANDA, DATE '1899-09-09') AS FECHA_ADM_DEMANDA_valida,\n"
                + "NULLIF(FECHA_ULT_ACT_PROC, DATE '1899-09-09') AS FECHA_ULT_ACT_PROC_valida,\n"
                + "NULLIF(FECHA_AUDIENCIA_PRELIM, DATE '1899-09-09') AS FECHA_AUDIENCIA_PRELIM_valida,\n"
                + "NULLIF(FECHA_AUD_JUICIO, DATE '1899-09-09') AS FECHA_AUD_JUICIO_valida,\n"
                + "NULLIF(FECHA_SENTENCIA, DATE '1899-09-09') AS FECHA_SENTENCIA_valida,\n"
                + "NULLIF(FECHA_DICTO_SOLUCION, DATE '1899-09-09') AS FECHA_DICTO_SOLUCION_valida\n"
                + "\n"
                + "        FROM tr_fed_ordinario\n"
                + "),\n"
                + "validacion AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "\n"
                + "     RTRIM(\n"
                + "            CASE\n"
                + "                WHEN FECHA_AUD_JUICIO_valida> FECHA_SENTENCIA_valida THEN\n"
                + "                    'FECHA_SENTENCIA (' ||\n"
                + "                    TO_CHAR(FECHA_SENTENCIA,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_AUD_JUICIO (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "            ||\n"
                + "            CASE\n"
                + "                WHEN FECHA_AUD_JUICIO_valida> FECHA_DICTO_SOLUCION_valida THEN\n"
                + "                    'FECHA_DICTO_SOLUCION (' ||\n"
                + "                    TO_CHAR(FECHA_DICTO_SOLUCION,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_AUD_JUICIO (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "\n"
                + "        ) AS campos_con_error\n"
                + "    FROM fechas\n"
                + ")\n"
                + "\n"
                + "SELECT\n"
                + "    nombre_organo_juris,\n"
                + "    id_organoj,\n"
                + "    clave_expediente,FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "    campos_con_error\n"
                + "FROM validacion\n"
                + "WHERE campos_con_error IS NOT NULL\n"
                + "ORDER BY\n"
                + "    nombre_organo_juris,\n"
                + "    clave_expediente";
        System.out.println(sql);
        resul = conexion.consultarFed(sql);
        try {
            while (resul.next()) {
                Array.add(new String[]{
                    resul.getString("id_organoj"),
                    resul.getString("clave_expediente"),
                    resul.getString("campos_con_error")});
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(RF_Fechas_Ordinario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Array;
    }

    public ArrayList Fed_Ordinario_FSentencia() {
        conexion.ConectarFed();
        Array = new ArrayList();
        sql = "WITH fechas AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "NULLIF(FECHA_PRESENTACION, DATE '1899-09-09') AS FECHA_PRESENTACION_valida,\n"
                + "NULLIF(FECHA_APERTURA_EXPEDIENTE, DATE '1899-09-09') AS FECHA_APERTURA_EXPEDIENTE_valida,\n"
                + "NULLIF(FECHA_ADM_DEMANDA, DATE '1899-09-09') AS FECHA_ADM_DEMANDA_valida,\n"
                + "NULLIF(FECHA_ULT_ACT_PROC, DATE '1899-09-09') AS FECHA_ULT_ACT_PROC_valida,\n"
                + "NULLIF(FECHA_AUDIENCIA_PRELIM, DATE '1899-09-09') AS FECHA_AUDIENCIA_PRELIM_valida,\n"
                + "NULLIF(FECHA_AUD_JUICIO, DATE '1899-09-09') AS FECHA_AUD_JUICIO_valida,\n"
                + "NULLIF(FECHA_SENTENCIA, DATE '1899-09-09') AS FECHA_SENTENCIA_valida,\n"
                + "NULLIF(FECHA_DICTO_SOLUCION, DATE '1899-09-09') AS FECHA_DICTO_SOLUCION_valida\n"
                + "\n"
                + "        FROM tr_fed_ordinario\n"
                + "),\n"
                + "validacion AS (\n"
                + "    SELECT\n"
                + "        nombre_organo_juris,\n"
                + "        id_organoj,\n"
                + "        clave_expediente,\n"
                + "        FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "\n"
                + "\n"
                + "     RTRIM(\n"
                + "            \n"
                + "            CASE\n"
                + "                WHEN FECHA_SENTENCIA_valida> FECHA_DICTO_SOLUCION_valida THEN\n"
                + "                    'FECHA_DICTO_SOLUCION (' ||\n"
                + "                    TO_CHAR(FECHA_DICTO_SOLUCION,'DD/MM/YYYY') ||\n"
                + "                    ') es menor que FECHA_SENTENCIA (' ||\n"
                + "                    TO_CHAR(fecha_audiencia_prelim,'DD/MM/YYYY') ||\n"
                + "                    '), '\n"
                + "                ELSE ''\n"
                + "            END\n"
                + "\n"
                + "        ) AS campos_con_error\n"
                + "    FROM fechas\n"
                + ")\n"
                + "\n"
                + "SELECT\n"
                + "    nombre_organo_juris,\n"
                + "    id_organoj,\n"
                + "    clave_expediente,FECHA_PRESENTACION,\n"
                + "FECHA_APERTURA_EXPEDIENTE,\n"
                + "FECHA_ADM_DEMANDA ,\n"
                + "FECHA_ULT_ACT_PROC,\n"
                + "FECHA_AUDIENCIA_PRELIM,\n"
                + "FECHA_AUD_JUICIO,\n"
                + "FECHA_SENTENCIA,\n"
                + "FECHA_DICTO_SOLUCION,\n"
                + "    campos_con_error\n"
                + "FROM validacion\n"
                + "WHERE campos_con_error IS NOT NULL\n"
                + "ORDER BY\n"
                + "    nombre_organo_juris,\n"
                + "    clave_expediente";
        System.out.println(sql);
        resul = conexion.consultarFed(sql);
        try {
            while (resul.next()) {
                Array.add(new String[]{
                    resul.getString("id_organoj"),
                    resul.getString("clave_expediente"),
                    resul.getString("campos_con_error")});
            }
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(RF_Fechas_Ordinario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Array;
    }

}
